// Unit 14 vocab still-icons. Catalog rows are the library record; this table is the runtime lookup.
const UNIT14_VOCAB_ART_ROWS = [
  { ko: '반말을 하다', slug: 'speak_banmal', folder: 'items', nameEn: 'Speaking banmal', family: 'etiquette' },
  { ko: '높임말[존댓말]을 하다', slug: 'speak_honorific', folder: 'items', nameEn: 'Speaking honorifics', family: 'etiquette' },
  { ko: '이름을 부르다', slug: 'call_by_name', folder: 'items', nameEn: 'Calling someone by name', family: 'etiquette' },
  { ko: '한 손으로 받다', slug: 'receive_one_hand', folder: 'items', nameEn: 'Receiving with one hand', family: 'etiquette' },
  { ko: '두 손으로 드리다', slug: 'give_two_hands', folder: 'items', nameEn: 'Giving with both hands', family: 'etiquette' },
  { ko: '자리를 양보하다', slug: 'yield_seat', folder: 'items', nameEn: 'Yielding a seat', family: 'etiquette' },
  { ko: '다리를 꼬고 앉다', slug: 'sit_cross_legged', folder: 'items', nameEn: 'Sitting with legs crossed', family: 'etiquette' },
  { ko: '고개를 돌리고 마시다', slug: 'turn_head_drink', folder: 'items', nameEn: 'Turning the head while drinking', family: 'etiquette' },
  { ko: '고개를 숙여서 인사하다', slug: 'bow_greeting', folder: 'items', nameEn: 'Bowing in greeting', family: 'etiquette' },
  { ko: '야단(을) 맞다', slug: 'get_scolded', folder: 'items', nameEn: 'Getting scolded', family: 'etiquette' },
  { ko: '금연', slug: 'no_smoking', folder: 'items', nameEn: 'No smoking', family: 'sign' },
  { ko: '주차 금지', slug: 'no_parking', folder: 'items', nameEn: 'No parking', family: 'sign' },
  { ko: '사진 촬영 금지', slug: 'no_photography', folder: 'items', nameEn: 'No photographs', family: 'sign' },
  { ko: '음식물 반입 금지', slug: 'no_food_or_drinks', folder: 'items', nameEn: 'No food or drinks', family: 'sign' },
  { ko: '휴대 전화 사용 금지', slug: 'no_cell_phones', folder: 'items', nameEn: 'No cell phones', family: 'sign' },
  { ko: '음식물을 먹다', slug: 'eat_food', folder: 'items', nameEn: 'Eating food', family: 'action' },
  { ko: '전화를 하다', slug: 'make_phone_call', folder: 'items', nameEn: 'Making a phone call', family: 'action' },
  { ko: '시끄럽게 하다', slug: 'make_noise', folder: 'items', nameEn: 'Making noise', family: 'action' },
  { ko: '자리를 바꾸다', slug: 'swap_seats', folder: 'items', nameEn: 'Swapping seats', family: 'action' },
  { ko: '밖으로 나가다', slug: 'go_outside', folder: 'items', nameEn: 'Going outside', family: 'action' },
  { ko: '휴대전화를 끄다', slug: 'turn_off_phone', folder: 'items', nameEn: 'Turning off a cell phone', family: 'action' },
  { ko: '실수하다', slug: 'make_mistake', folder: 'items', nameEn: 'Making a mistake', family: 'emotion' },
  { ko: '창피하다', slug: 'feel_embarrassed', folder: 'items', nameEn: 'Feeling embarrassed', family: 'emotion' },
  { ko: '어색하다', slug: 'feel_awkward', folder: 'items', nameEn: 'Feeling awkward', family: 'emotion' },
  { ko: '의사 선생님', slug: 'doctor', folder: 'items', nameEn: 'Doctor (honorific)', family: 'people' },
  { ko: '처음 만난 사람', slug: 'first_meeting', folder: 'items', nameEn: 'A person met for the first time', family: 'people' },
  { ko: '물론이지', slug: 'of_course', folder: 'items', nameEn: 'Of course', family: 'abstract' },
  { ko: '잊어버리다', slug: 'forget', folder: 'items', nameEn: 'Forgetting', family: 'abstract' },
  { ko: '복잡하다', slug: 'complicated', folder: 'items', nameEn: 'Being complicated', family: 'abstract' },
  { ko: '우리나라', slug: 'our_country', folder: 'items', nameEn: 'Our country', family: 'place' },
  { ko: '비슷하다', slug: 'similar', folder: 'items', nameEn: 'Being similar', family: 'abstract' },
  { ko: '다르다', slug: 'different', folder: 'items', nameEn: 'Being different', family: 'abstract' },
  { ko: '가까운 나라', slug: 'neighboring_country', folder: 'items', nameEn: 'A neighboring country', family: 'place' },
  { ko: '지각하다', slug: 'be_late', folder: 'items', nameEn: 'Arriving late', family: 'abstract' },
  { ko: '공연', slug: 'performance', folder: 'items', nameEn: 'Performance / concert', family: 'place' },
  { ko: '시작되다', slug: 'to_begin', folder: 'items', nameEn: 'To begin', family: 'abstract' },
  { ko: '안내 방송', slug: 'announcement', folder: 'items', nameEn: 'Announcement', family: 'sign' },
  { ko: '지키다', slug: 'keep_rules', folder: 'items', nameEn: 'Keeping the rules', family: 'sign' },
  { ko: '어기다', slug: 'break_rules', folder: 'items', nameEn: 'Breaking the rules', family: 'sign' },
  { ko: '기숙사 규칙', slug: 'dorm_rules', folder: 'items', nameEn: 'Dormitory rules', family: 'sign' },
  { ko: '공중도덕', slug: 'public_etiquette', folder: 'items', nameEn: 'Public etiquette', family: 'abstract' },
  { ko: '식당', slug: 'cafeteria', folder: 'items', nameEn: 'Cafeteria', family: 'place' },
  { ko: '운동 시설', slug: 'sports_facility', folder: 'items', nameEn: 'Sports facility', family: 'place' },
  { ko: '무료로 이용하다', slug: 'use_for_free', folder: 'items', nameEn: 'Using for free', family: 'abstract' },
  { ko: '문화 차이', slug: 'cultural_difference', folder: 'items', nameEn: 'Cultural differences', family: 'abstract' },
  { ko: '당황하다', slug: 'feel_flustered', folder: 'items', nameEn: 'Feeling flustered', family: 'emotion' },
  { ko: '왼손으로 물건을 주다', slug: 'give_left_hand', folder: 'items', nameEn: 'Giving with the left hand', family: 'etiquette' },
  { ko: '머리를 만지다', slug: 'touch_head', folder: 'items', nameEn: 'Touching someone\'s head', family: 'etiquette' },
  { ko: '경로 우대', slug: 'senior_preference', folder: 'items', nameEn: 'Senior-citizen preference', family: 'people' },
  { ko: '노인', slug: 'elderly', folder: 'items', nameEn: 'The elderly', family: 'people' },
  { ko: '몸이 불편한 사람', slug: 'disabled_person', folder: 'items', nameEn: 'A person with physical difficulties', family: 'people' },
  { ko: '비어 있다', slug: 'be_empty', folder: 'items', nameEn: 'Being empty / unoccupied', family: 'place' },
  { ko: '입장료 할인', slug: 'admission_discount', folder: 'items', nameEn: 'Admission-fee discount', family: 'abstract' },
  { ko: '제도', slug: 'system_policy', folder: 'items', nameEn: 'System / policy', family: 'abstract' }
];
if (typeof VOCAB_ART_ROWS !== 'undefined' && Array.isArray(VOCAB_ART_ROWS)) {
  UNIT14_VOCAB_ART_ROWS.forEach(function (r) { VOCAB_ART_ROWS.push(r); });
}
if (typeof window !== 'undefined') {
  window.UNIT14_VOCAB_ART_ROWS = UNIT14_VOCAB_ART_ROWS;
}
