// Extra unit 10 leftovers + unit 11/13 still-icons generated in the farm 16-bit set.
const VOCAB_ART_MORE_ROWS = [
  { ko: '짜장면', slug: 'jjajangmyeon', folder: 'foods', nameEn: 'Jjajangmyeon', family: 'noodle' },
  { ko: '생선회', slug: 'sashimi_plate', folder: 'foods', nameEn: 'Sliced raw fish', family: 'meat' },
  { ko: '케밥', slug: 'kebab_skewer', folder: 'foods', nameEn: 'Kebab', family: 'meat' },
  { ko: '간장', slug: 'soy_sauce', folder: 'items', nameEn: 'Soy sauce', family: 'ingredient' },
  { ko: '고추장', slug: 'gochujang_jar', folder: 'items', nameEn: 'Chili paste', family: 'ingredient' },
  { ko: '식초', slug: 'vinegar_bottle', folder: 'items', nameEn: 'Vinegar', family: 'ingredient' },
  { ko: '녹차', slug: 'green_tea', folder: 'foods', nameEn: 'Green tea', family: 'drink' },
  { ko: '우유', slug: 'milk_bottle', folder: 'foods', nameEn: 'Milk', family: 'drink' },
  { ko: '약', slug: 'medicine_bottle', folder: 'items', nameEn: 'Medicine', family: 'health' },
  { ko: '감기약', slug: 'medicine_capsule', folder: 'items', nameEn: 'Cold medicine', family: 'health' },
  { ko: '안약', slug: 'eye_drops', folder: 'items', nameEn: 'Eye drops', family: 'health' },
  { ko: '연고', slug: 'ointment_tube', folder: 'items', nameEn: 'Ointment', family: 'health' },
  { ko: '인삼', slug: 'ginseng_root', folder: 'items', nameEn: 'Korean ginseng', family: 'health' },
  { ko: '병원', slug: 'clinic_building', folder: 'items', nameEn: 'Hospital / clinic', family: 'place' },
  { ko: '약국', slug: 'pharmacy_shop', folder: 'items', nameEn: 'Pharmacy', family: 'place' },
  { ko: '원룸', slug: 'studio_oneroom', folder: 'items', nameEn: 'One-room studio', family: 'place' },
  { ko: '추천', slug: 'recommend', folder: 'items', nameEn: 'A recommendation', family: 'abstract' },
  { ko: '음식값', slug: 'price_coins', folder: 'items', nameEn: 'The food bill', family: 'abstract' },
  { ko: '전화를 걸다', slug: 'make_phone_call', folder: 'items', nameEn: 'To make a phone call', family: 'action' },
  { ko: '늦다', slug: 'be_late', folder: 'items', nameEn: 'To be late', family: 'abstract' },
  { ko: '채소', slug: 'vegetable_pile', folder: 'items', nameEn: 'Vegetables', family: 'ingredient' },
  { ko: '과일', slug: 'farm_apple', folder: 'items', nameEn: 'Fruit', family: 'ingredient' },
  { ko: '의사', slug: 'doctor', folder: 'items', nameEn: 'Doctor', family: 'people' },
  { ko: "파스", slug: 'heat_patch', folder: 'items', nameEn: "Medicated heat patch", family: 'health' },
  { ko: "붙이다", slug: 'heat_patch', folder: 'items', nameEn: "Medicated heat patch", family: 'health' },
  { ko: "다리를 다치다", slug: 'bandaged_boot', folder: 'items', nameEn: "Bandaged boot", family: 'health' },
  { ko: "몸살이 나다", slug: 'bandaged_boot', folder: 'items', nameEn: "Bandaged boot", family: 'health' },
  { ko: "머리가 아프다", slug: 'ice_pack', folder: 'items', nameEn: "Ice pack", family: 'health' },
  { ko: "두통약", slug: 'ice_pack', folder: 'items', nameEn: "Ice pack", family: 'health' },
  { ko: "어지럽다", slug: 'ice_pack', folder: 'items', nameEn: "Ice pack", family: 'health' },
  { ko: "붓다", slug: 'ice_pack', folder: 'items', nameEn: "Ice pack", family: 'health' },
  { ko: "어디가 아프다", slug: 'ice_pack', folder: 'items', nameEn: "Ice pack", family: 'health' },
  { ko: "안과", slug: 'eyeglasses', folder: 'items', nameEn: "Eyeglasses", family: 'health' },
  { ko: "눈이 아프다", slug: 'eyeglasses', folder: 'items', nameEn: "Eyeglasses", family: 'health' },
  { ko: "감기에 걸리다", slug: 'tissue_box', folder: 'items', nameEn: "Tissue box", family: 'health' },
  { ko: "기침이 나다", slug: 'tissue_box', folder: 'items', nameEn: "Tissue box", family: 'health' },
  { ko: "목이 붓다", slug: 'tissue_box', folder: 'items', nameEn: "Tissue box", family: 'health' },
  { ko: "이가 아프다", slug: 'cracked_tooth', folder: 'items', nameEn: "Aching tooth", family: 'health' },
  { ko: "치과", slug: 'cracked_tooth', folder: 'items', nameEn: "Aching tooth", family: 'health' },
  { ko: "내과", slug: 'stethoscope', folder: 'items', nameEn: "Stethoscope", family: 'health' },
  { ko: "진료를 받다", slug: 'stethoscope', folder: 'items', nameEn: "Stethoscope", family: 'health' },
  { ko: "환자", slug: 'stethoscope', folder: 'items', nameEn: "Stethoscope", family: 'health' },
  { ko: "열이 나다", slug: 'thermometer', folder: 'items', nameEn: "Thermometer", family: 'health' },
  { ko: "해열제", slug: 'thermometer', folder: 'items', nameEn: "Thermometer", family: 'health' },
  { ko: "낫다", slug: 'thermometer', folder: 'items', nameEn: "Thermometer", family: 'health' },
  { ko: "이비인후과", slug: 'human_ear', folder: 'items', nameEn: "Ear", family: 'health' },
  { ko: "설탕", slug: 'sugar_bowl', folder: 'items', nameEn: "Sugar bowl", family: 'ingredient' },
  { ko: "정형외과", slug: 'femur_bone', folder: 'items', nameEn: "Bone", family: 'health' },
  { ko: "젓다", slug: 'wooden_spoon', folder: 'items', nameEn: "Wooden spoon", family: 'action' },
  { ko: "처방", slug: 'prescription_slip', folder: 'items', nameEn: "Prescription", family: 'health' },
  { ko: "주의사항", slug: 'prescription_slip', folder: 'items', nameEn: "Prescription", family: 'health' },
  { ko: "소금", slug: 'salt_shaker', folder: 'items', nameEn: "Salt shaker", family: 'ingredient' },
  { ko: "싱겁다", slug: 'salt_shaker', folder: 'items', nameEn: "Salt shaker", family: 'ingredient' },
  { ko: "입맛이 없다", slug: 'empty_plate', folder: 'items', nameEn: "Empty plate", family: 'health' },
  { ko: "소화가 안되다", slug: 'empty_plate', folder: 'items', nameEn: "Empty plate", family: 'health' },
  { ko: "속이 안 좋다", slug: 'empty_plate', folder: 'items', nameEn: "Empty plate", family: 'health' },
  { ko: "배가 아프다", slug: 'empty_plate', folder: 'items', nameEn: "Empty plate", family: 'health' },
  { ko: "배탈이 나다", slug: 'empty_plate', folder: 'items', nameEn: "Empty plate", family: 'health' },
  { ko: "토하다", slug: 'empty_plate', folder: 'items', nameEn: "Empty plate", family: 'health' },
  { ko: "소화제", slug: 'empty_plate', folder: 'items', nameEn: "Empty plate", family: 'health' },
  { ko: "손을 씻다", slug: 'soap_bar', folder: 'items', nameEn: "Bar of soap", family: 'health' },
  { ko: "청소", slug: 'soap_bar', folder: 'items', nameEn: "Bar of soap", family: 'health' },
  { ko: "깨끗하다", slug: 'soap_bar', folder: 'items', nameEn: "Bar of soap", family: 'health' },
  { ko: "거실", slug: 'green_sofa', folder: 'items', nameEn: "Sofa", family: 'place' },
  { ko: "방", slug: 'green_sofa', folder: 'items', nameEn: "Sofa", family: 'place' },
  { ko: "아파트", slug: 'apartment_block', folder: 'items', nameEn: "Apartment block", family: 'place' },
  { ko: "주거", slug: 'apartment_block', folder: 'items', nameEn: "Apartment block", family: 'place' },
  { ko: "오피스텔", slug: 'apartment_block', folder: 'items', nameEn: "Apartment block", family: 'place' },
  { ko: "부동산", slug: 'apartment_block', folder: 'items', nameEn: "Apartment block", family: 'place' },
  { ko: "부엌", slug: 'kitchen_stove', folder: 'items', nameEn: "Kitchen stove", family: 'place' },
  { ko: "가스 요금", slug: 'kitchen_stove', folder: 'items', nameEn: "Kitchen stove", family: 'place' },
  { ko: "화장실", slug: 'toilet', folder: 'items', nameEn: "Toilet", family: 'place' },
  { ko: "한옥", slug: 'hanok_house', folder: 'items', nameEn: "Hanok", family: 'place' },
  { ko: "북촌 한옥마을", slug: 'hanok_house', folder: 'items', nameEn: "Hanok", family: 'place' },
  { ko: "민속촌", slug: 'hanok_house', folder: 'items', nameEn: "Hanok", family: 'place' },
  { ko: "기숙사", slug: 'dormitory', folder: 'items', nameEn: "Dormitory", family: 'place' },
  { ko: "이사하다", slug: 'moving_boxes', folder: 'items', nameEn: "Moving boxes", family: 'place' },
  { ko: "태어나다", slug: 'wrapped_baby', folder: 'items', nameEn: "Newborn", family: 'people' },
  { ko: "아기를 낳다", slug: 'wrapped_baby', folder: 'items', nameEn: "Newborn", family: 'people' },
  { ko: "아기", slug: 'wrapped_baby', folder: 'items', nameEn: "Newborn", family: 'people' },
  { ko: "결혼하다", slug: 'wedding_rings', folder: 'items', nameEn: "Wedding rings", family: 'people' },
  { ko: "출구", slug: 'exit_door', folder: 'items', nameEn: "Exit door", family: 'place' },
  { ko: "출입구", slug: 'exit_door', folder: 'items', nameEn: "Exit door", family: 'place' },
  { ko: "취직하다", slug: 'briefcase', folder: 'items', nameEn: "Briefcase", family: 'people' },
  { ko: "승진하다", slug: 'briefcase', folder: 'items', nameEn: "Briefcase", family: 'people' },
  { ko: "주택", slug: 'detached_house', folder: 'items', nameEn: "Detached house", family: 'place' },
  { ko: "짓다", slug: 'detached_house', folder: 'items', nameEn: "Detached house", family: 'place' },
  { ko: "빌라", slug: 'detached_house', folder: 'items', nameEn: "Detached house", family: 'place' },
  { ko: "졸업하다", slug: 'diploma_scroll', folder: 'items', nameEn: "Diploma", family: 'people' },
  { ko: "입학하다", slug: 'diploma_scroll', folder: 'items', nameEn: "Diploma", family: 'people' },
  { ko: "입학", slug: 'diploma_scroll', folder: 'items', nameEn: "Diploma", family: 'people' },
  { ko: "친구를 사귀다", slug: 'school_backpack', folder: 'items', nameEn: "School backpack", family: 'people' },
  { ko: "재래시장", slug: 'market_stall_icon', folder: 'items', nameEn: "Market stall", family: 'place' },
  { ko: "장을 보다", slug: 'market_stall_icon', folder: 'items', nameEn: "Market stall", family: 'place' },
  { ko: "전기 요금", slug: 'light_bulb', folder: 'items', nameEn: "Light bulb", family: 'place' },
  { ko: "잠을 잘 못 자다", slug: 'white_pillow', folder: 'items', nameEn: "Pillow", family: 'health' },
  { ko: "푹 쉬다", slug: 'white_pillow', folder: 'items', nameEn: "Pillow", family: 'health' },
  { ko: "피곤하다", slug: 'white_pillow', folder: 'items', nameEn: "Pillow", family: 'health' },
  { ko: "기운이 없다", slug: 'white_pillow', folder: 'items', nameEn: "Pillow", family: 'health' },
  { ko: "계약", slug: 'contract_seal', folder: 'items', nameEn: "Sealed contract", family: 'place' },
  { ko: "계약 기간", slug: 'contract_seal', folder: 'items', nameEn: "Sealed contract", family: 'place' },
  { ko: "전세", slug: 'contract_seal', folder: 'items', nameEn: "Sealed contract", family: 'place' },
  { ko: "태권도", slug: 'taekwondo_dobok', folder: 'items', nameEn: "Taekwondo uniform", family: 'people' },
  { ko: "태권도장", slug: 'taekwondo_dobok', folder: 'items', nameEn: "Taekwondo uniform", family: 'people' },
  { ko: "수도 요금", slug: 'water_faucet', folder: 'items', nameEn: "Water faucet", family: 'place' },
  { ko: "수영장", slug: 'water_faucet', folder: 'items', nameEn: "Water faucet", family: 'place' },
  { ko: "운동", slug: 'running_shoe', folder: 'items', nameEn: "Running shoe", family: 'people' },
  { ko: "운동을 하다", slug: 'running_shoe', folder: 'items', nameEn: "Running shoe", family: 'people' },
  { ko: "달리다", slug: 'running_shoe', folder: 'items', nameEn: "Running shoe", family: 'people' },
  { ko: "달리기", slug: 'running_shoe', folder: 'items', nameEn: "Running shoe", family: 'people' },
  { ko: "마라톤", slug: 'running_shoe', folder: 'items', nameEn: "Running shoe", family: 'people' },
  { ko: "건강", slug: 'running_shoe', folder: 'items', nameEn: "Running shoe", family: 'people' },
  { ko: "하루", slug: 'wall_calendar', folder: 'items', nameEn: "Calendar", family: 'abstract' },
  { ko: "매일", slug: 'wall_calendar', folder: 'items', nameEn: "Calendar", family: 'abstract' },
  { ko: "식후", slug: 'wall_calendar', folder: 'items', nameEn: "Calendar", family: 'abstract' },
  { ko: "쉬는 시간", slug: 'wall_calendar', folder: 'items', nameEn: "Calendar", family: 'abstract' },
  { ko: "방학", slug: 'wall_calendar', folder: 'items', nameEn: "Calendar", family: 'abstract' },
  { ko: "배달", slug: 'delivery_scooter', folder: 'items', nameEn: "Delivery", family: 'share' },
  { ko: "먹다", slug: 'medicine_capsule', folder: 'items', nameEn: "To take medicine", family: 'share' },
  { ko: "넣다", slug: 'eye_drops', folder: 'items', nameEn: "To put in eye drops", family: 'share' },
  { ko: "바르다", slug: 'ointment_tube', folder: 'items', nameEn: "To apply ointment", family: 'share' },
  { ko: "의원", slug: 'clinic_building', folder: 'items', nameEn: "Clinic", family: 'share' },
  { ko: "약사", slug: 'pharmacy_shop', folder: 'items', nameEn: "Pharmacist", family: 'share' },
  { ko: "얼굴에 뭐가 나다", slug: 'ointment_tube', folder: 'items', nameEn: "Breakout", family: 'share' },
  { ko: "피부과", slug: 'ointment_tube', folder: 'items', nameEn: "Dermatology", family: 'share' },
  { ko: "멀미를 하다", slug: 'medicine_capsule', folder: 'items', nameEn: "Motion sickness", family: 'share' },
  { ko: "멀미약", slug: 'medicine_capsule', folder: 'items', nameEn: "Motion-sickness medicine", family: 'share' },
  { ko: "시끄럽다", slug: 'make_noise', folder: 'items', nameEn: "Noisy", family: 'share' },
  { ko: "빈방", slug: 'be_empty', folder: 'items', nameEn: "Vacant room", family: 'share' },
  { ko: "교통이 편리하다", slug: 'subway_station', folder: 'items', nameEn: "Convenient transport", family: 'share' },
  { ko: "교통편", slug: 'subway_station', folder: 'items', nameEn: "Transport", family: 'share' },
  { ko: "월세", slug: 'price_coins', folder: 'items', nameEn: "Monthly rent", family: 'share' },
  { ko: "집세", slug: 'price_coins', folder: 'items', nameEn: "Rent", family: 'share' },
  { ko: "보증금", slug: 'price_coins', folder: 'items', nameEn: "Deposit", family: 'share' },
  { ko: "식비", slug: 'empty_plate', folder: 'items', nameEn: "Food costs", family: 'share' },
  { ko: "교통비", slug: 'subway_station', folder: 'items', nameEn: "Transport costs", family: 'share' },
  { ko: "전화 요금", slug: 'make_phone_call', folder: 'items', nameEn: "Phone bill", family: 'share' },
  { ko: "반찬", slug: 'vegetable_pile', folder: 'items', nameEn: "Side dish", family: 'share' },
  { ko: "관리비", slug: 'soap_bar', folder: 'items', nameEn: "Maintenance fee", family: 'share' },
  { ko: "현관", slug: 'studio_oneroom', folder: 'items', nameEn: "Entryway", family: 'share' },
  { ko: "낮", slug: 'sun_icon', folder: 'items', nameEn: "Sun", family: 'time' },
  { ko: "아침", slug: 'sun_icon', folder: 'items', nameEn: "Sun", family: 'time' },
  { ko: "따뜻하다", slug: 'sun_icon', folder: 'items', nameEn: "Sun", family: 'time' },
  { ko: "기사", slug: 'newspaper', folder: 'items', nameEn: "Newspaper", family: 'media' },
  { ko: "신문 기사", slug: 'newspaper', folder: 'items', nameEn: "Newspaper", family: 'media' },
  { ko: "기자", slug: 'newspaper', folder: 'items', nameEn: "Newspaper", family: 'media' },
  { ko: "영양제", slug: 'vitamin_bottle', folder: 'items', nameEn: "Vitamin bottle", family: 'health' },
  { ko: "변호사", slug: 'justice_scales', folder: 'items', nameEn: "Scales of justice", family: 'people' },
  { ko: "밤", slug: 'crescent_moon', folder: 'items', nameEn: "Moon", family: 'time' },
  { ko: "저녁", slug: 'crescent_moon', folder: 'items', nameEn: "Moon", family: 'time' },
  { ko: "세계", slug: 'desk_globe', folder: 'items', nameEn: "Globe", family: 'place' },
  { ko: "유학", slug: 'desk_globe', folder: 'items', nameEn: "Globe", family: 'place' },
  { ko: "춘천", slug: 'desk_globe', folder: 'items', nameEn: "Globe", family: 'place' },
  { ko: "지갑", slug: 'leather_wallet', folder: 'items', nameEn: "Wallet", family: 'money' },
  { ko: "생활비", slug: 'leather_wallet', folder: 'items', nameEn: "Wallet", family: 'money' },
  { ko: "돈이 들다", slug: 'leather_wallet', folder: 'items', nameEn: "Wallet", family: 'money' },
  { ko: "죽다", slug: 'lit_candle', folder: 'items', nameEn: "Candle", family: 'people' },
  { ko: "은퇴하다", slug: 'lit_candle', folder: 'items', nameEn: "Candle", family: 'people' },
  { ko: "은퇴", slug: 'lit_candle', folder: 'items', nameEn: "Candle", family: 'people' },
  { ko: "고등학교", slug: 'schoolhouse', folder: 'items', nameEn: "Schoolhouse", family: 'place' },
  { ko: "대학원", slug: 'schoolhouse', folder: 'items', nameEn: "Schoolhouse", family: 'place' },
  { ko: "중학생", slug: 'schoolhouse', folder: 'items', nameEn: "Schoolhouse", family: 'place' },
  { ko: "사랑에 빠지다", slug: 'red_heart', folder: 'items', nameEn: "Heart", family: 'people' },
  { ko: "친해지다", slug: 'red_heart', folder: 'items', nameEn: "Heart", family: 'people' },
  { ko: "기분이 좋다", slug: 'red_heart', folder: 'items', nameEn: "Heart", family: 'people' },
  { ko: "발표하다", slug: 'silver_mic', folder: 'items', nameEn: "Microphone", family: 'people' },
  { ko: "인터뷰", slug: 'silver_mic', folder: 'items', nameEn: "Microphone", family: 'people' },
  { ko: "설명하다", slug: 'silver_mic', folder: 'items', nameEn: "Microphone", family: 'people' },
  { ko: "베란다", slug: 'balcony_rail', folder: 'items', nameEn: "Balcony", family: 'place' },
  { ko: "전망이 좋다", slug: 'balcony_rail', folder: 'items', nameEn: "Balcony", family: 'place' },
  { ko: "역할극", slug: 'silver_mic', folder: 'items', nameEn: "role-play", family: 'fill' },
  { ko: "마다", slug: 'kinds_types', folder: 'items', nameEn: "every, each (N마다)", family: 'fill' },
  { ko: "씩", slug: 'kinds_types', folder: 'items', nameEn: "each, apiece (per unit)", family: 'fill' },
  { ko: "계속", slug: 'kinds_types', folder: 'items', nameEn: "continuously", family: 'fill' },
  { ko: "걱정", slug: 'ice_pack', folder: 'items', nameEn: "worry", family: 'fill' },
  { ko: "심심하다", slug: 'kinds_types', folder: 'items', nameEn: "to be bored", family: 'fill' },
  { ko: "시간이 나다", slug: 'wall_calendar', folder: 'items', nameEn: "to have free time", family: 'fill' },
  { ko: "계획을 세우다", slug: 'leather_wallet', folder: 'items', nameEn: "to make a plan", family: 'fill' },
  { ko: "자꾸", slug: 'kinds_types', folder: 'items', nameEn: "repeatedly, again and again", family: 'fill' },
  { ko: "화해하다", slug: 'kinds_types', folder: 'items', nameEn: "to make up, reconcile", family: 'fill' },
  { ko: "싸우다", slug: 'kinds_types', folder: 'items', nameEn: "to quarrel, fight", family: 'fill' },
  { ko: "가볍다", slug: 'kinds_types', folder: 'items', nameEn: "to be light", family: 'fill' },
  { ko: "어떻게 오셨어요?", slug: 'running_shoe', folder: 'items', nameEn: "What brings you here?", family: 'fill' },
  { ko: "언제부터", slug: 'wall_calendar', folder: 'items', nameEn: "since when", family: 'fill' },
  { ko: "이틀", slug: 'wall_calendar', folder: 'items', nameEn: "two days", family: 'fill' },
  { ko: "정도", slug: 'running_shoe', folder: 'items', nameEn: "about, approximately", family: 'fill' },
  { ko: "그래도", slug: 'running_shoe', folder: 'items', nameEn: "even so, still", family: 'fill' },
  { ko: "을/를 위해서", slug: 'running_shoe', folder: 'items', nameEn: "for the sake of, in order to", family: 'fill' },
  { ko: "특별히", slug: 'running_shoe', folder: 'items', nameEn: "particularly, especially", family: 'fill' },
  { ko: "스트레스가 풀리다", slug: 'ice_pack', folder: 'items', nameEn: "for stress to be relieved", family: 'fill' },
  { ko: "스트레스가 많다", slug: 'ice_pack', folder: 'items', nameEn: "to be under a lot of stress", family: 'fill' },
  { ko: "동호회", slug: 'school_backpack', folder: 'items', nameEn: "club, hobby society", family: 'fill' },
  { ko: "나가다", slug: 'go_outside', folder: 'items', nameEn: "to go out; to attend", family: 'fill' },
  { ko: "시간을 내다", slug: 'wall_calendar', folder: 'items', nameEn: "to make time", family: 'fill' },
  { ko: "고민", slug: 'ice_pack', folder: 'items', nameEn: "worry, something on one's mind", family: 'fill' },
  { ko: "조언", slug: 'silver_mic', folder: 'items', nameEn: "advice", family: 'fill' },
  { ko: "여행을 다녀오다", slug: 'desk_globe', folder: 'items', nameEn: "to go on a trip and come back", family: 'fill' },
  { ko: "무슨 일 있어요?", slug: 'running_shoe', folder: 'items', nameEn: "Is something the matter?", family: 'fill' },
  { ko: "사흘", slug: 'wall_calendar', folder: 'items', nameEn: "three days", family: 'fill' },
  { ko: "나이", slug: 'elderly', folder: 'items', nameEn: "age", family: 'fill' },
  { ko: "완주", slug: 'running_shoe', folder: 'items', nameEn: "running the full course", family: 'fill' },
  { ko: "대회", slug: 'running_shoe', folder: 'items', nameEn: "competition, meet", family: 'fill' },
  { ko: "참가하다", slug: 'school_backpack', folder: 'items', nameEn: "to take part, participate", family: 'fill' },
  { ko: "선수", slug: 'school_backpack', folder: 'items', nameEn: "athlete, competitor", family: 'fill' },
  { ko: "상을 받다", slug: 'kinds_types', folder: 'items', nameEn: "to win a prize", family: 'fill' },
  { ko: "축하하다", slug: 'birthday_cake', folder: 'items', nameEn: "to congratulate", family: 'fill' },
  { ko: "평소", slug: 'wall_calendar', folder: 'items', nameEn: "ordinary times, usually", family: 'fill' },
  { ko: "식사", slug: 'empty_plate', folder: 'items', nameEn: "a meal", family: 'fill' },
  { ko: "여러 번", slug: 'kinds_types', folder: 'items', nameEn: "several times", family: 'fill' },
  { ko: "가장", slug: 'kinds_types', folder: 'items', nameEn: "the most, -est", family: 'fill' },
  { ko: "빠르다", slug: 'running_shoe', folder: 'items', nameEn: "to be fast", family: 'fill' },
  { ko: "특별하다", slug: 'kinds_types', folder: 'items', nameEn: "to be special", family: 'fill' },
  { ko: "건강 비결", slug: 'running_shoe', folder: 'items', nameEn: "the secret of good health", family: 'fill' },
  { ko: "생활", slug: 'running_shoe', folder: 'items', nameEn: "life, living", family: 'fill' },
  { ko: "습관", slug: 'running_shoe', folder: 'items', nameEn: "habit", family: 'fill' },
  { ko: "생활 습관", slug: 'running_shoe', folder: 'items', nameEn: "lifestyle habits", family: 'fill' },
  { ko: "건강하다", slug: 'running_shoe', folder: 'items', nameEn: "to be healthy", family: 'fill' },
  { ko: "몸에 좋다", slug: 'running_shoe', folder: 'items', nameEn: "to be good for the body", family: 'fill' },
  { ko: "그러나", slug: 'running_shoe', folder: 'items', nameEn: "however", family: 'fill' },
  { ko: "바꾸다", slug: 'light_bulb', folder: 'items', nameEn: "to change", family: 'fill' },
  { ko: "중요하다", slug: 'running_shoe', folder: 'items', nameEn: "to be important", family: 'fill' },
  { ko: "웃다", slug: 'birthday_cake', folder: 'items', nameEn: "to laugh, to smile", family: 'fill' },
  { ko: "모든", slug: 'running_shoe', folder: 'items', nameEn: "all, every", family: 'fill' },
  { ko: "좋은 쪽으로 생각하다", slug: 'running_shoe', folder: 'items', nameEn: "to look on the bright side", family: 'fill' },
  { ko: "노력하다", slug: 'running_shoe', folder: 'items', nameEn: "to make an effort", family: 'fill' },
  { ko: "오래", slug: 'running_shoe', folder: 'items', nameEn: "for a long time", family: 'fill' },
  { ko: "한 번에", slug: 'running_shoe', folder: 'items', nameEn: "all at once, in one go", family: 'fill' },
  { ko: "외출하다", slug: 'go_outside', folder: 'items', nameEn: "to go out (leave the house)", family: 'fill' },
  { ko: "돌아오다", slug: 'go_outside', folder: 'items', nameEn: "to come back", family: 'fill' },
  { ko: "바로", slug: 'running_shoe', folder: 'items', nameEn: "right away", family: 'fill' },
  { ko: "예방하다", slug: 'detached_house', folder: 'items', nameEn: "to prevent", family: 'fill' },
  { ko: "꼭", slug: 'running_shoe', folder: 'items', nameEn: "without fail, be sure to", family: 'fill' },
  { ko: "하숙집", slug: 'dormitory', folder: 'items', nameEn: "boarding house (room with meals)", family: 'fill' },
  { ko: "고시원", slug: 'studio_oneroom', folder: 'items', nameEn: "gosiwon — a tiny single room", family: 'fill' },
  { ko: "1인실", slug: 'studio_oneroom', folder: 'items', nameEn: "single room (for one)", family: 'fill' },
  { ko: "방이 넓다", slug: 'detached_house', folder: 'items', nameEn: "the room is spacious", family: 'fill' },
  { ko: "방이 좁다", slug: 'detached_house', folder: 'items', nameEn: "the room is cramped", family: 'fill' },
  { ko: "방값이 싸다", slug: 'leather_wallet', folder: 'items', nameEn: "the rent is cheap", family: 'fill' },
  { ko: "새로 지었다", slug: 'kinds_types', folder: 'items', nameEn: "newly built", family: 'fill' },
  { ko: "시설이 잘되어 있다", slug: 'detached_house', folder: 'items', nameEn: "well equipped, good facilities", family: 'fill' },
  { ko: "교통이 불편하다", slug: 'subway_station', folder: 'items', nameEn: "the transport links are poor", family: 'fill' },
  { ko: "주변이 조용하다", slug: 'kinds_types', folder: 'items', nameEn: "the area around is quiet", family: 'fill' },
  { ko: "집주인이 좋다", slug: 'detached_house', folder: 'items', nameEn: "the landlord is good", family: 'fill' },
  { ko: "살기 좋다", slug: 'detached_house', folder: 'items', nameEn: "good to live in", family: 'fill' },
  { ko: "어둡다", slug: 'detached_house', folder: 'items', nameEn: "to be dark", family: 'fill' },
  { ko: "마음에 들다", slug: 'red_heart', folder: 'items', nameEn: "to like it, for it to suit you", family: 'fill' },
  { ko: "주변 환경", slug: 'kinds_types', folder: 'items', nameEn: "the surroundings, the neighbourhood", family: 'fill' },
  { ko: "크기", slug: 'kinds_types', folder: 'items', nameEn: "size", family: 'fill' },
  { ko: "매매", slug: 'leather_wallet', folder: 'items', nameEn: "buying and selling (property)", family: 'fill' },
  { ko: "이하", slug: 'contract_seal', folder: 'items', nameEn: "or less, no more than", family: 'fill' },
  { ko: "포함되다", slug: 'contract_seal', folder: 'items', nameEn: "to be included", family: 'fill' },
  { ko: "반씩", slug: 'kinds_types', folder: 'items', nameEn: "half each", family: 'fill' },
  { ko: "나오다", slug: 'kinds_types', folder: 'items', nameEn: "to come to (of a bill)", family: 'fill' },
  { ko: "중개인", slug: 'estate_broker', folder: 'items', nameEn: "agent, broker", family: 'fill' },
  { ko: "조건", slug: 'contract_seal', folder: 'items', nameEn: "conditions, terms", family: 'fill' },
  { ko: "위치", slug: 'kinds_types', folder: 'items', nameEn: "location", family: 'fill' },
  { ko: "기타", slug: 'kinds_types', folder: 'items', nameEn: "other, anything else", family: 'fill' },
  { ko: "구하다", slug: 'kinds_types', folder: 'items', nameEn: "to look for, to find (a place)", family: 'fill' },
  { ko: "알아보다", slug: 'kinds_types', folder: 'items', nameEn: "to look into, to ask around", family: 'fill' },
  { ko: "결정하다", slug: 'kinds_types', folder: 'items', nameEn: "to decide", family: 'fill' },
  { ko: "구경하다", slug: 'kinds_types', folder: 'items', nameEn: "to look round, to view", family: 'fill' },
  { ko: "광고", slug: 'newspaper', folder: 'items', nameEn: "advertisement", family: 'fill' },
  { ko: "문의하다", slug: 'kinds_types', folder: 'items', nameEn: "to enquire", family: 'fill' },
  { ko: "거리", slug: 'kinds_types', folder: 'items', nameEn: "distance; a walk away", family: 'fill' },
  { ko: "떠들다", slug: 'kinds_types', folder: 'items', nameEn: "to make a racket", family: 'fill' },
  { ko: "공기", slug: 'balcony_rail', folder: 'items', nameEn: "air", family: 'fill' },
  { ko: "마침", slug: 'kinds_types', folder: 'items', nameEn: "as it happens, just then", family: 'fill' },
  { ko: "회사를 옮기다", slug: 'kinds_types', folder: 'items', nameEn: "to move to another company", family: 'fill' },
  { ko: "편하다", slug: 'kinds_types', folder: 'items', nameEn: "to be comfortable, easy", family: 'fill' },
  { ko: "불편하다", slug: 'ice_pack', folder: 'items', nameEn: "to be inconvenient", family: 'fill' },
  { ko: "힘들다", slug: 'ice_pack', folder: 'items', nameEn: "to be hard going", family: 'fill' },
  { ko: "연락하다", slug: 'make_phone_call', folder: 'items', nameEn: "to get in touch", family: 'fill' },
  { ko: "그렇지 않아도", slug: 'kinds_types', folder: 'items', nameEn: "as it happens, I was going to anyway", family: 'fill' },
  { ko: "높은 곳", slug: 'kinds_types', folder: 'items', nameEn: "a high spot, up high", family: 'fill' },
  { ko: "길이 막히다", slug: 'subway_station', folder: 'items', nameEn: "for the road to be jammed", family: 'fill' },
  { ko: "대부분", slug: 'desk_globe', folder: 'items', nameEn: "mostly, most of them", family: 'fill' },
  { ko: "바뀌다", slug: 'light_bulb', folder: 'items', nameEn: "to be turned into, to change", family: 'fill' },
  { ko: "생활하다", slug: 'running_shoe', folder: 'items', nameEn: "to live, to get by day to day", family: 'fill' },
  { ko: "아주머니", slug: 'elderly', folder: 'items', nameEn: "ma’am — an older woman", family: 'fill' },
  { ko: "가족처럼", slug: 'elderly', folder: 'items', nameEn: "like family", family: 'fill' },
  { ko: "소개하다", slug: 'kinds_types', folder: 'items', nameEn: "to introduce, to put on to", family: 'fill' },
  { ko: "나중에", slug: 'wall_calendar', folder: 'items', nameEn: "later on", family: 'fill' },
  { ko: "좋은 점", slug: 'kinds_types', folder: 'items', nameEn: "the good points", family: 'fill' },
  { ko: "나쁜 점", slug: 'kinds_types', folder: 'items', nameEn: "the bad points", family: 'fill' },
  { ko: "룸메이트", slug: 'school_backpack', folder: 'items', nameEn: "roommate", family: 'fill' },
  { ko: "규칙", slug: 'dorm_rules', folder: 'items', nameEn: "a rule", family: 'fill' },
  { ko: "궁금하다", slug: 'detached_house', folder: 'items', nameEn: "to wonder, to be curious", family: 'fill' },
  { ko: "혹시", slug: 'detached_house', folder: 'items', nameEn: "by any chance", family: 'fill' },
  { ko: "잘됐다", slug: 'birthday_cake', folder: 'items', nameEn: "that works out well", family: 'fill' },
  { ko: "바람이 통하다", slug: 'balcony_rail', folder: 'items', nameEn: "to be well ventilated", family: 'fill' },
  { ko: "느끼다", slug: 'kinds_types', folder: 'items', nameEn: "to feel", family: 'fill' },
  { ko: "시원하다", slug: 'balcony_rail', folder: 'items', nameEn: "to be cool, refreshing", family: 'fill' },
  { ko: "놀러 가다", slug: 'go_outside', folder: 'items', nameEn: "to go round to visit", family: 'fill' },
  { ko: "어울리다", slug: 'kinds_types', folder: 'items', nameEn: "to suit, to go well with", family: 'fill' },
  { ko: "인생", slug: 'red_heart', folder: 'items', nameEn: "a life, a lifetime", family: 'fill' },
  { ko: "고생하다", slug: 'red_heart', folder: 'items', nameEn: "to go through a hard time", family: 'fill' },
  { ko: "꿈", slug: 'red_heart', folder: 'items', nameEn: "a dream, what one wants to become", family: 'fill' },
  { ko: "봉사 활동", slug: 'red_heart', folder: 'items', nameEn: "volunteer work", family: 'fill' },
  { ko: "늘다", slug: 'light_bulb', folder: 'items', nameEn: "to increase", family: 'fill' },
  { ko: "줄다", slug: 'light_bulb', folder: 'items', nameEn: "to decrease", family: 'fill' },
  { ko: "오르다", slug: 'light_bulb', folder: 'items', nameEn: "to go up", family: 'fill' },
  { ko: "내리다", slug: 'light_bulb', folder: 'items', nameEn: "to go down", family: 'fill' },
  { ko: "생기다", slug: 'light_bulb', folder: 'items', nameEn: "to be formed, to come into being", family: 'fill' },
  { ko: "발전하다", slug: 'light_bulb', folder: 'items', nameEn: "to develop", family: 'fill' },
  { ko: "인구", slug: 'desk_globe', folder: 'items', nameEn: "population", family: 'fill' },
  { ko: "물건값", slug: 'leather_wallet', folder: 'items', nameEn: "the price of goods", family: 'fill' },
  { ko: "시골", slug: 'hanok_house', folder: 'items', nameEn: "the countryside", family: 'fill' },
  { ko: "수", slug: 'desk_globe', folder: 'items', nameEn: "a number, a count", family: 'fill' },
  { ko: "과일값", slug: 'leather_wallet', folder: 'items', nameEn: "the price of fruit", family: 'fill' },
  { ko: "점점", slug: 'light_bulb', folder: 'items', nameEn: "little by little", family: 'fill' },
  { ko: "달라지다", slug: 'light_bulb', folder: 'items', nameEn: "to become different", family: 'fill' },
  { ko: "옛날", slug: 'light_bulb', folder: 'items', nameEn: "the old days", family: 'fill' },
  { ko: "A-아지다/어지다", slug: 'kinds_types', folder: 'items', nameEn: "to get / to become — an adjective turning into a change", family: 'fill' },
  { ko: "V-게 되다", slug: 'kinds_types', folder: 'items', nameEn: "to end up doing it, to come to do it", family: 'fill' },
  { ko: "익숙하다", slug: 'kinds_types', folder: 'items', nameEn: "to be accustomed to it", family: 'fill' },
  { ko: "이제", slug: 'wall_calendar', folder: 'items', nameEn: "now, by now", family: 'fill' },
  { ko: "알게 되다", slug: 'kinds_types', folder: 'items', nameEn: "to come to know", family: 'fill' },
  { ko: "건강해지다", slug: 'running_shoe', folder: 'items', nameEn: "to get healthier", family: 'fill' },
  { ko: "오래간만이다", slug: 'kinds_types', folder: 'items', nameEn: "it's been a long time", family: 'fill' },
  { ko: "별일 없다", slug: 'kinds_types', folder: 'items', nameEn: "to have nothing much going on", family: 'fill' },
  { ko: "그동안", slug: 'wall_calendar', folder: 'items', nameEn: "in the meantime, since we last met", family: 'fill' },
  { ko: "걱정하다", slug: 'ice_pack', folder: 'items', nameEn: "to worry", family: 'fill' },
  { ko: "곧", slug: 'wall_calendar', folder: 'items', nameEn: "soon", family: 'fill' },
  { ko: "안부", slug: 'kinds_types', folder: 'items', nameEn: "how someone is keeping", family: 'fill' },
  { ko: "안부를 묻다", slug: 'kinds_types', folder: 'items', nameEn: "to ask after someone", family: 'fill' },
  { ko: "근황", slug: 'kinds_types', folder: 'items', nameEn: "what someone has been up to lately", family: 'fill' },
  { ko: "얼마나", slug: 'kinds_types', folder: 'items', nameEn: "how long, how much", family: 'fill' },
  { ko: "처음에는", slug: 'kinds_types', folder: 'items', nameEn: "at first", family: 'fill' },
  { ko: "외국", slug: 'desk_globe', folder: 'items', nameEn: "a foreign country", family: 'fill' },
  { ko: "V-기 전에", slug: 'kinds_types', folder: 'items', nameEn: "before doing it", family: 'fill' },
  { ko: "V-(으)ㄴ 후에", slug: 'kinds_types', folder: 'items', nameEn: "after doing it", family: 'fill' },
  { ko: "출발하다", slug: 'kinds_types', folder: 'items', nameEn: "to set off", family: 'fill' },
  { ko: "준비 운동", slug: 'running_shoe', folder: 'items', nameEn: "a warm-up", family: 'fill' },
  { ko: "다니다", slug: 'kinds_types', folder: 'items', nameEn: "to attend, to go regularly", family: 'fill' },
  { ko: "먼저", slug: 'kinds_types', folder: 'items', nameEn: "first, before anything else", family: 'fill' },
  { ko: "숙제", slug: 'homework_notebook', folder: 'items', nameEn: "homework", family: 'fill' },
  { ko: "놀다", slug: 'kinds_types', folder: 'items', nameEn: "to hang out, to play", family: 'fill' },
  { ko: "마치다", slug: 'kinds_types', folder: 'items', nameEn: "to finish something", family: 'fill' },
  { ko: "-고 나서", slug: 'kinds_types', folder: 'items', nameEn: "and then, once that is done", family: 'fill' },
  { ko: "-기로 하다", slug: 'kinds_types', folder: 'items', nameEn: "to arrange to, to decide to", family: 'fill' },
  { ko: "-려고 하다", slug: 'kinds_types', folder: 'items', nameEn: "to be planning to", family: 'fill' },
  { ko: "곳", slug: 'kinds_types', folder: 'items', nameEn: "a place", family: 'fill' },
  { ko: "프랑스", slug: 'desk_globe', folder: 'items', nameEn: "France", family: 'fill' },
  { ko: "파리", slug: 'desk_globe', folder: 'items', nameEn: "Paris", family: 'fill' },
  { ko: "거의", slug: 'kinds_types', folder: 'items', nameEn: "almost, hardly any", family: 'fill' },
  { ko: "예전에", slug: 'kinds_types', folder: 'items', nameEn: "in the old days", family: 'fill' },
  { ko: "근처", slug: 'kinds_types', folder: 'items', nameEn: "nearby", family: 'fill' },
  { ko: "호선", slug: 'kinds_types', folder: 'items', nameEn: "line number — 9호선 is Line 9", family: 'fill' },
  { ko: "훨씬", slug: 'kinds_types', folder: 'items', nameEn: "far more", family: 'fill' },
  { ko: "편리하다", slug: 'kinds_types', folder: 'items', nameEn: "to be convenient", family: 'fill' },
  { ko: "외국인", slug: 'desk_globe', folder: 'items', nameEn: "a foreigner", family: 'fill' },
  { ko: "어디에서나", slug: 'kinds_types', folder: 'items', nameEn: "anywhere at all", family: 'fill' },
  { ko: "앞으로", slug: 'kinds_types', folder: 'items', nameEn: "from now on", family: 'fill' },
  { ko: "기대가 되다", slug: 'kinds_types', folder: 'items', nameEn: "to be something to look forward to", family: 'fill' },
  { ko: "N에 대한", slug: 'kinds_types', folder: 'items', nameEn: "about N, concerning N", family: 'fill' },
  { ko: "N(이)나", slug: 'kinds_types', folder: 'items', nameEn: "N or something like it", family: 'fill' },
  { ko: "강남", slug: 'desk_globe', folder: 'items', nameEn: "Gangnam, south of the river", family: 'fill' },
  { ko: "한강", slug: 'desk_globe', folder: 'items', nameEn: "the Han River", family: 'fill' },
  { ko: "1970년대", slug: 'light_bulb', folder: 'items', nameEn: "the 1970s — N년대 is the decade", family: 'fill' },
  { ko: "수도", slug: 'desk_globe', folder: 'items', nameEn: "a capital city", family: 'fill' },
  { ko: "과거", slug: 'light_bulb', folder: 'items', nameEn: "the past", family: 'fill' },
  { ko: "명", slug: 'light_bulb', folder: 'items', nameEn: "the counter for people", family: 'fill' },
  { ko: "그래프", slug: 'line_graph', folder: 'items', nameEn: "a graph", family: 'fill' },
  { ko: "초등학교", slug: 'schoolhouse', folder: 'items', nameEn: "elementary school", family: 'fill' },
  { ko: "행복", slug: 'red_heart', folder: 'items', nameEn: "happiness", family: 'fill' },
  { ko: "불행", slug: 'red_heart', folder: 'items', nameEn: "unhappiness", family: 'fill' },
  { ko: "점을 찍다", slug: 'red_heart', folder: 'items', nameEn: "to mark a dot", family: 'fill' },
  { ko: "연결하다", slug: 'red_heart', folder: 'items', nameEn: "to join up, to connect", family: 'fill' },
  { ko: "부모님", slug: 'red_heart', folder: 'items', nameEn: "one’s parents", family: 'fill' },
  { ko: "그때", slug: 'red_heart', folder: 'items', nameEn: "at that time", family: 'fill' },
  { ko: "그 후로", slug: 'red_heart', folder: 'items', nameEn: "ever since then", family: 'fill' },
  { ko: "아프다", slug: 'medicine_bottle', folder: 'items', nameEn: "to be ill", family: 'fill' },
  { ko: "기다리다", slug: 'red_heart', folder: 'items', nameEn: "to wait for", family: 'fill' },
  { ko: "탈락", slug: 'kinds_types', folder: 'items', nameEn: "dropping — a sound that stops being pronounced", family: 'fill' },
  { ko: "모음", slug: 'kinds_types', folder: 'items', nameEn: "a vowel", family: 'fill' },
  { ko: "싫다", slug: 'kinds_types', folder: 'items', nameEn: "to dislike", family: 'fill' },
  { ko: "끓다", slug: 'kinds_types', folder: 'items', nameEn: "to boil", family: 'fill' },
  { ko: "극장", slug: 'cinema_house', folder: 'items', nameEn: "a cinema", family: 'fill' },
  { ko: "기분", slug: 'red_heart', folder: 'items', nameEn: "a mood, how one feels", family: 'fill' },
  { ko: "낳다", slug: 'kinds_types', folder: 'items', nameEn: "to give birth", family: 'fill' },
  { ko: "괜찮아지다", slug: 'kinds_types', folder: 'items', nameEn: "to get better, to come right", family: 'fill' },
  { ko: "썰렁하다", slug: 'ice_pack', folder: 'items', nameEn: "to be deserted, to have no custom; (of air) chilly", family: 'fill' },
  { ko: "모색", slug: 'running_shoe', folder: 'items', nameEn: "a search for a way forward", family: 'fill' },
  { ko: "여러 곳", slug: 'public_etiquette', folder: 'items', nameEn: "several places", family: 'fill' },
  { ko: "찾다", slug: 'go_outside', folder: 'items', nameEn: "to visit a place; to look for", family: 'fill' },
  { ko: "직접", slug: 'exit_door', folder: 'items', nameEn: "in person, directly", family: 'fill' },
  { ko: "추워지다", slug: 'ice_pack', folder: 'items', nameEn: "to turn cold", family: 'fill' },
  { ko: "손님", slug: 'elderly', folder: 'items', nameEn: "a customer", family: 'fill' },
  { ko: "통하다", slug: 'exit_door', folder: 'items', nameEn: "to go through, to be by way of", family: 'fill' },
  { ko: "경기", slug: 'leather_wallet', folder: 'items', nameEn: "business conditions, how trade is going", family: 'fill' },
  { ko: "회복", slug: 'leather_wallet', folder: 'items', nameEn: "a recovery", family: 'fill' },
  { ko: "노력", slug: 'running_shoe', folder: 'items', nameEn: "effort", family: 'fill' },
  { ko: "상품", slug: 'leather_wallet', folder: 'items', nameEn: "goods, a product", family: 'fill' },
  { ko: "구매하다", slug: 'leather_wallet', folder: 'items', nameEn: "to buy, to purchase", family: 'fill' },
  { ko: "원하다", slug: 'public_etiquette', folder: 'items', nameEn: "to want", family: 'fill' },
  { ko: "많아지다", slug: 'public_etiquette', folder: 'items', nameEn: "to grow in number", family: 'fill' },
  { ko: "제목", slug: 'newspaper', folder: 'items', nameEn: "a headline, a title", family: 'fill' },
  { ko: "눈으로 먹다", slug: 'empty_plate', folder: 'items', nameEn: "to eat with the eyes — to enjoy food by looking at it", family: 'fill' },
  { ko: "귀로 맛보다", slug: 'empty_plate', folder: 'items', nameEn: "to taste with the ears — to enjoy food through its sounds", family: 'fill' },
  { ko: "맛보다", slug: 'empty_plate', folder: 'items', nameEn: "to taste", family: 'fill' },
  { ko: "음식", slug: 'empty_plate', folder: 'items', nameEn: "food", family: 'fill' },
  { ko: "모양", slug: 'kinds_types', folder: 'items', nameEn: "the shape of a thing", family: 'fill' },
  { ko: "색깔", slug: 'kinds_types', folder: 'items', nameEn: "colour", family: 'fill' },
  { ko: "시대", slug: 'newspaper', folder: 'items', nameEn: "an age, an era", family: 'fill' },
  { ko: "천국", slug: 'newspaper', folder: 'items', nameEn: "heaven — in a headline, \"awash with\"", family: 'fill' },
  { ko: "요리 프로그램", slug: 'newspaper', folder: 'items', nameEn: "a cooking programme", family: 'fill' },
  { ko: "텔레비전 프로그램", slug: 'newspaper', folder: 'items', nameEn: "a television programme", family: 'fill' },
  { ko: "실제", slug: 'newspaper', folder: 'items', nameEn: "the real thing, actual", family: 'fill' },
  { ko: "보여주다", slug: 'newspaper', folder: 'items', nameEn: "to show", family: 'fill' },
  { ko: "즐기다", slug: 'public_etiquette', folder: 'items', nameEn: "to enjoy", family: 'fill' },
  { ko: "관련되다", slug: 'public_etiquette', folder: 'items', nameEn: "to be related to", family: 'fill' },
  { ko: "요즘", slug: 'public_etiquette', folder: 'items', nameEn: "these days", family: 'fill' },
  { ko: "중요해지다", slug: 'running_shoe', folder: 'items', nameEn: "to become important", family: 'fill' },
  { ko: "색조 화장품", slug: 'kinds_types', folder: 'items', nameEn: "colour cosmetics — makeup, as against skincare", family: 'fill' },
  { ko: "화장품", slug: 'kinds_types', folder: 'items', nameEn: "cosmetics", family: 'fill' },
  { ko: "화장을 하다", slug: 'kinds_types', folder: 'items', nameEn: "to wear makeup", family: 'fill' },
  { ko: "외모", slug: 'kinds_types', folder: 'items', nameEn: "a person's looks", family: 'fill' },
  { ko: "가꾸다", slug: 'detached_house', folder: 'items', nameEn: "to tend, to groom — used of looks and of gardens alike", family: 'fill' },
  { ko: "불티", slug: 'newspaper', folder: 'items', nameEn: "a spark — in a headline, short for 불티나다, to sell out fast", family: 'fill' },
  { ko: "관리", slug: 'public_etiquette', folder: 'items', nameEn: "looking after something; also being in charge of it", family: 'fill' },
  { ko: "늘어나다", slug: 'light_bulb', folder: 'items', nameEn: "to grow in number", family: 'fill' },
  { ko: "필요가 있다", slug: 'public_etiquette', folder: 'items', nameEn: "there is a need to", family: 'fill' },
  { ko: "주로", slug: 'public_etiquette', folder: 'items', nameEn: "mainly", family: 'fill' },
  { ko: "담당하다", slug: 'public_etiquette', folder: 'items', nameEn: "to be in charge of, to handle", family: 'fill' },
  { ko: "사회적 지위", slug: 'public_etiquette', folder: 'items', nameEn: "social standing", family: 'fill' },
  { ko: "관심", slug: 'public_etiquette', folder: 'items', nameEn: "interest, attention", family: 'fill' },
  { ko: "피서객", slug: 'kinds_types', folder: 'items', nameEn: "a holidaymaker escaping the heat", family: 'fill' },
  { ko: "피서지", slug: 'kinds_types', folder: 'items', nameEn: "a place people go to escape the heat", family: 'fill' },
  { ko: "더위", slug: 'kinds_types', folder: 'items', nameEn: "the heat", family: 'fill' },
  { ko: "쓰레기", slug: 'trash_bag', folder: 'items', nameEn: "rubbish", family: 'fill' },
  { ko: "치우다", slug: 'trash_bag', folder: 'items', nameEn: "to clear away", family: 'fill' },
  { ko: "양", slug: 'kinds_types', folder: 'items', nameEn: "a quantity, an amount", family: 'fill' },
  { ko: "전쟁", slug: 'newspaper', folder: 'items', nameEn: "a war", family: 'fill' },
  { ko: "N와의 전쟁", slug: 'newspaper', folder: 'items', nameEn: "a war with N — what a headline calls a problem it cannot sol", family: 'fill' },
  { ko: "심각하다", slug: 'public_etiquette', folder: 'items', nameEn: "to be serious", family: 'fill' },
  { ko: "애쓰다", slug: 'public_etiquette', folder: 'items', nameEn: "to struggle, to take pains", family: 'fill' },
  { ko: "-기 위해", slug: 'kinds_types', folder: 'items', nameEn: "in order to", family: 'fill' },
  { ko: "-(으)로 인해", slug: 'kinds_types', folder: 'items', nameEn: "owing to, because of", family: 'fill' },
  { ko: "여러 가지로", slug: 'public_etiquette', folder: 'items', nameEn: "in various ways", family: 'fill' },
  { ko: "불편", slug: 'ice_pack', folder: 'items', nameEn: "inconvenience", family: 'fill' },
  { ko: "겪다", slug: 'public_etiquette', folder: 'items', nameEn: "to go through, to suffer", family: 'fill' },
  { ko: "저축률", slug: 'leather_wallet', folder: 'items', nameEn: "the savings rate", family: 'fill' },
  { ko: "저축", slug: 'leather_wallet', folder: 'items', nameEn: "saving, savings", family: 'fill' },
  { ko: "바닥", slug: 'leather_wallet', folder: 'items', nameEn: "the bottom — of a figure, rock bottom", family: 'fill' },
  { ko: "떨어지다", slug: 'leather_wallet', folder: 'items', nameEn: "to fall", family: 'fill' },
  { ko: "올라가다", slug: 'leather_wallet', folder: 'items', nameEn: "to climb back up", family: 'fill' },
  { ko: "낮다", slug: 'kinds_types', folder: 'items', nameEn: "to be low", family: 'fill' },
  { ko: "젊은층", slug: 'public_etiquette', folder: 'items', nameEn: "the young, as an age group", family: 'fill' },
  { ko: "젊다", slug: 'public_etiquette', folder: 'items', nameEn: "to be young", family: 'fill' },
  { ko: "무관심", slug: 'public_etiquette', folder: 'items', nameEn: "indifference", family: 'fill' },
  { ko: "걸리다", slug: 'public_etiquette', folder: 'items', nameEn: "to take (an amount of time)", family: 'fill' },
  { ko: "나타나다", slug: 'public_etiquette', folder: 'items', nameEn: "to come out, to show up — of a figure or a result", family: 'fill' },
  { ko: "N 만에", slug: 'kinds_types', folder: 'items', nameEn: "for the first time in N — measured from the last time it hap", family: 'fill' },
  { ko: "N 동안", slug: 'wall_calendar', folder: 'items', nameEn: "throughout N, for the whole of N", family: 'fill' },
  { ko: "N을/를 비롯해서", slug: 'kinds_types', folder: 'items', nameEn: "including N, and N first among them", family: 'fill' },
  { ko: "여름철", slug: 'kinds_types', folder: 'items', nameEn: "the summer months", family: 'fill' },
  { ko: "여름", slug: 'kinds_types', folder: 'items', nameEn: "summer", family: 'fill' },
  { ko: "보관", slug: 'fridge', folder: 'items', nameEn: "storage, keeping", family: 'fill' },
  { ko: "보관하다", slug: 'fridge', folder: 'items', nameEn: "to store, to keep", family: 'fill' },
  { ko: "냉장고", slug: 'fridge', folder: 'items', nameEn: "a fridge", family: 'fill' },
  { ko: "냉장고 안", slug: 'fridge', folder: 'items', nameEn: "inside the fridge", family: 'fill' },
  { ko: "믿다", slug: 'public_etiquette', folder: 'items', nameEn: "to trust, to rely on", family: 'fill' },
  { ko: "낭패", slug: 'public_etiquette', folder: 'items', nameEn: "a fiasco — a plan that lets you down at the worst moment", family: 'fill' },
  { ko: "안심하다", slug: 'public_etiquette', folder: 'items', nameEn: "to be at ease about something", family: 'fill' },
  { ko: "마련하다", slug: 'public_etiquette', folder: 'items', nameEn: "to get hold of, to arrange for", family: 'fill' },
  { ko: "좋지 않다", slug: 'public_etiquette', folder: 'items', nameEn: "is not a good idea", family: 'fill' },
  { ko: "N만", slug: 'kinds_types', folder: 'items', nameEn: "N only, N and nothing besides", family: 'fill' },
  { ko: "-아/어서는", slug: 'kinds_types', folder: 'items', nameEn: "if you go on doing it, and what follows is bad — 믿어서는, if yo", family: 'fill' },
  { ko: "-던", slug: 'kinds_types', folder: 'items', nameEn: "the one you were in the middle of", family: 'fill' },
  { ko: "-아/어야 하다", slug: 'kinds_types', folder: 'items', nameEn: "must, have to", family: 'fill' },
  { ko: "-(으)ㄹ 수 없다", slug: 'desk_globe', folder: 'items', nameEn: "cannot", family: 'fill' },
  { ko: "-(으)려면", slug: 'kinds_types', folder: 'items', nameEn: "if you intend to", family: 'fill' },
  { ko: "정부", slug: 'kinds_types', folder: 'items', nameEn: "the government", family: 'fill' },
  { ko: "정책", slug: 'kinds_types', folder: 'items', nameEn: "a policy", family: 'fill' },
  { ko: "부동산 정책", slug: 'kinds_types', folder: 'items', nameEn: "real-estate policy", family: 'fill' },
  { ko: "시민", slug: 'kinds_types', folder: 'items', nameEn: "a citizen", family: 'fill' },
  { ko: "평가하다", slug: 'kinds_types', folder: 'items', nameEn: "to judge, to rate", family: 'fill' },
  { ko: "집값", slug: 'leather_wallet', folder: 'items', nameEn: "house prices", family: 'fill' },
  { ko: "집값 잡기", slug: 'leather_wallet', folder: 'items', nameEn: "reining house prices back in", family: 'fill' },
  { ko: "서민", slug: 'leather_wallet', folder: 'items', nameEn: "ordinary working people", family: 'fill' },
  { ko: "서민 경제", slug: 'leather_wallet', folder: 'items', nameEn: "the household economy of ordinary people", family: 'fill' },
  { ko: "경제", slug: 'leather_wallet', folder: 'items', nameEn: "an economy", family: 'fill' },
  { ko: "물가", slug: 'leather_wallet', folder: 'items', nameEn: "the cost of living", family: 'fill' },
  { ko: "악영향", slug: 'leather_wallet', folder: 'items', nameEn: "a harmful effect", family: 'fill' },
  { ko: "영향을 미치다", slug: 'leather_wallet', folder: 'items', nameEn: "to have an effect on", family: 'fill' },
  { ko: "찬물", slug: 'newspaper', folder: 'items', nameEn: "cold water", family: 'fill' },
  { ko: "찬물을 끼얹다", slug: 'newspaper', folder: 'items', nameEn: "to pour cold water on it — to spoil something that was going", family: 'fill' },
  { ko: "잡다", slug: 'public_etiquette', folder: 'items', nameEn: "to catch; to get something under control", family: 'fill' },
  { ko: "냉정하다", slug: 'public_etiquette', folder: 'items', nameEn: "to be cool-headed, unsentimental", family: 'fill' },
  { ko: "마음", slug: 'red_heart', folder: 'items', nameEn: "the heart, how one feels", family: 'fill' },
  { ko: "아주", slug: 'public_etiquette', folder: 'items', nameEn: "very", family: 'fill' },
  { ko: "많이", slug: 'public_etiquette', folder: 'items', nameEn: "a lot", family: 'fill' },
  { ko: "-는 중", slug: 'kinds_types', folder: 'items', nameEn: "in the middle of doing it", family: 'fill' },
  { ko: "N 때문에", slug: 'kinds_types', folder: 'items', nameEn: "because of N", family: 'fill' },
  { ko: "-게 하다", slug: 'kinds_types', folder: 'items', nameEn: "to make something turn out that way", family: 'fill' },
  { ko: "-기", slug: 'newspaper', folder: 'items', nameEn: "the -ing form, turning a verb into something a headline can ", family: 'fill' },
  { ko: "개", slug: 'farm_dog', folder: 'items', nameEn: "a dog", family: 'fill' },
  { ko: "반려견", slug: 'farm_dog', folder: 'items', nameEn: "a pet dog — the word a paper uses, not 개", family: 'fill' },
  { ko: "주인", slug: 'kinds_types', folder: 'items', nameEn: "an owner", family: 'fill' },
  { ko: "키우다", slug: 'kinds_types', folder: 'items', nameEn: "to keep, to raise an animal", family: 'fill' },
  { ko: "물다", slug: 'kinds_types', folder: 'items', nameEn: "to bite", family: 'fill' },
  { ko: "물리다", slug: 'kinds_types', folder: 'items', nameEn: "to get bitten — the passive of 물다", family: 'fill' },
  { ko: "특성", slug: 'kinds_types', folder: 'items', nameEn: "a characteristic, what something is like by nature", family: 'fill' },
  { ko: "착각", slug: 'public_etiquette', folder: 'items', nameEn: "a thing people are sure of and wrong about", family: 'fill' },
  { ko: "흔하다", slug: 'public_etiquette', folder: 'items', nameEn: "to be common", family: 'fill' },
  { ko: "확신하다", slug: 'public_etiquette', folder: 'items', nameEn: "to be certain of it", family: 'fill' },
  { ko: "잘못되다", slug: 'public_etiquette', folder: 'items', nameEn: "to be mistaken, to be wrong", family: 'fill' },
  { ko: "자신", slug: 'public_etiquette', folder: 'items', nameEn: "oneself, one’s own", family: 'fill' },
  { ko: "우리", slug: 'public_etiquette', folder: 'items', nameEn: "our", family: 'fill' },
  { ko: "사람", slug: 'public_etiquette', folder: 'items', nameEn: "a person", family: 'fill' },
  { ko: "한번", slug: 'public_etiquette', folder: 'items', nameEn: "once, one time", family: 'fill' },
  { ko: "다시", slug: 'public_etiquette', folder: 'items', nameEn: "again", family: 'fill' },
  { ko: "안 + V", slug: 'kinds_types', folder: 'items', nameEn: "the short negative — 안 물어요 = doesn’t bite, said out loud", family: 'fill' },
  { ko: "-지 않다", slug: 'light_bulb', folder: 'items', nameEn: "the long negative, the one papers write — 오르지 않고, 물지 않는다", family: 'fill' },
  { ko: "-다고 하다", slug: 'kinds_types', folder: 'items', nameEn: "to say that — and with 확신하다, to be sure that", family: 'fill' },
  { ko: "-기 전에", slug: 'kinds_types', folder: 'items', nameEn: "before doing it — 키우기 전에, before you get one", family: 'fill' },
  { ko: "N에 대해서", slug: 'kinds_types', folder: 'items', nameEn: "about N", family: 'fill' },
  { ko: "-(으)ㄴ 적이 있다", slug: 'kinds_types', folder: 'items', nameEn: "to have ever done it", family: 'fill' },
  { ko: "-(으)ㄹ 수 있다", slug: 'desk_globe', folder: 'items', nameEn: "can, might", family: 'fill' },
  { ko: "바나나", slug: 'farm_apple', folder: 'items', nameEn: "a banana", family: 'fill' },
  { ko: "꿀잠", slug: 'crescent_moon', folder: 'items', nameEn: "honey sleep — a deep, sweet night. No honey involved.", family: 'fill' },
  { ko: "잠", slug: 'running_shoe', folder: 'items', nameEn: "sleep", family: 'fill' },
  { ko: "자다", slug: 'running_shoe', folder: 'items', nameEn: "to sleep", family: 'fill' },
  { ko: "숙면", slug: 'running_shoe', folder: 'items', nameEn: "sound sleep — the clinical word for the same thing", family: 'fill' },
  { ko: "푹", slug: 'running_shoe', folder: 'items', nameEn: "soundly, right through", family: 'fill' },
  { ko: "불안감", slug: 'running_shoe', folder: 'items', nameEn: "anxiety, a feeling of unease", family: 'fill' },
  { ko: "효과", slug: 'running_shoe', folder: 'items', nameEn: "an effect", family: 'fill' },
  { ko: "도움이 되다", slug: 'running_shoe', folder: 'items', nameEn: "to be a help", family: 'fill' },
  { ko: "없애다", slug: 'running_shoe', folder: 'items', nameEn: "to get rid of it", family: 'fill' },
  { ko: "속", slug: 'running_shoe', folder: 'items', nameEn: "the stomach, the insides", family: 'fill' },
  { ko: "사르르", slug: 'newspaper', folder: 'items', nameEn: "the word for melting quietly away — a headline quotes it and", family: 'fill' },
  { ko: "함께", slug: 'public_etiquette', folder: 'items', nameEn: "together with", family: 'fill' },
  { ko: "-게 해 주다", slug: 'kinds_types', folder: 'items', nameEn: "to let someone do it, to make it possible", family: 'fill' },
  { ko: "-(으)ㄹ뿐더러", slug: 'kinds_types', folder: 'items', nameEn: "not only that, but also — the written form of stacking with ", family: 'fill' },
  { ko: "-아/어야", slug: 'kinds_types', folder: 'items', nameEn: "only if you — a condition, not a recommendation", family: 'fill' },
  { ko: "-(으)ㄹ 때", slug: 'kinds_types', folder: 'items', nameEn: "when you do it", family: 'fill' },
  { ko: "-는 게 좋다", slug: 'kinds_types', folder: 'items', nameEn: "it is a good idea to", family: 'fill' },
  { ko: "N도", slug: 'kinds_types', folder: 'items', nameEn: "N as well, on top of what was already said", family: 'fill' },
  { ko: "서점", slug: 'hardcover_book', folder: 'items', nameEn: "a bookshop", family: 'fill' },
  { ko: "서점가", slug: 'hardcover_book', folder: 'items', nameEn: "the book trade — 가 as in 대학가, a whole scene rather than one ", family: 'fill' },
  { ko: "책", slug: 'hardcover_book', folder: 'items', nameEn: "a book", family: 'fill' },
  { ko: "열차", slug: 'subway_station', folder: 'items', nameEn: "a train", family: 'fill' },
  { ko: "행복 열차", slug: 'subway_station', folder: 'items', nameEn: "'Happiness Train' — the name of the book, which is why it is", family: 'fill' },
  { ko: "읽다", slug: 'hardcover_book', folder: 'items', nameEn: "to read", family: 'fill' },
  { ko: "큰 인기를 얻다", slug: 'kinds_types', folder: 'items', nameEn: "to be enjoying great popularity — 인기 is popularity, 얻다 to ob", family: 'fill' },
  { ko: "10만 부나", slug: 'leather_wallet', folder: 'items', nameEn: "as many as a hundred thousand copies — 부 counts books, and 나", family: 'fill' },
  { ko: "팔리다", slug: 'leather_wallet', folder: 'items', nameEn: "to sell, to be sold", family: 'fill' },
  { ko: "판매되다", slug: 'leather_wallet', folder: 'items', nameEn: "to be on sale — the formal word for the same thing", family: 'fill' },
  { ko: "운행", slug: 'leather_wallet', folder: 'items', nameEn: "running a service", family: 'fill' },
  { ko: "-앓이", slug: 'newspaper', folder: 'items', nameEn: "the -앓이 ending: a craze for it. From 앓다, to be ill — but nob", family: 'fill' },
  { ko: "지금", slug: 'public_etiquette', folder: 'items', nameEn: "now", family: 'fill' },
  { ko: "현재", slug: 'public_etiquette', folder: 'items', nameEn: "at present — the written form of 지금", family: 'fill' },
  { ko: "최근", slug: 'public_etiquette', folder: 'items', nameEn: "recently", family: 'fill' },
  { ko: "이름", slug: 'public_etiquette', folder: 'items', nameEn: "a name", family: 'fill' },
  { ko: "시작하다", slug: 'public_etiquette', folder: 'items', nameEn: "to start", family: 'fill' },
  { ko: "가다", slug: 'public_etiquette', folder: 'items', nameEn: "to go", family: 'fill' },
  { ko: "많다", slug: 'public_etiquette', folder: 'items', nameEn: "to be many", family: 'fill' },
  { ko: "한 달 새", slug: 'public_etiquette', folder: 'items', nameEn: "in the space of one month — 새 is 사이, the gap between", family: 'fill' },
  { ko: "이번 달", slug: 'public_etiquette', folder: 'items', nameEn: "this month", family: 'fill' },
  { ko: "N(이)라는", slug: 'kinds_types', folder: 'items', nameEn: "called N, going by the name N", family: 'fill' },
  { ko: "-까지만", slug: 'kinds_types', folder: 'items', nameEn: "only up to — and the 만 is where the trap is", family: 'fill' },
  // The blank-filling question type, added with 문항 1-2. Weather words take the sun and
  // the tap; the four endings take kinds_types, the tile every grammar point already uses —
  // there is nothing to draw for -더니 that a learner would recognise as -더니.
  { ko: "날씨", slug: 'sun_icon', folder: 'items', nameEn: "the weather", family: 'fill' },
  { ko: "비가 오다", slug: 'water_faucet', folder: 'items', nameEn: "to rain", family: 'fill' },
  { ko: "맑다", slug: 'sun_icon', folder: 'items', nameEn: "to be clear, to be fine", family: 'fill' },
  { ko: "개다", slug: 'sun_icon', folder: 'items', nameEn: "to clear up after rain", family: 'fill' },
  { ko: "오전", slug: 'sun_icon', folder: 'items', nameEn: "the morning, before noon", family: 'fill' },
  { ko: "-더니", slug: 'kinds_types', folder: 'items', nameEn: "I saw A, and then B", family: 'fill' },
  { ko: "-더라도", slug: 'kinds_types', folder: 'items', nameEn: "even if it does", family: 'fill' },
  { ko: "-아/어 가지고", slug: 'kinds_types', folder: 'items', nameEn: "and so — the spoken -아/어서", family: 'fill' },
  { ko: "-는 대신에", slug: 'kinds_types', folder: 'items', nameEn: "instead of doing it", family: 'fill' },
  { ko: "피곳하다", slug: 'get_scolded', folder: 'items', nameEn: "to be tired", family: 'fill' },
  { ko: "쉬다", slug: 'white_pillow', folder: 'items', nameEn: "to rest — the pillow 푹 쉬다 already uses", family: 'fill' },
  { ko: "일찍", slug: 'wall_calendar', folder: 'items', nameEn: "early", family: 'fill' },
  { ko: "너무", slug: 'kinds_types', folder: 'items', nameEn: "too, far too", family: 'fill' },
  { ko: "오늘", slug: 'wall_calendar', folder: 'items', nameEn: "today", family: 'fill' },
  { ko: "집", slug: 'detached_house', folder: 'items', nameEn: "home", family: 'fill' },
  { ko: "-아/어야지", slug: 'kinds_types', folder: 'items', nameEn: "I really must — a resolve", family: 'fill' },
  { ko: "-(으)ㄹ걸", slug: 'kinds_types', folder: 'items', nameEn: "I should have — a regret or a guess", family: 'fill' },
  { ko: "-더라", slug: 'kinds_types', folder: 'items', nameEn: "I saw that they did", family: 'fill' },
  { ko: "-기도 하다", slug: 'kinds_types', folder: 'items', nameEn: "also does it, sometimes does it", family: 'fill' },
  { ko: "-(으)니까", slug: 'kinds_types', folder: 'items', nameEn: "because — before a decision", family: 'fill' },
  { ko: "하고 말하다", slug: 'kinds_types', folder: 'items', nameEn: "to say, quoting the words as spoken", family: 'fill' },
  { ko: "취업 준비생", slug: 'restaurant_staff', folder: 'items', nameEn: "someone preparing to enter the job market", family: 'fill' },
  { ko: "이상", slug: 'kinds_types', folder: 'items', nameEn: "or more, upwards of", family: 'fill' },
  { ko: "면접시험", slug: 'restaurant_staff', folder: 'items', nameEn: "a job interview", family: 'fill' },
  { ko: "준비", slug: 'homework_notebook', folder: 'items', nameEn: "preparation", family: 'fill' },
  { ko: "고민하다", slug: 'get_scolded', folder: 'items', nameEn: "to agonise over something", family: 'fill' },
  { ko: "N(으)로 말미암아", slug: 'kinds_types', folder: 'items', nameEn: "owing to N — the formal twin of (으)로 인하여", family: 'fill' },
  { ko: "N에 따라서", slug: 'kinds_types', folder: 'items', nameEn: "depending on N — a correlation, not a cause", family: 'fill' },
  { ko: "N에도 불구하고", slug: 'kinds_types', folder: 'items', nameEn: "despite N", family: 'fill' },
  { ko: "시험 기간", slug: 'wall_calendar', folder: 'items', nameEn: "the exam period", family: 'fill' },
  { ko: "공부하다", slug: 'homework_notebook', folder: 'items', nameEn: "to study", family: 'fill' },
  { ko: "학생", slug: 'schoolhouse', folder: 'items', nameEn: "a student", family: 'fill' },
  { ko: "도서관", slug: 'hardcover_book', folder: 'items', nameEn: "a library", family: 'fill' },
  { ko: "밤새도록", slug: 'crescent_moon', folder: 'items', nameEn: "all night long", family: 'fill' },
  { ko: "불을 켜다", slug: 'light_bulb', folder: 'items', nameEn: "to switch a light on", family: 'fill' },
  { ko: "켜다", slug: 'light_bulb', folder: 'items', nameEn: "to switch on", family: 'fill' },
  { ko: "-아/어 놓다", slug: 'kinds_types', folder: 'items', nameEn: "do it and leave it that way", family: 'fill' },
  { ko: "-아/어 두다", slug: 'kinds_types', folder: 'items', nameEn: "do it and leave it that way — the twin of -아/어 놓다", family: 'fill' },
  { ko: "-곤 하다", slug: 'kinds_types', folder: 'items', nameEn: "used to do it, again and again", family: 'fill' }
];
if (typeof VOCAB_ART_ROWS !== 'undefined' && Array.isArray(VOCAB_ART_ROWS)) {
  VOCAB_ART_MORE_ROWS.forEach(function (r) {
    if (!VOCAB_ART_ROWS.some(function (x) { return x && x.ko === r.ko; })) VOCAB_ART_ROWS.push(r);
  });
}
if (typeof window !== 'undefined') {
  window.VOCAB_ART_MORE_ROWS = VOCAB_ART_MORE_ROWS;
}
