// Comprehensive test harness for texture overwrites and key resolution
const fs = require('fs');

global.window = {
  addEventListener: () => {},
  removeEventListener: () => {},
  AudioContext: class {},
  webkitAudioContext: class {}
};

global.document = {
  getElementById: () => ({ addEventListener: () => {}, style: {} }),
  createElement: () => ({ getContext: () => ({}) }),
  addEventListener: () => {}
};

// Create mock Phaser environment
const textureStore = new Map();
const animStore = new Map();

global.Phaser = {
  Textures: {
    FilterMode: { NEAREST: 1, LINEAR: 0 }
  },
  Input: { Keyboard: { KeyCodes: {} } },
  Scale: { RESIZE: 1, FIT: 0 },
  Game: class Game {},
  Scene: class Scene {}
};

class MockTexture {
  constructor(key, w, h) {
    this.key = key;
    this.width = w;
    this.height = h;
    this.filterMode = 0;
  }
  setFilter(mode) {
    this.filterMode = mode;
  }
}

class MockGraphics {
  constructor() {}
  fillStyle() {}
  fillRect() {}
  fillCircle() {}
  fillTriangle() {}
  beginPath() {}
  moveTo() {}
  lineTo() {}
  closePath() {}
  fillPath() {}
  lineBetween() {}
  lineStyle() {}
  strokePath() {}
  strokeRect() {}
  strokeCircle() {}
  generateTexture(key, width, height) {
    textureStore.set(key, new MockTexture(key, width, height));
  }
  destroy() {}
}

const mockScene = {
  textures: {
    exists: (key) => textureStore.has(key),
    remove: (key) => textureStore.delete(key),
    get: (key) => textureStore.get(key)
  },
  make: {
    graphics: () => new MockGraphics()
  },
  anims: {
    exists: (key) => animStore.has(key),
    create: (config) => animStore.set(config.key, config)
  }
};

const gameCode = fs.readFileSync('./game.js', 'utf8');

const fn = new Function('Phaser', 'mockScene', 'textureStore', 'animStore', gameCode + `
  return {
    PixelArtRenderer,
    FarmScene
  };
`);

try {
  const { PixelArtRenderer, FarmScene } = fn(global.Phaser, mockScene, textureStore, animStore);

  console.log("=== Step 1: PixelArtRenderer.generateAllTextures ===");
  PixelArtRenderer.generateAllTextures(mockScene);

  const snapshotGen = new Map();
  for (const [k, v] of textureStore.entries()) {
    snapshotGen.set(k, { width: v.width, height: v.height });
  }
  console.log("Total textures generated by PixelArtRenderer:", snapshotGen.size);

  const farmSceneInst = new FarmScene();
  farmSceneInst.textures = mockScene.textures;
  farmSceneInst.make = mockScene.make;
  farmSceneInst.anims = mockScene.anims;

  console.log("\n=== Step 2: FarmScene._bakeTextures ===");
  farmSceneInst._bakeTextures();

  console.log("Total textures after _bakeTextures:", textureStore.size);

  console.log("\n=== Texture Overwrite Analysis ===");
  const overwritten = [];
  for (const [k, v] of snapshotGen.entries()) {
    const newTex = textureStore.get(k);
    if (!newTex) {
      console.warn("Texture removed:", k);
    } else if (newTex.width !== v.width || newTex.height !== v.height) {
      overwritten.push({
        key: k,
        oldSize: `${v.width}x${v.height}`,
        newSize: `${newTex.width}x${newTex.height}`
      });
    }
  }

  if (overwritten.length > 0) {
    console.error("Overwritten texture keys detected:");
    overwritten.forEach(o => {
      console.error(`  - Key '${o.key}': original size ${o.oldSize} -> overwritten size ${o.newSize}`);
    });
  } else {
    console.log("No texture overwrites found.");
  }

  console.log("\n=== Animation Registration Analysis ===");
  const requiredAnims = [
    'player-walk-down', 'player-walk-up', 'player-walk-left', 'player-walk-right',
    'player-water', 'player-harvest', 'player-pick'
  ];
  for (const animKey of requiredAnims) {
    const anim = animStore.get(animKey);
    if (!anim) {
      console.error("Missing animation key:", animKey);
    } else {
      console.log(`Animation '${animKey}': ${anim.frames.length} frames registered.`);
    }
  }

} catch (err) {
  console.error("Error executing harness:", err);
}
