'use strict';

/**
 * Every content file the admin may edit, in one table.
 *
 * Before this, routes were added a unit at a time, and the result was uneven in a way nobody
 * could see from any single file: levels.json and Unit 10 were fully editable, while Units
 * 11, 13 and 14, the whole TOPIK world and every cassette bank had no route at all. Nothing
 * was broken — they were simply never connected, and there was no place where that would
 * show up as an absence.
 *
 * So the absence is now checkable. `COVERAGE` below is the whole rule: every file the game
 * publishes is either in CONTENT, or in UNEDITABLE with a reason. scripts/validate_content.js
 * compares this against what scripts/r2Content.js actually uploads, so adding a world without
 * an admin route fails the build instead of going quietly unnoticed for four units.
 *
 * The table is also load-bearing for a second reason. Vercel's Hobby plan allows twelve
 * serverless functions and the project uses eleven; the last time that ceiling was hit the
 * deployment failed while CI stayed green (see api/unit10/[kind].js). One route per content
 * kind is therefore not available even in principle — there is exactly one admin function,
 * and this is what it dispatches on.
 *
 * Every `validate` returns the normalised body and touches no disk, because on Vercel there
 * is no disk to touch: the write goes to GitHub and to R2 instead.
 */

const path = require('path');
const workbook = require('./workbook');
const world = require('./world');
const cassette = require('./cassette');
const skins = require('./skins');
const levels = require('./levels');

const p = (...parts) => path.join(...parts);

const WORLD_IDS = [
  { id: '2b-unit-10', label: '2B Unit 10 · 뭐 먹을래?' },
  { id: '2b-unit-11', label: '2B Unit 11 · 운동을 좀 해 보는 게 어때요?' },
  { id: '2b-unit-13', label: '2B Unit 13 · 조용해서 살기 좋아요' },
  { id: '2b-unit-14', label: '2B Unit 14 · 예절을 지킵시다' },
  { id: '2b-unit-15', label: '2B Unit 15 · 인생과 변화' },
  { id: 'topik-2', label: 'TOPIK II · exam practice' }
];

const QUIZ_UNITS = ['unit10', 'unit11', 'unit13', 'unit14', 'unit15', 'topik2'];
const CASSETTE_UNITS = ['unit10', 'unit11', 'unit13', 'unit14', 'unit15'];

// Human names for the bank keys, which are otherwise file stems. Derived from WORKBOOKS
// rather than listed again, so a bank added there cannot be missed here.
const BANK_LABEL = {
  unit14: 'Unit 14 · 연습 문제 (익힘책)',
  'unit14-textbook': 'Unit 14 · 교과서',
  'unit15-textbook': 'Unit 15 · 교과서',
  unit10: 'Unit 10 · 연습 문제 (익힘책)',
  'unit10-textbook': 'Unit 10 · 교과서',
  'topik2-questions': 'TOPIK II · 기출 문제'
};

const CONTENT = [
  {
    key: 'levels',
    rel: 'levels.json',
    group: 'Core',
    label: 'Levels and the 1500 words',
    validate: (body) => levels.validateLevels(body)
  },
  {
    key: 'skins',
    rel: p('skins', 'catalog.json'),
    group: 'Core',
    label: 'Skins catalogue',
    // The only validator that needs the repo, because it checks the sprites exist.
    validate: (body, ctx) => skins.normaliseCatalog(body, ctx && ctx.rootDir)
  },
  {
    key: 'layout',
    rel: world.LAYOUT_REL,
    group: 'Core',
    label: 'Farm layout — shared by every unit',
    validate: (body) => world.validateLayout(body)
  },
  ...WORLD_IDS.map((w) => ({
    key: 'world/' + w.id,
    rel: p('worlds', w.id + '.json'),
    group: 'Word lists',
    label: w.label,
    validate: (body) => world.validateWorld(body)
  })),
  ...QUIZ_UNITS.map((u) => ({
    key: 'quiz/' + u,
    rel: p('worlds', u + '-desk-quiz.json'),
    group: 'Desk quizzes',
    label: u.replace('unit', 'Unit ') + ' · 퀴즈',
    validate: (body) => world.validateQuiz(body)
  })),
  ...CASSETTE_UNITS.map((u) => ({
    key: 'cassette/' + u,
    rel: p('worlds', u + '-cassette.json'),
    group: 'Cassette banks',
    label: u.replace('unit', 'Unit ') + ' · 카세트',
    validate: (body) => cassette.validateCassette(body)
  })),
  ...Object.keys(workbook.WORKBOOKS).map((unit) => ({
    key: 'bank/' + unit,
    rel: workbook.WORKBOOKS[unit],
    group: 'Exercise banks',
    label: BANK_LABEL[unit] || unit,
    validate: (body, ctx) => workbook.validateWorkbook(body, (ctx && ctx.rel) || workbook.WORKBOOKS[unit])
  }))
];

// Files the game publishes that the admin deliberately does not edit. A reason is required:
// "not in the table" and "not editable on purpose" look identical from the outside, and only
// one of them is fine.
const UNEDITABLE = [
  { match: /^audio\//, why: 'recordings — cut from the book tapes by scripts/, and rendered TTS clips. Not text.' },
  { match: /^sprites\//, why: 'pixel art, plus a catalogue generated by scripts/register_art.js' },
  { rel: 'facts.json', why: 'generated from levels.json — edit the words, then regenerate (npm run verify:facts)' }
];

// Where a file is properly edited, when somewhere better than a JSON box exists. Most of
// these files do have a real editor — a word table, a quiz builder, an exercise page — and
// the Content tab was listing all twenty-one as raw JSON without saying so, which made the
// whole panel look harder than it is. A file with no `editor` is one where JSON genuinely is
// the only way in, and saying that plainly is more useful than pretending otherwise.
const EDITORS = {
  levels: { tab: 'levels', label: 'Levels tab' },
  skins: { tab: 'skins', label: 'Skins tab' },
  layout: { tab: 'unit10', panel: 'layout', label: 'Units tab, Map layout' }
};
WORLD_IDS.forEach((w) => {
  EDITORS['world/' + w.id] = { tab: 'unit10', panel: 'words', unit: w.id, label: 'Units tab, word table' };
});
QUIZ_UNITS.forEach((u) => {
  const world = '2b-' + u.replace('unit', 'unit-');
  EDITORS['quiz/' + u] = { tab: 'unit10', panel: 'quiz', unit: world, label: 'Units tab, quiz builder' };
});
Object.keys(workbook.WORKBOOKS).forEach((unit) => {
  EDITORS['bank/' + unit] = { tab: 'unit14', unit, label: 'Workbooks tab' };
});

function byKey(key) {
  return CONTENT.find((c) => c.key === key) || null;
}

function relOf(key) {
  const c = byKey(key);
  if (!c) throw new Error(`No content registered under "${key}"`);
  return c.rel;
}

// What the picker in the admin is built from: no validators, no paths that would let a
// browser guess at the repo layout.
function list() {
  return CONTENT.map((c) => ({
    key: c.key,
    group: c.group,
    label: c.label,
    editor: EDITORS[c.key] || null
  }));
}

// Is this published file accounted for? Used by scripts/validate_content.js against the real
// upload list, which is the only way the two can be kept honest with each other.
function coverage(rels) {
  const known = new Set(CONTENT.map((c) => c.rel.split(path.sep).join('/')));
  const uncovered = [];
  rels.forEach((raw) => {
    const rel = String(raw).split(path.sep).join('/');
    if (known.has(rel)) return;
    const excused = UNEDITABLE.some((u) => (u.match ? u.match.test(rel) : u.rel === rel));
    if (!excused) uncovered.push(rel);
  });
  return { uncovered, editable: known.size };
}

module.exports = { CONTENT, UNEDITABLE, EDITORS, byKey, relOf, list, coverage };
