const fs = require('fs');
const { getPaths } = require('./sync');

/**
 * Word-origin data access for the admin panel.
 *
 * Previously this module located, brace-matched, vm-evaluated and re-serialized a
 * `const VOCAB_FACTS = { ... }` literal embedded in game.js. That literal is gone:
 * an audit found it was 803 KB of 99.7% templated filler, so it was regenerated as
 * facts.json (~58 KB of structured origin data) by scripts/build_facts_json.js.
 *
 * facts.json is keyed by the Korean word (`ko`), not the English gloss, because all
 * 1500 Korean headwords are unique while English glosses collide and needed
 * case-insensitive reconciliation.
 *
 * Entry shape:
 *   { o: 'native' | 'sino' | 'sino-partial' | 'sino-verb' | 'sino-passive'
 *        | 'sino-adj' | 'sino-noun' | 'mixed' | 'mixed-loan' | 'loan' | 'unknown',
 *     h?: '父母',                        // hanja, when known
 *     p?: [['父','부','father'], ...],   // [char, reading, English gloss]
 *     l?: 'coffee', n?: '동생', s?: '하다', note?: '...' }
 *
 * IMPORTANT: facts.json is a build artifact. The curated source of truth lives in
 * the HANJA/SINO/LOANWORDS maps inside scripts/build_facts_json.js, so writes here
 * would be silently discarded on the next build. The write helpers therefore refuse
 * and point the caller at the generator instead of corrupting the pipeline.
 */

const ORIGIN_LABELS = {
  'native': 'Native Korean (고유어)',
  'sino': 'Sino-Korean (한자어)',
  'sino-partial': 'Sino-Korean (한자어, partial hanja)',
  'sino-verb': 'Sino-Korean verb',
  'sino-passive': 'Sino-Korean passive/causative verb',
  'sino-adj': 'Sino-Korean adjective',
  'sino-noun': 'Sino-Korean noun',
  'mixed': 'Sino-Korean + native Korean',
  'mixed-loan': 'Sino-Korean + loanword',
  'loan': 'Loanword (외래어)',
  'unknown': 'Not yet curated'
};

const GENERATOR_HINT =
  'facts.json is generated by scripts/build_facts_json.js. Edit the curated ' +
  'SINO / MIXED / LOANWORDS / NATIVE_NOTE maps in that script and re-run ' +
  '`node scripts/build_facts_json.js`, then restart the admin server.';

function readFacts(rootDir) {
  const paths = getPaths(rootDir);
  if (!fs.existsSync(paths.factsPath)) {
    throw new Error(
      `facts.json not found at ${paths.factsPath}. Run \`node scripts/build_facts_json.js\` to generate it.`
    );
  }
  return JSON.parse(fs.readFileSync(paths.factsPath, 'utf8'));
}

/** Human-readable one-liner for a facts.json entry, used by the admin table. */
function describeFact(entry) {
  if (!entry) return '';
  const label = ORIGIN_LABELS[entry.o] || entry.o || '';
  const bits = [label];
  if (entry.h) bits.push(entry.h);
  if (entry.p && entry.p.length) bits.push(entry.p.map(p => `${p[0]} (${p[1]}) “${p[2]}”`).join(' + '));
  if (entry.l) bits.push(`from “${entry.l}”`);
  if (entry.n) bits.push(`+ ${entry.n} (native)`);
  if (entry.s) bits.push(`+ ${entry.s}`);
  if (entry.note) bits.push(entry.note);
  return bits.filter(Boolean).join(' — ');
}

/**
 * Returns the origin dictionary plus coverage stats.
 *
 * "Covered" now means the word has a curated origin. Words classified `unknown`
 * are reported through `missingFacts` — that list is the curation backlog, and is
 * the metric worth watching: the old data reported ~100% coverage only because it
 * asserted "Native Korean" for every word it did not actually know.
 *
 * `casingDiscrepancies` is retained as an always-empty array for frontend
 * compatibility; keys are exact Korean headwords now, so casing cannot mismatch.
 */
function getVocabFactsData(rootDir) {
  const paths = getPaths(rootDir);
  const facts = readFacts(rootDir);

  const missingFacts = [];
  let curatedCount = 0;
  let totalWordsCount = 0;
  const byOrigin = {};

  if (fs.existsSync(paths.levelsPath)) {
    const levels = JSON.parse(fs.readFileSync(paths.levelsPath, 'utf8'));
    levels.forEach(lvl => {
      (lvl.words || []).forEach(w => {
        totalWordsCount++;
        const ko = (w.ko || '').normalize('NFC');
        const entry = facts[ko];
        const origin = entry ? entry.o : 'unknown';
        byOrigin[origin] = (byOrigin[origin] || 0) + 1;

        if (entry && origin !== 'unknown') {
          curatedCount++;
        } else {
          missingFacts.push({
            level: lvl.level,
            ko: w.ko,
            en: (w.en || '').trim(),
            hint: w.hint,
            category: w.categoryEn || w.category
          });
        }
      });
    });
  }

  const coveragePercentage = totalWordsCount > 0
    ? Math.round((curatedCount / totalWordsCount) * 10000) / 100
    : 100.0;

  return {
    facts,
    // Rendered strings so the admin table can display entries without knowing the schema.
    descriptions: Object.fromEntries(Object.entries(facts).map(([k, v]) => [k, describeFact(v)])),
    totalFacts: Object.keys(facts).length,
    exactMatchCount: curatedCount,
    casingMismatchCount: 0,
    coveragePercentage,
    byOrigin,
    missingFacts,
    casingDiscrepancies: [],
    readOnly: true,
    generatorHint: GENERATOR_HINT
  };
}

function refuseWrite(action) {
  const err = new Error(`Cannot ${action} word origins from the admin panel. ${GENERATOR_HINT}`);
  err.statusCode = 409;
  err.generatorHint = GENERATOR_HINT;
  throw err;
}

function addVocabFact()    { refuseWrite('add'); }
function updateVocabFact() { refuseWrite('update'); }
function deleteVocabFact() { refuseWrite('delete'); }

module.exports = {
  readFacts,
  describeFact,
  getVocabFactsData,
  addVocabFact,
  updateVocabFact,
  deleteVocabFact,
  ORIGIN_LABELS,
  GENERATOR_HINT
};
