'use strict';
// Promote only individually reviewed, hash-verified Unit illustrations.
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { loadCatalog, saveCatalog, registerArt } = require('./art_library');
const { applyTopikArt } = require('./apply_topik_art');
const { indexArtWords } = require('./index_art_words');
const root = path.resolve(__dirname, '..');
const file = path.join(root, 'docs/unit-art-redesign.json');
const queue = JSON.parse(fs.readFileSync(file, 'utf8'));
const ready = queue.entries.filter(e => e.reviewed === true);
const check = process.argv.includes('--check');
const hash = p => crypto.createHash('sha256').update(fs.readFileSync(path.join(root, p))).digest('hex');
if (process.argv.includes('--require-complete') && ready.length !== queue.entries.length) {
  throw new Error('Unit artwork incomplete: ' + ready.length + '/' + queue.entries.length + ' reviewed');
}
const pack = loadCatalog(root);
const rows = [];
const workbook = {};
const paths = new Set();
for (const entry of ready) {
  if (!['foods', 'items', 'quiz'].includes(entry.folder) || !/^unit\d+_[a-z0-9_]+$/.test(entry.slug)) throw new Error('Unsafe target path');
  if (entry.source !== 'docs/unit-art-sources/' + entry.slug + '.png'
      || entry.candidate !== 'docs/unit-art-candidates/' + entry.slug + '.png') throw new Error('Unexpected candidate/source path');
  if (hash(entry.source) !== entry.reviewedSourceHash || hash(entry.candidate) !== entry.reviewedCandidateHash) throw new Error('Artwork changed since review: ' + entry.slug);
  if (entry.processedSourceHash !== entry.reviewedSourceHash) throw new Error('Candidate was exported from an older source: ' + entry.slug);
  if (!entry.hasTransparency || !entry.binaryAlpha || entry.size?.[1] !== queue.processing.height) throw new Error('Invalid export: ' + entry.slug);
  const target = 'sprites/' + entry.folder + '/' + entry.slug + '.png';
  if (paths.has(target)) throw new Error('Duplicate Unit target');
  paths.add(target);
  entry.file = target;
  if (check && hash(target) !== entry.reviewedCandidateHash) throw new Error('Shipped image differs: ' + target);
  registerArt(pack, { folder: entry.folder, slug: entry.slug, nameEn: entry.en,
    wordKo: entry.ko || undefined, family: 'unit' + entry.unit + '-' + entry.type,
    usedBy: entry.type !== 'vocabulary' ? ['study-desk', 'workbook'] : ['vocabulary-book', 'word-detail', 'farm'],
    notes: 'Unit redesign: individually reviewed 192px PNG. Source and brief: docs/unit-art-redesign.json.' });
  if (entry.type === 'vocabulary') rows.push({ ko: entry.ko, nameEn: entry.en, folder: entry.folder,
    slug: entry.slug, worldId: '2b-unit-' + entry.unit, cooking: entry.cooking });
  if (entry.type === 'workbook') workbook[entry.workbookKey] = entry.folder + '/' + entry.slug + '.png';
}
const runtime = '// Generated by scripts/apply_unit_art.js from reviewed Unit artwork.\n'
  + 'const UNIT_VOCAB_ART_ROWS = ' + JSON.stringify(rows, null, 2) + ';\n'
  + 'const UNIT_WORKBOOK_ART_FILES = ' + JSON.stringify(workbook, null, 2) + ';\n'
  + "if (typeof window !== 'undefined') window.UNIT_VOCAB_ART_ROWS = UNIT_VOCAB_ART_ROWS;\n";
const worldWrites = new Map();
for (const unit of new Set(ready.filter(e => e.type === 'vocabulary').map(e => e.unit))) {
  const rel = 'worlds/2b-unit-' + unit + '.json';
  const world = JSON.parse(fs.readFileSync(path.join(root, rel), 'utf8'));
  const drawn = new Set(ready.filter(e => e.type === 'vocabulary' && e.unit === unit).map(e => e.ko));
  let changed = false;
  for (const word of world.level.words) {
    if (word.artPending && drawn.has(word.ko)) {
      // Preserve textbook-vs-supplement provenance independently of art coverage.
      word.chapterSupplement = true;
      delete word.artPending;
      changed = true;
    }
  }
  if (changed) worldWrites.set(rel, JSON.stringify(world, null, 2) + '\n');
}
if (check) {
  if (worldWrites.size) throw new Error('Reviewed Unit words are still marked artPending');
  if (fs.readFileSync(path.join(root, 'js/vocabArtUnits.js'), 'utf8') !== runtime) throw new Error('Unit runtime mapping is stale');
} else {
  // All candidates and destinations have been checked before any activation.
  saveCatalog(root, pack);
  for (const entry of ready) {
    // Leave identical active sprites untouched, including files being served by
    // the local preview on Windows. Changed or missing exports are still copied.
    if (!fs.existsSync(path.join(root, entry.file)) || hash(entry.file) !== entry.reviewedCandidateHash) {
      fs.copyFileSync(path.join(root, entry.candidate), path.join(root, entry.file));
    }
    entry.status = 'shipped';
  }
  fs.writeFileSync(path.join(root, 'js/vocabArtUnits.js'), runtime);
  for (const [rel, content] of worldWrites) fs.writeFileSync(path.join(root, rel), content);
  queue.status = ready.length === queue.entries.length ? 'complete' : 'in-progress';
  fs.writeFileSync(file, JSON.stringify(queue, null, 2) + '\n');
  applyTopikArt(root, { requireComplete: true });
  indexArtWords(root);
}
console.log(ready.length + '/' + queue.entries.length + ' Unit images ' + (check ? 'verified' : 'active'));
