/**
 * build_facts_json.js — generates facts.json (English) from levels.json
 *
 * Replaces the old scripts/build_vocab_facts.js, which inlined an 803 KB
 * `VOCAB_FACTS` literal into game.js. That data was 99.7% templated filler:
 * every entry shared the same closing sentence and the same mnemonic scaffold,
 * and the "example sentences" were generated by string concatenation and were
 * frequently ungrammatical (e.g. 먹다 -> "매일 한국어로 먹며 연습합니다").
 *
 * This script keeps only the signal that cannot be derived at runtime — the
 * curated word origin (hanja breakdown / loanword source / native) — and emits
 * it as structured data. Romanization, syllable count and batchim are computed
 * from the Hangul itself in getFunFact(), so they are deliberately NOT stored.
 *
 * Output schema, keyed by word.ko (all 1500 are unique):
 *   { o: 'native' }
 *   { o: 'sino',       h: '父母', p: [['父','부','father'], ['母','모','mother']] }
 *   { o: 'mixed',      h: '男',   p: [['男','남','male']], n: '동생' }
 *   { o: 'mixed-loan', h: '信用', p: [...], l: 'card' }
 *   { o: 'loan',       l: 'coffee' }
 *   { o: 'sino-verb' | 'sino-passive' | 'sino-adj' | 'sino-noun' }
 *
 * Run:  node scripts/build_facts_json.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const levelsData = JSON.parse(fs.readFileSync(path.join(ROOT, 'levels.json'), 'utf8'));

// ─────────────────────────────────────────────────────────────────────────────
// Hanja eumhun (音訓) glosses, translated to English.
// Keyed by the full "<hanja> <korean-meaning> <korean-reading>" token because
// the same character carries different glosses in different compounds
// (子 아들 "son" vs 子 첫째지 "first branch"; 行 다닐 "to go" vs 行 행할 "to carry out").
// ─────────────────────────────────────────────────────────────────────────────
const EUMHUN_EN = {
  '兄 형 형': 'elder brother',        '男 사내 남': 'male',
  '女 계집 녀': 'female',             '父 아비 부': 'father',
  '母 어미 모': 'mother',             '子 아들 자': 'son',
  '女 딸 녀': 'daughter',             '親 친할 친': 'close, intimate',
  '戚 겨레 척': 'kin',                '三 석 삼': 'three',
  '寸 마디 촌': 'degree of kinship',  '姨 이모 이': 'maternal aunt',
  '姑 시어미 고': 'paternal aunt',    '孫 손자 손': 'grandchild',
  '學 배울 학': 'to learn',           '校 학교 교': 'school',
  '生 날 생': 'to be born',           '先 먼저 선': 'first, before',
  '醫 의원 의': 'healing, medicine',  '院 집 원': 'institution',
  '師 스승 사': 'master, teacher',    '藥 약 약': 'medicine',
  '局 판 국': 'bureau, office',       '銀 은 은': 'silver',
  '行 다닐 행': 'to circulate',       '郵 우편 우': 'post, mail',
  '遞 갈아탈 체': 'to relay',         '警 경계할 경': 'to guard, to warn',
  '察 살필 찰': 'to inspect',         '署 관청 서': 'government office',
  '消 사라질 소': 'to extinguish',    '防 막을 방': 'to prevent',
  '百 일백 백': 'hundred',            '貨 재물 화': 'goods',
  '店 가게 점': 'shop',               '圖 그림 도': 'picture, diagram',
  '書 글 서': 'writing, book',        '館 집 관': 'hall, building',
  '博 넓을 박': 'broad, extensive',   '物 물건 물': 'thing, object',
  '美 아름다울 미': 'beautiful',      '術 재주 술': 'art, technique',
  '公 공평할 공': 'public',           '園 동산 원': 'garden',
  '映 비칠 영': 'to project',         '畫 그림 화': 'picture',
  '容 얼굴 용': 'face, appearance',   '室 집 실': 'room',
  '地 땅 지': 'earth, ground',        '下 아래 하': 'below',
  '鐵 쇠 철': 'iron',                 '驛 역 역': 'station',
  '空 하늘 공': 'sky, empty',         '港 항구 항': 'harbour',
  '口 입 구': 'mouth, opening',       '駐 살 주': 'to station, to park',
  '車 수레 차': 'vehicle',            '場 마당 장': 'place, grounds',
  '食 먹을 식': 'to eat, food',       '堂 집 당': 'hall',
  '飲 마실 음': 'to drink',           '料 헤아릴 료': 'material, fee',
  '水 물 수': 'water',                '茶 차 다': 'tea',
  '饅 만두 만': 'steamed bun',        '頭 머리 두': 'head',
  '果 열매 과': 'fruit',              '實 열매 실': 'fruit, substance',
  '時 때 시': 'time',                 '間 사이 간': 'interval',
  '日 날 일': 'day, sun',             '字 글자 자': 'character',
  '週 돌 주': 'week, cycle',          '末 끝 말': 'end',
  '平 평평할 평': 'level, ordinary',  '正 바를 정': 'upright, exact',
  '午 낮 오': 'noon',                 '子 첫째지 자': 'first zodiac branch (midnight)',
  '季 계절 계': 'season',             '節 마디 절': 'node, section',
  '氣 기운 기': 'air, energy',        '溫 따뜻할 온': 'warm',
  '濕 축축할 습': 'damp',             '度 법도 도': 'degree, measure',
  '運 옮길 운': 'to move, to carry',  '動 움직일 동': 'to move',
  '文 글 문': 'writing, text',        '化 될 화': 'to transform',
  '餘 남을 여': 'surplus, spare',     '暇 겨레 가': 'leisure',
  '健 건강할 건': 'healthy',          '康 편안할 강': 'at ease, well',
  '症 증세 증': 'symptom',            '狀 형상 상': 'condition, form',
  '科 과목 과': 'branch, subject',    '目 눈 목': 'eye, item',
  '試 시험할 시': 'to test',          '驗 시험 험': 'examination',
  '職 직분 직': 'post, duty',         '業 업 업': 'occupation',
  '務 힘쓸 무': 'to strive, duty',    '課 매길 과': 'to assign, lesson',
  '題 제목 제': 'topic, title',       '住 살 주': 'to reside',
  '居 살 거': 'to dwell',             '家 집 가': 'house, family',
  '具 갖출 구': 'implement',          '環 고리 환': 'ring, circle',
  '境 지경 경': 'boundary, region',   '情 뜻 정': 'feeling, circumstance',
  '報 알릴 보': 'to report',          '通 통할 통': 'to pass through',
  '信 믿을 신': 'to trust, message',  '放 놓을 방': 'to release, to air',
  '送 보낼 송': 'to send',            '新 새 신': 'new',
  '聞 들을 문': 'to hear',            '禮 예도 예': 'courtesy, rite',
  '社 모임 사': 'association',        '會 모일 회': 'to gather',
  '制 제도 제': 'system, to regulate','問 물을 문': 'to ask',
  '金 돈 금': 'gold, money',          '融 녹을 융': 'to melt, to circulate',
  '經 지날 경': 'to pass, to manage', '濟 건널 제': 'to cross, to relieve',
  '費 쓸 비': 'to spend, expense',    '市 저자 시': 'market, city',
  '貿 무역할 무': 'to trade',         '易 바꿀 역': 'to exchange',
  '產 낳을 산': 'to produce',         '研 갈 연': 'to grind, to research',
  '究 구할 구': 'to investigate',     '技 재주 기': 'skill',
  '遺 남길 유': 'to leave behind',    '產 재산 산': 'property',
  '演 펼칠 연': 'to perform',         '藝 재주 예': 'art, craft',
  '判 판단할 판': 'to judge',         '斷 끊을 단': 'to cut off, to decide',
  '價 값 가': 'price',                '値 값 치': 'value',
  '基 터 기': 'foundation',           '準 평평할 준': 'standard',
  '概 대개 개': 'outline, general',   '念 생각 념': 'thought',
  '原 근본 원': 'origin, root',       '理 이치 리': 'principle',
  '政 정사 정': 'governance',         '治 다스릴 치': 'to govern',
  '府 관청 부': 'government office',  '法 법 법': 'law',
  '秩 차례 질': 'order, sequence',    '序 차례 서': 'order, sequence',
  '行 행할 행': 'to carry out',       '民 백성 민': 'people, citizen',
  '豫 먼저 예': 'beforehand',         '約 약속 약': 'promise',
  '注 대댈 주': 'to pour, to note',   '文 글자 문': 'character, writing',
  '計 셈할 계': 'to count',           '算 셈할 산': 'to calculate',
  '領 거둘 영': 'to receive',         '收 거둘 수': 'to collect',
  '證 증거 증': 'proof, certificate', '從 따를 종': 'to follow',
  '業 업무 업': 'work, business',     '員 인원 원': 'member, staff',
  '格 격식 격': 'form, standard',     '割 쪼갤 할': 'to split',
  '引 끌 인': 'to pull',              '決 결단할 결': 'to decide',
  '済 건널 제': 'to settle',          '現 나타날 현': 'to appear, present',
  '座 자리 좌': 'seat, account',      '移 옮길 이': 'to transfer',
  '替 바꿀 체': 'to substitute',      '購 살 구': 'to purchase',
  '買 살 매': 'to buy',               '販 팔 판': 'to vend',
  '賣 팔 매': 'to sell',              '節 아낄 절': 'to economize',
  '浪 물결 랑': 'wave, wasteful',     '無 없을 무': 'without, none',
  '東 동녘 동': 'east',               '西 서녘 서': 'west',
  '南 남녘 남': 'south',              '北 북녘 북': 'north',
  '中 가운데 중': 'middle',           '央 가운데 앙': 'centre',
  '手 손 수': 'hand',                 '段 단계 단': 'step, stage',
  '路 길 로': 'road',                 '線 줄 선': 'line',
  '換 바꿀 환': 'to exchange',        '乘 탈 승': 'to ride, to board',
  '由 까닭 유': 'reason, by way of',  '出 날 출': 'to exit',
  // Used only by the corrected 환불 entry below.
  '還 돌아올 환': 'to return',        '拂 떨칠 불': 'to pay out',
  // Used only by 신용카드.
  '用 쓸 용': 'to use',
};

// ─────────────────────────────────────────────────────────────────────────────
// Curated word origins. Format: [hanja, [eumhun tokens...]] for pure Sino-Korean,
// or a descriptor object for native / mixed / loan words.
//
// Three entries are corrected relative to the old HANJA_MAP, which contained
// hanja that did not match its own breakdown:
//   무료   listed 免費 but decomposed 無 + 料   -> 無料 is correct
//   환불   listed the parts in reverse order    -> 還拂
//   계좌이체 listed 口座 (= 구좌, the obsolete term) -> 計座移替
// ─────────────────────────────────────────────────────────────────────────────
const SINO = {
  '형': ['兄', ['兄 형 형']],
  '부모': ['父母', ['父 아비 부', '母 어미 모']],
  '자녀': ['子女', ['子 아들 자', '女 딸 녀']],
  '친척': ['親戚', ['親 친할 친', '戚 겨레 척']],
  '삼촌': ['三寸', ['三 석 삼', '寸 마디 촌']],
  '이모': ['姨母', ['姨 이모 이', '母 어미 모']],
  '고모': ['姑母', ['姑 시어미 고', '母 어미 모']],
  '손자': ['孫子', ['孫 손자 손', '子 아들 자']],
  '손녀': ['孫女', ['孫 손자 손', '女 딸 녀']],
  '학교': ['學校', ['學 배울 학', '校 학교 교']],
  '학생': ['學生', ['學 배울 학', '生 날 생']],
  '선생님': ['先生', ['先 먼저 선', '生 날 생']],
  '병원': ['醫院', ['醫 의원 의', '院 집 원']],
  '의사': ['醫師', ['醫 의원 의', '師 스승 사']],
  '약국': ['藥局', ['藥 약 약', '局 판 국']],
  '은행': ['銀行', ['銀 은 은', '行 다닐 행']],
  '우체국': ['郵遞局', ['郵 우편 우', '遞 갈아탈 체', '局 판 국']],
  '경찰서': ['警察署', ['警 경계할 경', '察 살필 찰', '署 관청 서']],
  '소방서': ['消防署', ['消 사라질 소', '防 막을 방', '署 관청 서']],
  '백화점': ['百貨店', ['百 일백 백', '貨 재물 화', '店 가게 점']],
  '도서관': ['圖書館', ['圖 그림 도', '書 글 서', '館 집 관']],
  '박물관': ['博物館', ['博 넓을 박', '物 물건 물', '館 집 관']],
  '미술관': ['美術館', ['美 아름다울 미', '術 재주 술', '館 집 관']],
  '공원': ['公園', ['公 공평할 공', '園 동산 원']],
  '영화관': ['映畫館', ['映 비칠 영', '畫 그림 화', '館 집 관']],
  '미용실': ['美容室', ['美 아름다울 미', '容 얼굴 용', '室 집 실']],
  '지하철역': ['地下鐵驛', ['地 땅 지', '下 아래 하', '鐵 쇠 철', '驛 역 역']],
  '지하철': ['地下鐵', ['地 땅 지', '下 아래 하', '鐵 쇠 철']],
  '공항': ['空港', ['空 하늘 공', '港 항구 항']],
  '항구': ['港口', ['港 항구 항', '口 입 구']],
  '주차장': ['駐車場', ['駐 살 주', '車 수레 차', '場 마당 장']],
  '식당': ['食堂', ['食 먹을 식', '堂 집 당']],
  '음료수': ['飲料水', ['飲 마실 음', '料 헤아릴 료', '水 물 수']],
  '음식': ['飲食', ['飲 마실 음', '食 먹을 식']],
  '차': ['茶', ['茶 차 다']],
  '만두': ['饅頭', ['饅 만두 만', '頭 머리 두']],
  '과일': ['果實', ['果 열매 과', '實 열매 실']],
  '시간': ['時間', ['時 때 시', '間 사이 간']],
  '일자': ['日字', ['日 날 일', '字 글자 자']],
  '주말': ['週末', ['週 돌 주', '末 끝 말']],
  '평일': ['平日', ['平 평평할 평', '日 날 일']],
  '정오': ['正午', ['正 바를 정', '午 낮 오']],
  '자정': ['子正', ['子 첫째지 자', '正 바를 정']],
  '계절': ['季節', ['季 계절 계', '節 마디 절']],
  '기온': ['氣溫', ['氣 기운 기', '溫 따뜻할 온']],
  '습도': ['濕度', ['濕 축축할 습', '度 법도 도']],
  '온도': ['溫度', ['溫 따뜻할 온', '度 법도 도']],
  '운동': ['運動', ['運 옮길 운', '動 움직일 동']],
  '문화': ['文化', ['文 글 문', '化 될 화']],
  '여가': ['餘暇', ['餘 남을 여', '暇 겨레 가']],
  '건강': ['健康', ['健 건강할 건', '康 편안할 강']],
  '증상': ['症狀', ['症 증세 증', '狀 형상 상']],
  '과목': ['科目', ['科 과목 과', '目 눈 목']],
  '시험': ['試驗', ['試 시험할 시', '驗 시험 험']],
  '직업': ['職業', ['職 직분 직', '業 업 업']],
  '업무': ['業務', ['業 업 업', '務 힘쓸 무']],
  '과제': ['課題', ['課 매길 과', '題 제목 제']],
  '주거': ['住居', ['住 살 주', '居 살 거']],
  '가구': ['家具', ['家 집 가', '具 갖출 구']],
  '환경': ['環境', ['環 고리 환', '境 지경 경']],
  '정보': ['情報', ['情 뜻 정', '報 알릴 보']],
  '통신': ['通信', ['通 통할 통', '信 믿을 신']],
  '방송': ['放送', ['放 놓을 방', '送 보낼 송']],
  '신문': ['新聞', ['新 새 신', '聞 들을 문']],
  '예절': ['禮節', ['禮 예도 예', '節 마디 절']],
  '사회': ['社會', ['社 모임 사', '會 모일 회']],
  '제도': ['制度', ['制 제도 제', '度 법도 도']],
  '문제': ['問題', ['問 물을 문', '題 제목 제']],
  '금융': ['金融', ['金 돈 금', '融 녹을 융']],
  '경제': ['經濟', ['經 지날 경', '濟 건널 제']],
  '소비': ['消費', ['消 사라질 소', '費 쓸 비']],
  '시장': ['市場', ['市 저자 시', '場 마당 장']],
  '무역': ['貿易', ['貿 무역할 무', '易 바꿀 역']],
  '산업': ['產業', ['產 낳을 산', '業 업 업']],
  '과학': ['科學', ['科 과목 과', '學 배울 학']],
  '연구': ['研究', ['研 갈 연', '究 구할 구']],
  '기술': ['技術', ['技 재주 기', '術 재주 술']],
  '유산': ['遺產', ['遺 남길 유', '產 재산 산']],
  '공연': ['公演', ['公 공평할 공', '演 펼칠 연']],
  '예술': ['藝術', ['藝 재주 예', '術 재주 술']],
  '문학': ['文學', ['文 글 문', '學 배울 학']],
  '판단': ['判斷', ['判 판단할 판', '斷 끊을 단']],
  '가치': ['價値', ['價 값 가', '値 값 치']],
  '기준': ['基準', ['基 터 기', '準 평평할 준']],
  '개념': ['概念', ['概 대개 개', '念 생각 념']],
  '원리': ['原理', ['原 근본 원', '理 이치 리']],
  '정치': ['政治', ['政 정사 정', '治 다스릴 치']],
  '정부': ['政府', ['政 정사 정', '府 관청 부']],
  '법': ['法', ['法 법 법']],
  '질서': ['秩序', ['秩 차례 질', '序 차례 서']],
  '행정': ['行政', ['行 행할 행', '政 정사 정']],
  '시민': ['市民', ['市 저자 시', '民 백성 민']],
  '예약': ['豫約', ['豫 먼저 예', '約 약속 약']],
  '주문': ['注文', ['注 대댈 주', '文 글자 문']],
  '계산': ['計算', ['計 셈할 계', '算 셈할 산']],
  '영수증': ['領收證', ['領 거둘 영', '收 거둘 수', '證 증거 증']],
  '종업원': ['從業員', ['從 따를 종', '業 업무 업', '員 인원 원']],
  '가격': ['價格', ['價 값 가', '格 격식 격']],
  '할인': ['割引', ['割 쪼갤 할', '引 끌 인']],
  '결제': ['決済', ['決 결단할 결', '済 건널 제']],
  '현금': ['現金', ['現 나타날 현', '金 돈 금']],
  '계좌이체': ['計座移替', ['計 셈할 계', '座 자리 좌', '移 옮길 이', '替 바꿀 체']],
  '환불': ['還拂', ['還 돌아올 환', '拂 떨칠 불']],
  '구매': ['購買', ['購 살 구', '買 살 매']],
  '판매': ['販賣', ['販 팔 판', '賣 팔 매']],
  '절약': ['節約', ['節 아낄 절', '約 약속 약']],
  '낭비': ['浪費', ['浪 물결 랑', '費 쓸 비']],
  '무료': ['無料', ['無 없을 무', '料 헤아릴 료']],
  '중앙': ['中央', ['中 가운데 중', '央 가운데 앙']],
  '수단': ['手段', ['手 손 수', '段 단계 단']],
  '요금': ['料金', ['料 헤아릴 료', '金 돈 금']],
  '노선': ['路線', ['路 길 로', '線 줄 선']],
  '환승': ['換乘', ['換 바꿀 환', '乘 탈 승']],
  '하차': ['下車', ['下 아래 하', '車 수레 차']],
  '승차': ['乘車', ['乘 탈 승', '車 수레 차']],
  '경유': ['經由', ['經 지날 경', '由 까닭 유']],
  '출구': ['出口', ['出 날 출', '口 입 구']],
};

// Sino-Korean root + native Korean suffix.
const MIXED = {
  '남동생': ['男', ['男 사내 남'], '동생'],
  '여동생': ['女', ['女 계집 녀'], '동생'],
  '동쪽': ['東', ['東 동녘 동'], '쪽'],
  '서쪽': ['西', ['西 서녘 서'], '쪽'],
  '남쪽': ['南', ['南 남녘 남'], '쪽'],
  '북쪽': ['北', ['北 북녘 북'], '쪽'],
};

// Sino-Korean root + English loanword.
const MIXED_LOAN = {
  '신용카드': ['信用', ['信 믿을 신', '用 쓸 용'], 'card'],
};

// Native Korean words with a note worth keeping (the rest just get o:'native').
const NATIVE_NOTE = {
  '아버지': 'respectful term for one\'s father',
  '어머니': 'respectful term for one\'s mother',
  '할아버지': 'grandfather; also used for any elderly man',
  '할머니': 'grandmother; also used for any elderly woman',
};

const LOANWORDS = {
  '커피': 'coffee', '빵': 'pão (Portuguese, via Japanese)', '마트': 'mart',
  '버스': 'bus', '택시': 'taxi', '셔츠': 'shirt', '코트': 'coat',
  '점퍼': 'jumper', '스마트폰': 'smartphone', '인터넷': 'internet',
  'SNS': 'SNS (social networking service)', 'PD': 'PD (producer/director)',
  '뉴스': 'news', '드라마': 'drama', '라디오': 'radio', '텔레비전': 'television',
  '컴퓨터': 'computer', '이메일': 'e-mail', '블로그': 'blog', '스포츠': 'sports',
  '테니스': 'tennis', '골프': 'golf', '피자': 'pizza', '햄버거': 'hamburger',
  '아이스크림': 'ice cream', '초콜릿': 'chocolate', '케이크': 'cake',
  '샌드위치': 'sandwich', '콜라': 'cola', '사이다': 'cider', '맥주': 'beer',
  '위스키': 'whisky', '뷔페': 'buffet', '메뉴': 'menu', '호텔': 'hotel',
  '리조트': 'resort', '모텔': 'motel', '패션': 'fashion', '스타일': 'style',
  '디자인': 'design', '팀': 'team', '게이머': 'gamer', '게임': 'game',
  '데이터': 'data', '시스템': 'system', '네트워크': 'network', '사이트': 'site',
  '메시지': 'message', '세일': 'sale', '메뉴판': 'menu (board)', '카메라': 'camera',
  '샤워': 'shower', '샴푸': 'shampoo', '비누': 'soap (Portuguese sabão)',
  '티셔츠': 'T-shirt', '청바지': 'jeans', '슬리퍼': 'slipper', '넥타이': 'necktie',
  '와이셔츠': 'white shirt', '원피스': 'one-piece dress', '스커트': 'skirt',
  '재킷': 'jacket', '패딩': 'padding (padded coat)', '핸드폰': 'hand phone',
  '노트북': 'notebook (laptop)', '모니터': 'monitor', '키보드': 'keyboard',
  '마우스': 'mouse', '마이크': 'mic', '헤드폰': 'headphone', '이어폰': 'earphone',
  '스피커': 'speaker', '택배': 'parcel delivery', '서비스': 'service',
  '이벤트': 'event', '캠페인': 'campaign', '아이디어': 'idea', '스트레스': 'stress',
  '다이어트': 'diet', '비키니': 'bikini', '선글라스': 'sunglasses',
  '립스틱': 'lipstick', '파운데이션': 'foundation', '마스크': 'mask',
  '시즌': 'season', '매치': 'match', '골': 'goal', '패스': 'pass', '슛': 'shoot',
  '코치': 'coach', '매니저': 'manager', '프로': 'pro', '팬': 'fan',
  '콘서트': 'concert', '밴드': 'band', '아티스트': 'artist',
};

// 맥주 and 택배 are Sino-Korean, not loanwords — the old list mis-tagged them.
delete LOANWORDS['맥주'];
delete LOANWORDS['택배'];

// ─────────────────────────────────────────────────────────────────────────────

function eumhun(tokens) {
  return tokens.map(t => {
    const en = EUMHUN_EN[t];
    if (!en) { throw new Error(`Missing English gloss for eumhun token: "${t}"`); }
    const [char, , reading] = t.split(' ');
    return [char, reading, en];
  });
}

// Derivational suffixes that attach to a Sino-Korean root without changing it.
// 건강하다 -> 건강 (健康) + 하다, so the curated hanja for the root still applies.
// Ordered longest-first so 시키다 wins over 다.
const DERIV_SUFFIXES = [
  ['시키다', 'sino-passive'], ['스럽다', 'sino-adj'], ['롭다', 'sino-adj'],
  ['하다', 'sino-verb'],      ['되다', 'sino-passive'],
  ['적이다', 'sino-adj'],     ['적', 'sino-adj'],
];

// Curated Sino roots of 2+ syllables, longest first, for compound matching.
const SINO_ROOTS_BY_LEN = Object.keys(SINO)
  .filter(k => k.length >= 2)
  .sort((a, b) => b.length - a.length);

function classify(ko) {
  if (SINO[ko])        { const [h, t] = SINO[ko];              return { o: 'sino', h, p: eumhun(t) }; }
  if (MIXED[ko])       { const [h, t, n] = MIXED[ko];          return { o: 'mixed', h, p: eumhun(t), n }; }
  if (MIXED_LOAN[ko])  { const [h, t, l] = MIXED_LOAN[ko];     return { o: 'mixed-loan', h, p: eumhun(t), l }; }
  if (LOANWORDS[ko])   { return { o: 'loan', l: LOANWORDS[ko] }; }
  if (NATIVE_NOTE[ko]) { return { o: 'native', note: NATIVE_NOTE[ko] }; }

  // A curated Sino root carrying a derivational suffix keeps its hanja.
  for (const [suf, kind] of DERIV_SUFFIXES) {
    if (!ko.endsWith(suf)) continue;
    const root = ko.slice(0, -suf.length);
    if (SINO[root]) {
      const [h, t] = SINO[root];
      return { o: kind, h, p: eumhun(t), s: suf };
    }
    if (LOANWORDS[root]) return { o: 'loan', l: LOANWORDS[root], s: suf };
  }

  // Compounds built on curated Sino roots: 건강검진 contains 건강 (健康), so the word
  // is certainly Sino-Korean even though we only know part of the hanja. Scans
  // left to right taking the longest root at each position, so 중앙도서관 yields
  // both 中央 and 圖書館.
  //
  // Restricted to roots of 2+ syllables — a single Hangul syllable maps to many
  // characters (차 = 茶 / 車 / 差 / 次), so one-syllable matching would emit wrong
  // etymology. Emitted as `sino-partial`; `k` lists the parts we can vouch for.
  const found = [];
  for (let i = 0; i < ko.length; ) {
    const root = SINO_ROOTS_BY_LEN.find(r => ko.startsWith(r, i));
    if (root) { found.push(root); i += root.length; } else { i++; }
  }
  if (found.length) {
    return {
      o: 'sino-partial',
      h: found.map(r => SINO[r][0]).join(''),
      p: found.flatMap(r => eumhun(SINO[r][1])),
      k: found,
    };
  }

  // Suffix heuristics for Sino-Korean words we have no curated hanja for.
  if (ko.endsWith('하다') && ko.length >= 4)            return { o: 'sino-verb' };
  if (ko.endsWith('되다') || ko.endsWith('시키다'))      return { o: 'sino-passive' };
  if (ko.endsWith('적'))                                 return { o: 'sino-adj' };
  if (/[성력감]$/.test(ko))                              return { o: 'sino-noun' };

  // Honest default. The old VOCAB_FACTS claimed "고유어 (Native Korean word)" for
  // 1090 words with no evidence, which mislabels plenty of Sino-Korean vocabulary
  // (건강검진, 환경오염, 기술혁신 …). Unknown stays unknown; the UI shows
  // pronunciation and syllable structure instead of asserting an origin.
  return { o: 'unknown' };
}

// ── Build ────────────────────────────────────────────────────────────────────
const facts = {};
const stats = {};
let total = 0;

for (const level of levelsData) {
  for (const w of (level.words || [])) {
    const ko = (w.ko || '').normalize('NFC');
    if (!ko) continue;
    total++;
    if (facts[ko]) continue;           // levels.json has 1500 unique ko, but be safe
    const f = classify(ko);
    facts[ko] = f;
    stats[f.o] = (stats[f.o] || 0) + 1;
  }
}

const out = path.join(ROOT, 'facts.json');
fs.writeFileSync(out, JSON.stringify(facts), 'utf8');

const kb = (fs.statSync(out).size / 1024).toFixed(1);
console.log(`facts.json written: ${Object.keys(facts).length} entries from ${total} words, ${kb} KB`);
console.log('Origin breakdown:');
Object.entries(stats).sort((a, b) => b[1] - a[1])
  .forEach(([k, v]) => console.log(`  ${k.padEnd(12)} ${String(v).padStart(5)}`));
