/**
 * build_facts_json.js — generates facts.json (English) from levels.json
 *
 * Replaces the old scripts/build_vocab_facts.js, which inlined an 803 KB
 * `VOCAB_FACTS` literal into game.js. That data was 99.7% templated filler:
 * every entry shared the same closing sentence and the same mnemonic scaffold,
 * and the "example sentences" were generated by string concatenation and were
 * frequently ungrammatical (e.g. 먹다 -> "매일 한국어로 먹며 연습합니다").
 *
 * This script keeps only the signal that cannot be derived at runtime — the
 * curated word origin (hanja breakdown / loanword source / native) — and emits
 * it as structured data. Romanization, syllable count and batchim are computed
 * from the Hangul itself in getFunFact(), so they are deliberately NOT stored.
 *
 * Output schema, keyed by word.ko (all 1500 are unique):
 *   { o: 'native' }
 *   { o: 'sino',       h: '父母', p: [['父','부','father'], ['母','모','mother']] }
 *   { o: 'mixed',      h: '男',   p: [['男','남','male']], n: '동생' }
 *   { o: 'mixed-loan', h: '信用', p: [...], l: 'card' }
 *   { o: 'loan',       l: 'coffee' }
 *   { o: 'sino-verb' | 'sino-passive' | 'sino-adj' | 'sino-noun' }
 *
 * Run:  node scripts/build_facts_json.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const levelsData = JSON.parse(fs.readFileSync(path.join(ROOT, 'levels.json'), 'utf8'));

// ─────────────────────────────────────────────────────────────────────────────
// Hanja eumhun (音訓) glosses, translated to English.
// Keyed by the full "<hanja> <korean-meaning> <korean-reading>" token because
// the same character carries different glosses in different compounds
// (子 아들 "son" vs 子 첫째지 "first branch"; 行 다닐 "to go" vs 行 행할 "to carry out").
// ─────────────────────────────────────────────────────────────────────────────
const EUMHUN_EN = {
  '兄 형 형': 'elder brother',        '男 사내 남': 'male',
  '女 계집 녀': 'female',             '父 아비 부': 'father',
  '母 어미 모': 'mother',             '子 아들 자': 'son',
  '女 딸 녀': 'daughter',             '親 친할 친': 'close, intimate',
  '戚 겨레 척': 'kin',                '三 석 삼': 'three',
  '寸 마디 촌': 'degree of kinship',  '姨 이모 이': 'maternal aunt',
  '姑 시어미 고': 'paternal aunt',    '孫 손자 손': 'grandchild',
  '學 배울 학': 'to learn',           '校 학교 교': 'school',
  '生 날 생': 'to be born',           '先 먼저 선': 'first, before',
  '醫 의원 의': 'healing, medicine',  '院 집 원': 'institution',
  '師 스승 사': 'master, teacher',    '藥 약 약': 'medicine',
  '局 판 국': 'bureau, office',       '銀 은 은': 'silver',
  '行 다닐 행': 'to circulate',       '郵 우편 우': 'post, mail',
  '遞 갈아탈 체': 'to relay',         '警 경계할 경': 'to guard, to warn',
  '察 살필 찰': 'to inspect',         '署 관청 서': 'government office',
  '消 사라질 소': 'to extinguish',    '防 막을 방': 'to prevent',
  '百 일백 백': 'hundred',            '貨 재물 화': 'goods',
  '店 가게 점': 'shop',               '圖 그림 도': 'picture, diagram',
  '書 글 서': 'writing, book',        '館 집 관': 'hall, building',
  '博 넓을 박': 'broad, extensive',   '物 물건 물': 'thing, object',
  '美 아름다울 미': 'beautiful',      '術 재주 술': 'art, technique',
  '公 공평할 공': 'public',           '園 동산 원': 'garden',
  '映 비칠 영': 'to project',         '畫 그림 화': 'picture',
  '容 얼굴 용': 'face, appearance',   '室 집 실': 'room',
  '地 땅 지': 'earth, ground',        '下 아래 하': 'below',
  '鐵 쇠 철': 'iron',                 '驛 역 역': 'station',
  '空 하늘 공': 'sky, empty',         '港 항구 항': 'harbour',
  '口 입 구': 'mouth, opening',       '駐 살 주': 'to station, to park',
  '車 수레 차': 'vehicle',            '場 마당 장': 'place, grounds',
  '食 먹을 식': 'to eat, food',       '堂 집 당': 'hall',
  '飲 마실 음': 'to drink',           '料 헤아릴 료': 'material, fee',
  '水 물 수': 'water',                '茶 차 다': 'tea',
  '饅 만두 만': 'steamed bun',        '頭 머리 두': 'head',
  '果 열매 과': 'fruit',              '實 열매 실': 'fruit, substance',
  '時 때 시': 'time',                 '間 사이 간': 'interval',
  '日 날 일': 'day, sun',             '字 글자 자': 'character',
  '週 돌 주': 'week, cycle',          '末 끝 말': 'end',
  '平 평평할 평': 'level, ordinary',  '正 바를 정': 'upright, exact',
  '午 낮 오': 'noon',                 '子 첫째지 자': 'first zodiac branch (midnight)',
  '季 계절 계': 'season',             '節 마디 절': 'node, section',
  '氣 기운 기': 'air, energy',        '溫 따뜻할 온': 'warm',
  '濕 축축할 습': 'damp',             '度 법도 도': 'degree, measure',
  '運 옮길 운': 'to move, to carry',  '動 움직일 동': 'to move',
  '文 글 문': 'writing, text',        '化 될 화': 'to transform',
  '餘 남을 여': 'surplus, spare',     '暇 겨레 가': 'leisure',
  '健 건강할 건': 'healthy',          '康 편안할 강': 'at ease, well',
  '症 증세 증': 'symptom',            '狀 형상 상': 'condition, form',
  '科 과목 과': 'branch, subject',    '目 눈 목': 'eye, item',
  '試 시험할 시': 'to test',          '驗 시험 험': 'examination',
  '職 직분 직': 'post, duty',         '業 업 업': 'occupation',
  '務 힘쓸 무': 'to strive, duty',    '課 매길 과': 'to assign, lesson',
  '題 제목 제': 'topic, title',       '住 살 주': 'to reside',
  '居 살 거': 'to dwell',             '家 집 가': 'house, family',
  '具 갖출 구': 'implement',          '環 고리 환': 'ring, circle',
  '境 지경 경': 'boundary, region',   '情 뜻 정': 'feeling, circumstance',
  '報 알릴 보': 'to report',          '通 통할 통': 'to pass through',
  '信 믿을 신': 'to trust, message',  '放 놓을 방': 'to release, to air',
  '送 보낼 송': 'to send',            '新 새 신': 'new',
  '聞 들을 문': 'to hear',            '禮 예도 예': 'courtesy, rite',
  '社 모임 사': 'association',        '會 모일 회': 'to gather',
  '制 제도 제': 'system, to regulate','問 물을 문': 'to ask',
  '金 돈 금': 'gold, money',          '融 녹을 융': 'to melt, to circulate',
  '經 지날 경': 'to pass, to manage', '濟 건널 제': 'to cross, to relieve',
  '費 쓸 비': 'to spend, expense',    '市 저자 시': 'market, city',
  '貿 무역할 무': 'to trade',         '易 바꿀 역': 'to exchange',
  '產 낳을 산': 'to produce',         '研 갈 연': 'to grind, to research',
  '究 구할 구': 'to investigate',     '技 재주 기': 'skill',
  '遺 남길 유': 'to leave behind',    '產 재산 산': 'property',
  '演 펼칠 연': 'to perform',         '藝 재주 예': 'art, craft',
  '判 판단할 판': 'to judge',         '斷 끊을 단': 'to cut off, to decide',
  '價 값 가': 'price',                '値 값 치': 'value',
  '基 터 기': 'foundation',           '準 평평할 준': 'standard',
  '概 대개 개': 'outline, general',   '念 생각 념': 'thought',
  '原 근본 원': 'origin, root',       '理 이치 리': 'principle',
  '政 정사 정': 'governance',         '治 다스릴 치': 'to govern',
  '府 관청 부': 'government office',  '法 법 법': 'law',
  '秩 차례 질': 'order, sequence',    '序 차례 서': 'order, sequence',
  '行 행할 행': 'to carry out',       '民 백성 민': 'people, citizen',
  '豫 먼저 예': 'beforehand',         '約 약속 약': 'promise',
  '注 대댈 주': 'to pour, to note',   '文 글자 문': 'character, writing',
  '計 셈할 계': 'to count',           '算 셈할 산': 'to calculate',
  '領 거둘 영': 'to receive',         '收 거둘 수': 'to collect',
  '證 증거 증': 'proof, certificate', '從 따를 종': 'to follow',
  '業 업무 업': 'work, business',     '員 인원 원': 'member, staff',
  '格 격식 격': 'form, standard',     '割 쪼갤 할': 'to split',
  '引 끌 인': 'to pull',              '決 결단할 결': 'to decide',
  '済 건널 제': 'to settle',          '現 나타날 현': 'to appear, present',
  '座 자리 좌': 'seat, account',      '移 옮길 이': 'to transfer',
  '替 바꿀 체': 'to substitute',      '購 살 구': 'to purchase',
  '買 살 매': 'to buy',               '販 팔 판': 'to vend',
  '賣 팔 매': 'to sell',              '節 아낄 절': 'to economize',
  '浪 물결 랑': 'wave, wasteful',     '無 없을 무': 'without, none',
  '東 동녘 동': 'east',               '西 서녘 서': 'west',
  '南 남녘 남': 'south',              '北 북녘 북': 'north',
  '中 가운데 중': 'middle',           '央 가운데 앙': 'centre',
  '手 손 수': 'hand',                 '段 단계 단': 'step, stage',
  '路 길 로': 'road',                 '線 줄 선': 'line',
  '換 바꿀 환': 'to exchange',        '乘 탈 승': 'to ride, to board',
  '由 까닭 유': 'reason, by way of',  '出 날 출': 'to exit',
  // Used only by the corrected 환불 entry below.
  '還 돌아올 환': 'to return',        '拂 떨칠 불': 'to pay out',
  // Used only by 신용카드.
  '用 쓸 용': 'to use',

  // ── Second curation pass ────────────────────────────────────────────────────
  // Roots chosen by cascade potential: each one below appears inside several compounds
  // in levels.json, so curating it lifts every compound containing it via sino-partial.
  '旅 나그네 려': 'traveller',        '自 스스로 자': 'self',
  '然 그럴 연': 'so, thus',           '由 말미암을 유': 'to arise from',
  '關 관계할 관': 'to connect',       '係 맬 계': 'to tie',
  '共 함께 공': 'together',           '鑑 거울 감': 'to examine',
  '賞 상줄 상': 'to appreciate',      '議 의논할 의': 'to deliberate',
  '儀 거동 의': 'rite, decorum',      '排 물리칠 배': 'to expel',
  '電 번개 전': 'electricity',        '話 말씀 화': 'speech',
  '失 잃을 실': 'to lose',            '策 꾀 책': 'scheme, policy',
  '景 볕 경': 'scene, prospect',      '態 모습 태': 'condition',
  '汚 더러울 오': 'to soil',          '染 물들일 염': 'to stain',
  '保 지킬 보': 'to preserve',        '護 도울 호': 'to guard',
  '候 기후 후': 'season, climate',
  '要 요긴할 요': 'essential',        '選 가릴 선': 'to select',
  '擧 들 거': 'to raise up',          '授 줄 수': 'to impart',
  '卒 마칠 졸': 'to finish',          '企 꾀할 기': 'to plan',
  '創 비롯할 창': 'to originate',     '成 이룰 성': 'to form',
  '語 말씀 어': 'word, speech',       '感 느낄 감': 'to feel',
  '滿 찰 만': 'full',                 '足 발 족': 'sufficient',
  '疏 소통할 소': 'distant, sparse',  '遠 멀 원': 'far',
  '興 일 흥': 'to arise, interest',   '味 맛 미': 'taste',
  '和 화할 화': 'harmony',            '製 지을 제': 'to manufacture',
  '造 지을 조': 'to build',           '析 쪼갤 석': 'to analyse',
  '變 변할 변': 'to change',          '危 위태할 위': 'danger',
  '機 틀 기': 'mechanism, juncture',  '代 대신할 대': 'generation, era',
  '結 맺을 결': 'to bind, conclude',  '論 논할 론': 'to argue',
  '體 몸 체': 'body, form',
  '連 이을 련': 'to link',            '續 이을 속': 'to continue',
  '對 대할 대': 'to face, oppose',    '照 비칠 조': 'to shine on, compare',
  '人 사람 인': 'person',             '分 나눌 분': 'to divide',
  // Used by the corrected 병원 entry.
  '病 병 병': 'illness',
  // 茶 carries two established Korean readings, 다 and 차. Both are listed so 차 is not
  // rendered as a 두음법칙 shift, which it is not.
  '茶 차 차': 'tea',
};

// ─────────────────────────────────────────────────────────────────────────────
// Curated word origins. Format: [hanja, [eumhun tokens...]] for pure Sino-Korean,
// or a descriptor object for native / mixed / loan words.
//
// Three entries are corrected relative to the old HANJA_MAP, which contained
// hanja that did not match its own breakdown:
//   무료   listed 免費 but decomposed 無 + 料   -> 無料 is correct
//   환불   listed the parts in reverse order    -> 還拂
//   계좌이체 listed 口座 (= 구좌, the obsolete term) -> 計座移替
// ─────────────────────────────────────────────────────────────────────────────
const SINO = {
  '형': ['兄', ['兄 형 형']],
  '부모': ['父母', ['父 아비 부', '母 어미 모']],
  '자녀': ['子女', ['子 아들 자', '女 딸 녀']],
  '친척': ['親戚', ['親 친할 친', '戚 겨레 척']],
  '삼촌': ['三寸', ['三 석 삼', '寸 마디 촌']],
  '이모': ['姨母', ['姨 이모 이', '母 어미 모']],
  '고모': ['姑母', ['姑 시어미 고', '母 어미 모']],
  '손자': ['孫子', ['孫 손자 손', '子 아들 자']],
  '손녀': ['孫女', ['孫 손자 손', '女 딸 녀']],
  '학교': ['學校', ['學 배울 학', '校 학교 교']],
  '학생': ['學生', ['學 배울 학', '生 날 생']],
  '선생님': ['先生', ['先 먼저 선', '生 날 생']],
  // Corrected: the original map had 醫院, which reads 의원 (a clinic, or an assembly member).
  // 병원 is 病院.
  '병원': ['病院', ['病 병 병', '院 집 원']],
  '의사': ['醫師', ['醫 의원 의', '師 스승 사']],
  '약국': ['藥局', ['藥 약 약', '局 판 국']],
  '은행': ['銀行', ['銀 은 은', '行 다닐 행']],
  '우체국': ['郵遞局', ['郵 우편 우', '遞 갈아탈 체', '局 판 국']],
  '경찰서': ['警察署', ['警 경계할 경', '察 살필 찰', '署 관청 서']],
  '소방서': ['消防署', ['消 사라질 소', '防 막을 방', '署 관청 서']],
  '백화점': ['百貨店', ['百 일백 백', '貨 재물 화', '店 가게 점']],
  '도서관': ['圖書館', ['圖 그림 도', '書 글 서', '館 집 관']],
  '박물관': ['博物館', ['博 넓을 박', '物 물건 물', '館 집 관']],
  '미술관': ['美術館', ['美 아름다울 미', '術 재주 술', '館 집 관']],
  '공원': ['公園', ['公 공평할 공', '園 동산 원']],
  '영화관': ['映畫館', ['映 비칠 영', '畫 그림 화', '館 집 관']],
  '미용실': ['美容室', ['美 아름다울 미', '容 얼굴 용', '室 집 실']],
  '지하철역': ['地下鐵驛', ['地 땅 지', '下 아래 하', '鐵 쇠 철', '驛 역 역']],
  '지하철': ['地下鐵', ['地 땅 지', '下 아래 하', '鐵 쇠 철']],
  '공항': ['空港', ['空 하늘 공', '港 항구 항']],
  '항구': ['港口', ['港 항구 항', '口 입 구']],
  '주차장': ['駐車場', ['駐 살 주', '車 수레 차', '場 마당 장']],
  '식당': ['食堂', ['食 먹을 식', '堂 집 당']],
  '음료수': ['飲料水', ['飲 마실 음', '料 헤아릴 료', '水 물 수']],
  '음식': ['飲食', ['飲 마실 음', '食 먹을 식']],
  '차': ['茶', ['茶 차 차']],   // dual reading 다/차; here it is 차
  '만두': ['饅頭', ['饅 만두 만', '頭 머리 두']],
  // 과일 is deliberately absent: the original map claimed 果實, which reads 과실, not 과일.
  // It is handled as a naturalised native form in NATIVE_NOTE instead.
  '시간': ['時間', ['時 때 시', '間 사이 간']],
  '일자': ['日字', ['日 날 일', '字 글자 자']],
  '주말': ['週末', ['週 돌 주', '末 끝 말']],
  '평일': ['平日', ['平 평평할 평', '日 날 일']],
  '정오': ['正午', ['正 바를 정', '午 낮 오']],
  '자정': ['子正', ['子 첫째지 자', '正 바를 정']],
  '계절': ['季節', ['季 계절 계', '節 마디 절']],
  '기온': ['氣溫', ['氣 기운 기', '溫 따뜻할 온']],
  '습도': ['濕度', ['濕 축축할 습', '度 법도 도']],
  '온도': ['溫度', ['溫 따뜻할 온', '度 법도 도']],
  '운동': ['運動', ['運 옮길 운', '動 움직일 동']],
  '문화': ['文化', ['文 글 문', '化 될 화']],
  '여가': ['餘暇', ['餘 남을 여', '暇 겨레 가']],
  '건강': ['健康', ['健 건강할 건', '康 편안할 강']],
  '증상': ['症狀', ['症 증세 증', '狀 형상 상']],
  '과목': ['科目', ['科 과목 과', '目 눈 목']],
  '시험': ['試驗', ['試 시험할 시', '驗 시험 험']],
  '직업': ['職業', ['職 직분 직', '業 업 업']],
  '업무': ['業務', ['業 업 업', '務 힘쓸 무']],
  '과제': ['課題', ['課 매길 과', '題 제목 제']],
  '주거': ['住居', ['住 살 주', '居 살 거']],
  '가구': ['家具', ['家 집 가', '具 갖출 구']],
  '환경': ['環境', ['環 고리 환', '境 지경 경']],
  '정보': ['情報', ['情 뜻 정', '報 알릴 보']],
  '통신': ['通信', ['通 통할 통', '信 믿을 신']],
  '방송': ['放送', ['放 놓을 방', '送 보낼 송']],
  '신문': ['新聞', ['新 새 신', '聞 들을 문']],
  '예절': ['禮節', ['禮 예도 예', '節 마디 절']],
  '사회': ['社會', ['社 모임 사', '會 모일 회']],
  '제도': ['制度', ['制 제도 제', '度 법도 도']],
  '문제': ['問題', ['問 물을 문', '題 제목 제']],
  '금융': ['金融', ['金 돈 금', '融 녹을 융']],
  '경제': ['經濟', ['經 지날 경', '濟 건널 제']],
  '소비': ['消費', ['消 사라질 소', '費 쓸 비']],
  '시장': ['市場', ['市 저자 시', '場 마당 장']],
  '무역': ['貿易', ['貿 무역할 무', '易 바꿀 역']],
  '산업': ['產業', ['產 낳을 산', '業 업 업']],
  '과학': ['科學', ['科 과목 과', '學 배울 학']],
  '연구': ['研究', ['研 갈 연', '究 구할 구']],
  '기술': ['技術', ['技 재주 기', '術 재주 술']],
  '유산': ['遺產', ['遺 남길 유', '產 재산 산']],
  '공연': ['公演', ['公 공평할 공', '演 펼칠 연']],
  '예술': ['藝術', ['藝 재주 예', '術 재주 술']],
  '문학': ['文學', ['文 글 문', '學 배울 학']],
  '판단': ['判斷', ['判 판단할 판', '斷 끊을 단']],
  '가치': ['價値', ['價 값 가', '値 값 치']],
  '기준': ['基準', ['基 터 기', '準 평평할 준']],
  '개념': ['概念', ['概 대개 개', '念 생각 념']],
  '원리': ['原理', ['原 근본 원', '理 이치 리']],
  '정치': ['政治', ['政 정사 정', '治 다스릴 치']],
  '정부': ['政府', ['政 정사 정', '府 관청 부']],
  '법': ['法', ['法 법 법']],
  '질서': ['秩序', ['秩 차례 질', '序 차례 서']],
  '행정': ['行政', ['行 행할 행', '政 정사 정']],
  '시민': ['市民', ['市 저자 시', '民 백성 민']],
  '예약': ['豫約', ['豫 먼저 예', '約 약속 약']],
  '주문': ['注文', ['注 대댈 주', '文 글자 문']],
  '계산': ['計算', ['計 셈할 계', '算 셈할 산']],
  '영수증': ['領收證', ['領 거둘 영', '收 거둘 수', '證 증거 증']],
  '종업원': ['從業員', ['從 따를 종', '業 업무 업', '員 인원 원']],
  '가격': ['價格', ['價 값 가', '格 격식 격']],
  '할인': ['割引', ['割 쪼갤 할', '引 끌 인']],
  '결제': ['決済', ['決 결단할 결', '済 건널 제']],
  '현금': ['現金', ['現 나타날 현', '金 돈 금']],
  '계좌이체': ['計座移替', ['計 셈할 계', '座 자리 좌', '移 옮길 이', '替 바꿀 체']],
  '환불': ['還拂', ['還 돌아올 환', '拂 떨칠 불']],
  '구매': ['購買', ['購 살 구', '買 살 매']],
  '판매': ['販賣', ['販 팔 판', '賣 팔 매']],
  '절약': ['節約', ['節 아낄 절', '約 약속 약']],
  '낭비': ['浪費', ['浪 물결 랑', '費 쓸 비']],
  '무료': ['無料', ['無 없을 무', '料 헤아릴 료']],
  '중앙': ['中央', ['中 가운데 중', '央 가운데 앙']],
  '수단': ['手段', ['手 손 수', '段 단계 단']],
  '요금': ['料金', ['料 헤아릴 료', '金 돈 금']],
  '노선': ['路線', ['路 길 로', '線 줄 선']],
  '환승': ['換乘', ['換 바꿀 환', '乘 탈 승']],
  '하차': ['下車', ['下 아래 하', '車 수레 차']],
  '승차': ['乘車', ['乘 탈 승', '車 수레 차']],
  '경유': ['經由', ['經 지날 경', '由 까닭 유']],
  '출구': ['出口', ['出 날 출', '口 입 구']],

  // ── Second curation pass ────────────────────────────────────────────────────
  // Selected by measuring which roots occur inside the most still-uncurated compounds
  // (see the cascade analysis in the commit message), not by working alphabetically.
  '여행': ['旅行', ['旅 나그네 려', '行 다닐 행']],
  '자연': ['自然', ['自 스스로 자', '然 그럴 연']],
  '자유': ['自由', ['自 스스로 자', '由 까닭 유']],
  '관계': ['關係', ['關 관계할 관', '係 맬 계']],
  '공공': ['公共', ['公 공평할 공', '共 함께 공']],
  '감상': ['鑑賞', ['鑑 거울 감', '賞 상줄 상']],
  '회의': ['會議', ['會 모일 회', '議 의논할 의']],
  '예의': ['禮儀', ['禮 예도 예', '儀 거동 의']],
  '배출': ['排出', ['排 물리칠 배', '出 날 출']],
  '전화': ['電話', ['電 번개 전', '話 말씀 화']],
  '실업': ['失業', ['失 잃을 실', '業 업 업']],
  '정책': ['政策', ['政 정사 정', '策 꾀 책']],
  '경기': ['景氣', ['景 볕 경', '氣 기운 기']],
  '생태': ['生態', ['生 날 생', '態 모습 태']],
  '오염': ['汚染', ['汚 더러울 오', '染 물들일 염']],
  '보호': ['保護', ['保 지킬 보', '護 도울 호']],
  '기후': ['氣候', ['氣 기운 기', '候 기후 후']],
  '현대': ['現代', ['現 나타날 현', '代 대신할 대']],
  '요약': ['要約', ['要 요긴할 요', '約 약속 약']],
  '선거': ['選擧', ['選 가릴 선', '擧 들 거']],
  '수업': ['授業', ['授 줄 수', '業 업 업']],
  '졸업': ['卒業', ['卒 마칠 졸', '業 업 업']],
  '기업': ['企業', ['企 꾀할 기', '業 업 업']],
  '창업': ['創業', ['創 비롯할 창', '業 업 업']],
  '성어': ['成語', ['成 이룰 성', '語 말씀 어']],
  '감동': ['感動', ['感 느낄 감', '動 움직일 동']],
  '만족': ['滿足', ['滿 찰 만', '足 발 족']],
  '인기': ['人氣', ['人 사람 인', '氣 기운 기']],
  '소원': ['疏遠', ['疏 소통할 소', '遠 멀 원']],
  '흥미': ['興味', ['興 일 흥', '味 맛 미']],
  '평화': ['平和', ['平 평평할 평', '和 화할 화']],
  '주민': ['住民', ['住 살 주', '民 백성 민']],
  '제조': ['製造', ['製 지을 제', '造 지을 조']],
  '분석': ['分析', ['分 나눌 분', '析 쪼갤 석']],
  '변화': ['變化', ['變 변할 변', '化 될 화']],
  '위기': ['危機', ['危 위태할 위', '機 틀 기']],
  '결론': ['結論', ['結 맺을 결', '論 논할 론']],
  '구체': ['具體', ['具 갖출 구', '體 몸 체']],
  '연속': ['連續', ['連 이을 련', '續 이을 속']],
  '대조': ['對照', ['對 대할 대', '照 비칠 조']],
};

// Sino-Korean root + native Korean suffix.
const MIXED = {
  '남동생': ['男', ['男 사내 남'], '동생'],
  '여동생': ['女', ['女 계집 녀'], '동생'],
  '동쪽': ['東', ['東 동녘 동'], '쪽'],
  '서쪽': ['西', ['西 서녘 서'], '쪽'],
  '남쪽': ['南', ['南 남녘 남'], '쪽'],
  '북쪽': ['北', ['北 북녘 북'], '쪽'],
};

// Sino-Korean root + English loanword.
const MIXED_LOAN = {
  '신용카드': ['信用', ['信 믿을 신', '用 쓸 용'], 'card'],
};

// Native Korean words with a note worth keeping (the rest just get o:'native').
const NATIVE_NOTE = {
  '과일': 'naturalised in Korean; related to the Sino-Korean 果實 (과실), but no longer read that way',
  '아버지': 'respectful term for one\'s father',
  '어머니': 'respectful term for one\'s mother',
  '할아버지': 'grandfather; also used for any elderly man',
  '할머니': 'grandmother; also used for any elderly woman',
};

const LOANWORDS = {
  '커피': 'coffee', '빵': 'pão (Portuguese, via Japanese)', '마트': 'mart',
  '버스': 'bus', '택시': 'taxi', '셔츠': 'shirt', '코트': 'coat',
  '점퍼': 'jumper', '스마트폰': 'smartphone', '인터넷': 'internet',
  'SNS': 'SNS (social networking service)', 'PD': 'PD (producer/director)',
  '뉴스': 'news', '드라마': 'drama', '라디오': 'radio', '텔레비전': 'television',
  '컴퓨터': 'computer', '이메일': 'e-mail', '블로그': 'blog', '스포츠': 'sports',
  '테니스': 'tennis', '골프': 'golf', '피자': 'pizza', '햄버거': 'hamburger',
  '아이스크림': 'ice cream', '초콜릿': 'chocolate', '케이크': 'cake',
  '샌드위치': 'sandwich', '콜라': 'cola', '사이다': 'cider', '맥주': 'beer',
  '위스키': 'whisky', '뷔페': 'buffet', '메뉴': 'menu', '호텔': 'hotel',
  '리조트': 'resort', '모텔': 'motel', '패션': 'fashion', '스타일': 'style',
  '디자인': 'design', '팀': 'team', '게이머': 'gamer', '게임': 'game',
  '데이터': 'data', '시스템': 'system', '네트워크': 'network', '사이트': 'site',
  '메시지': 'message', '세일': 'sale', '메뉴판': 'menu (board)', '카메라': 'camera',
  '샤워': 'shower', '샴푸': 'shampoo', '비누': 'soap (Portuguese sabão)',
  '티셔츠': 'T-shirt', '청바지': 'jeans', '슬리퍼': 'slipper', '넥타이': 'necktie',
  '와이셔츠': 'white shirt', '원피스': 'one-piece dress', '스커트': 'skirt',
  '재킷': 'jacket', '패딩': 'padding (padded coat)', '핸드폰': 'hand phone',
  '노트북': 'notebook (laptop)', '모니터': 'monitor', '키보드': 'keyboard',
  '마우스': 'mouse', '마이크': 'mic', '헤드폰': 'headphone', '이어폰': 'earphone',
  '스피커': 'speaker', '택배': 'parcel delivery', '서비스': 'service',
  '이벤트': 'event', '캠페인': 'campaign', '아이디어': 'idea', '스트레스': 'stress',
  '다이어트': 'diet', '비키니': 'bikini', '선글라스': 'sunglasses',
  '립스틱': 'lipstick', '파운데이션': 'foundation', '마스크': 'mask',
  '시즌': 'season', '매치': 'match', '골': 'goal', '패스': 'pass', '슛': 'shoot',
  '코치': 'coach', '매니저': 'manager', '프로': 'pro', '팬': 'fan',
  '콘서트': 'concert', '밴드': 'band', '아티스트': 'artist',
};

// Second curation pass. Words verified against levels.json rather than recalled: an
// earlier heuristic sweep flagged 수업 / 졸업 / 기업 / 실업 / 제조업 as loanwords purely
// because they end in 업, when all of them are Sino-Korean (授業, 卒業, 企業, 失業, 製造業).
Object.assign(LOANWORDS, {
  '오토바이': 'auto-bicycle (motorcycle)', '힐링': 'healing',
  '캐리어': 'carrier (suitcase)',          '게스트하우스': 'guest house',
  '앱': 'app',                             '애플리케이션': 'application',
  '웹사이트': 'website',                    '업로드': 'upload',
  '스트리밍': 'streaming',                  '데이터베이스': 'database',
  '바이러스': 'virus',                      '콘텐츠': 'contents',
  '미디어': 'media',                        '팟캐스트': 'podcast',
  '인플레이션': 'inflation',                '빅데이터': 'big data',
  '시뮬레이션': 'simulation',               '리모델링': 'remodeling',
  '인테리어': 'interior',                   '데이터': 'data',
  '센터': 'center',                         '프로그램': 'program',
  '프린팅': 'printing',                     '업사이클링': 'upcycling',
  '소셜 미디어': 'social media',            '스마트 시티': 'smart city',
});

// 맥주 and 택배 are Sino-Korean, not loanwords — the old list mis-tagged them.
delete LOANWORDS['맥주'];
delete LOANWORDS['택배'];

// Native Korean predicates. Listed explicitly rather than inferred from the ending, because
// several endings attach happily to Sino roots — 만족스럽다 is 滿足 + 스럽다 and 예의 바르다
// is 禮儀 + 바르다, so a blanket "-스럽다 means native" rule would mislabel them. The `note`
// records which native ending is doing the work.
const NATIVE_PREDICATES = {
  '일어나다': 'native verb stem in -나다 (to arise)',
  '만나다': 'native verb stem in -나다',
  '신나다': 'native verb stem in -나다 (spirit rising)',
  '화나다': '화 (anger) + native -나다',
  '짜증나다': '짜증 (irritation) + native -나다',
  '네모나다': '네모 (four corners) + native -나다',
  '세모나다': '세모 (three corners) + native -나다',
  '헤어지다': 'native verb stem in -지다',
  '기름지다': '기름 (oil) + native -지다',
  '건방지다': 'native adjective in -지다',
  '바쁘다': 'native adjective stem in -쁘다',
  '기쁘다': 'native adjective stem in -쁘다',
  '나쁘다': 'native adjective stem in -쁘다',
  '예쁘다': 'native adjective stem in -쁘다',
  '슬프다': 'native adjective stem in -프다',
  '배고프다': '배 (belly) + native -고프다',
  '더럽다': 'native adjective stem in -럽다',
  '부끄럽다': 'native adjective stem in -럽다',
  '부럽다': 'native adjective stem in -럽다',
  '싱겁다': 'native adjective stem in -겁다',
  '뜨겁다': 'native adjective stem in -겁다',
  '무겁다': 'native adjective stem in -겁다',
  '즐겁다': 'native adjective stem in -겁다',
  '배부르다': '배 (belly) + native 부르다 (to be full)',
  '목마르다': '목 (throat) + native 마르다 (to dry)',
  '마르다': 'native verb 마르다 (to dry, to thin)',
  '머무르다': 'native verb stem in -르다',
  '맛있다': '맛 (taste) + 있다 (to exist)',
  '맛없다': '맛 (taste) + 없다 (to not exist)',
  '재미있다': '재미 (fun) + 있다 (to exist)',
  '뉘우치다': 'native verb 뉘우치다',
  '챙기다': 'native verb 챙기다',
};

// Idioms. Native by construction, and worth a gloss because the literal reading is the point.
const IDIOMS = {
  '배가 아프다': 'literally "the belly hurts" — to be envious of someone else\'s good fortune',
  '어깨가 무겁다': 'literally "the shoulders are heavy" — to carry a weighty responsibility',
  '눈코 뜰 새 없이 바쁘다': 'literally "no time to open eyes or nose" — frantically busy',
  '귀를 기울이다': 'literally "to tilt the ear" — to listen closely',
  '뼈가 있다': 'literally "there is a bone in it" — a remark with a hidden barb',
  '가슴을 치다': 'literally "to strike the chest" — to beat one\'s breast in grief',
  '눈이 높다': 'literally "the eyes are high" — to have exacting standards',
  '콧대가 높다': 'literally "the bridge of the nose is high" — haughty',
  '가슴이 치밀다': 'literally "the chest surges" — emotion welling up',
  '길을 찾다': 'literally "to look for the road" — to find one\'s way',
  '길을 잃다': 'literally "to lose the road" — to get lost',
  '눈길을 끌다': 'literally "to pull the gaze" — to catch the eye',
};

// Discourse connectives, all native Korean constructions.
const DISCOURSE = {
  '그러므로': 'native connective — 그러하다 + -므로 (because it is so)',
  '따라서': 'native connective — 따르다 (to follow) + -아서',
  '이에따라': 'native connective — 이에 (to this) + 따라 (following)',
  '잇따라': 'native connective — 잇다 (to join) + 따라',
  '왜냐하면': 'native connective — 왜 (why) + -냐 하면 (if one asks)',
  '그럼에도 불구하고': 'native + Sino — 그럼에도 (even so) + 不拘하고 (without regard)',
  '한편': 'native/Sino — 한 (one) + 便 (side)',
  '한편으로는': '한편 (one side) + -으로는 (as for)',
  '다른 한편으로는': '다른 (other) + 한편 + -으로는',
  '바꾸어 말하면': 'native — 바꾸다 (to change) + 말하다 (to say) + -면',
  '말하자면': 'native — 말하다 + -자면 (if one is to say)',
  '들자면': 'native — 들다 (to raise, cite) + -자면',
  '비유하자면': '比喩 (analogy) + 하자면',
  '정리하자면': '整理 (to order) + 하자면',
  '요약하자면': '要約 (to summarise) + 하자면',
  '요약하건대': '要約 + -하건대 (in so summarising)',
  '다음으로': 'native — 다음 (next) + -으로',
  '끝으로': 'native — 끝 (end) + -으로',
  '다음주': 'native 다음 (next) + 週 (week)',
  '다음달': 'native 다음 (next) + 달 (month)',
  '드디어': 'native adverb 드디어 (at last)',
  '도리어': 'native adverb 도리어 (on the contrary)',
};

// Multi-syllable loanwords that appear inside compounds, longest first, so a compound such
// as 데이터 센터 can be recognised from its parts the way sino-partial handles hanja roots.
const LOAN_ROOTS_BY_LEN = Object.keys(LOANWORDS)
  .filter(k => k.length >= 2)
  .sort((a, b) => b.length - a.length);

// ─────────────────────────────────────────────────────────────────────────────

function eumhun(tokens) {
  return tokens.map(t => {
    const en = EUMHUN_EN[t];
    if (!en) { throw new Error(`Missing English gloss for eumhun token: "${t}"`); }
    const [char, , reading] = t.split(' ');
    return [char, reading, en];
  });
}

// 두음법칙 — the initial-sound rule. Word-initial ㄹ and ㄴ shift in Sino-Korean, so 旅 (려)
// surfaces as 여 in 여행 and 路 (로) as 노 in 노선. Showing only the dictionary reading looks
// like a typo next to the word on screen; showing only the surface form hides the rule. So
// where they differ the reading becomes "려 → 여", which teaches it.
//
// Applied by position, and only for a word whose syllable count matches its hanja count —
// otherwise there is no reliable syllable-to-character alignment to compare against.
function markInitialSoundRule(ko, parts) {
  if (!parts || parts.length !== ko.length) return parts;
  return parts.map((p, i) => (p[1] === ko[i] ? p : [p[0], `${p[1]} → ${ko[i]}`, p[2]]));
}

// Derivational suffixes that attach to a Sino-Korean root without changing it.
// 건강하다 -> 건강 (健康) + 하다, so the curated hanja for the root still applies.
// Ordered longest-first so 시키다 wins over 다.
const DERIV_SUFFIXES = [
  ['시키다', 'sino-passive'], ['스럽다', 'sino-adj'], ['롭다', 'sino-adj'],
  ['하다', 'sino-verb'],      ['되다', 'sino-passive'],
  ['적이다', 'sino-adj'],     ['적', 'sino-adj'],
];

// Curated Sino roots of 2+ syllables, longest first, for compound matching.
const SINO_ROOTS_BY_LEN = Object.keys(SINO)
  .filter(k => k.length >= 2)
  .sort((a, b) => b.length - a.length);

function classify(ko) {
  if (SINO[ko])        { const [h, t] = SINO[ko];              return { o: 'sino', h, p: markInitialSoundRule(ko, eumhun(t)) }; }
  if (MIXED[ko])       { const [h, t, n] = MIXED[ko];          return { o: 'mixed', h, p: eumhun(t), n }; }
  if (MIXED_LOAN[ko])  { const [h, t, l] = MIXED_LOAN[ko];     return { o: 'mixed-loan', h, p: eumhun(t), l }; }
  if (LOANWORDS[ko])   { return { o: 'loan', l: LOANWORDS[ko] }; }
  if (NATIVE_NOTE[ko]) { return { o: 'native', note: NATIVE_NOTE[ko] }; }
  if (IDIOMS[ko])      { return { o: 'idiom', note: IDIOMS[ko] }; }
  if (DISCOURSE[ko])   { return { o: 'discourse', note: DISCOURSE[ko] }; }
  if (NATIVE_PREDICATES[ko]) { return { o: 'native', note: NATIVE_PREDICATES[ko] }; }

  // A curated Sino root carrying a derivational suffix keeps its hanja.
  for (const [suf, kind] of DERIV_SUFFIXES) {
    if (!ko.endsWith(suf)) continue;
    const root = ko.slice(0, -suf.length);
    if (SINO[root]) {
      const [h, t] = SINO[root];
      return { o: kind, h, p: eumhun(t), s: suf };
    }
    if (LOANWORDS[root]) return { o: 'loan', l: LOANWORDS[root], s: suf };
  }

  // Compounds built on curated Sino roots: 건강검진 contains 건강 (健康), so the word
  // is certainly Sino-Korean even though we only know part of the hanja. Scans
  // left to right taking the longest root at each position, so 중앙도서관 yields
  // both 中央 and 圖書館.
  //
  // Restricted to roots of 2+ syllables — a single Hangul syllable maps to many
  // characters (차 = 茶 / 車 / 差 / 次), so one-syllable matching would emit wrong
  // etymology. Emitted as `sino-partial`; `k` lists the parts we can vouch for.
  const found = [];
  for (let i = 0; i < ko.length; ) {
    const root = SINO_ROOTS_BY_LEN.find(r => ko.startsWith(r, i));
    if (root) { found.push(root); i += root.length; } else { i++; }
  }
  if (found.length) {
    return {
      o: 'sino-partial',
      h: found.map(r => SINO[r][0]).join(''),
      p: found.flatMap(r => eumhun(SINO[r][1])),
      k: found,
    };
  }

  // Same idea for loanwords: 데이터 센터 is 데이터 + 센터, 백신 프로그램 is a Sino root we do
  // not have plus 프로그램. Multi-syllable only, for the same ambiguity reason. The scan
  // skips any position that matches nothing, so a word-space between parts costs nothing.
  const loanParts = [];
  for (let i = 0; i < ko.length; ) {
    const r = LOAN_ROOTS_BY_LEN.find(x => ko.startsWith(x, i));
    if (r) { loanParts.push(r); i += r.length; } else { i++; }
  }
  if (loanParts.length) {
    return { o: 'loan-partial', l: loanParts.map(r => LOANWORDS[r]).join(' + '), k: loanParts };
  }

  // Suffix heuristics for Sino-Korean words we have no curated hanja for.
  if (ko.endsWith('하다') && ko.length >= 4)            return { o: 'sino-verb' };
  if (ko.endsWith('되다') || ko.endsWith('시키다'))      return { o: 'sino-passive' };
  if (ko.endsWith('적'))                                 return { o: 'sino-adj' };
  if (/[성력감]$/.test(ko))                              return { o: 'sino-noun' };

  // Honest default. The old VOCAB_FACTS claimed "고유어 (Native Korean word)" for
  // 1090 words with no evidence, which mislabels plenty of Sino-Korean vocabulary
  // (건강검진, 환경오염, 기술혁신 …). Unknown stays unknown; the UI shows
  // pronunciation and syllable structure instead of asserting an origin.
  return { o: 'unknown' };
}

// ── Build ────────────────────────────────────────────────────────────────────
const facts = {};
const stats = {};
let total = 0;

for (const level of levelsData) {
  for (const w of (level.words || [])) {
    const ko = (w.ko || '').normalize('NFC');
    if (!ko) continue;
    total++;
    if (facts[ko]) continue;           // levels.json has 1500 unique ko, but be safe
    const f = classify(ko);
    facts[ko] = f;
    stats[f.o] = (stats[f.o] || 0) + 1;
  }
}

// ── Guard: whole-word curation must still match a real headword ──────────────
//
// These six maps are keyed on complete words, unlike SINO and LOANWORDS which also hold
// bare roots for compound matching. So a key here that matches nothing in levels.json is
// dead curation — the usual cause is a headword being respelled (the 띄어쓰기 pass moved
// 어깨가무겁다 to 어깨가 무겁다) and the map not being updated with it. The word silently
// falls back to `unknown` and coverage drops with nothing to point at.
const WHOLE_WORD_MAPS = {
  MIXED, MIXED_LOAN, NATIVE_NOTE, IDIOMS, DISCOURSE, NATIVE_PREDICATES,
};
const headwords = new Set(
  levelsData.flatMap(l => (l.words || []).map(w => (w.ko || '').normalize('NFC')))
);
const orphaned = Object.entries(WHOLE_WORD_MAPS).flatMap(([name, map]) =>
  Object.keys(map).filter(k => !headwords.has(k.normalize('NFC'))).map(k => `${name}['${k}']`)
);
if (orphaned.length) {
  console.error('\nERROR: curated entries that match no word in levels.json:');
  orphaned.forEach(o => console.error(`  ${o}`));
  console.error('Either the headword was respelled, or the entry is stale. Fix, then re-run.');
  process.exit(1);
}

// ── Guard: every emitted origin class must be renderable by the game ─────────
//
// renderOrigin() in game.js is a switch with a `default: return ''`, so introducing a new
// origin class here and forgetting to add a case there silently produces entries that are
// curated but display nothing. That happened once already with idiom / discourse /
// loan-partial, so the generator now refuses to emit a class game.js cannot render.
const gameJs = fs.readFileSync(path.join(ROOT, 'game.js'), 'utf8');
const renderOriginBody = gameJs.slice(
  gameJs.indexOf('function renderOrigin('),
  gameJs.indexOf('function renderStructure(')
);
const renderable = new Set(
  [...renderOriginBody.matchAll(/case '([a-z-]+)':/g)].map(m => m[1]).concat('unknown')
);
const unrenderable = Object.keys(stats).filter(o => !renderable.has(o));
if (unrenderable.length) {
  console.error('\nERROR: these origin classes have no case in game.js renderOrigin():');
  unrenderable.forEach(o => console.error(`  ${o} (${stats[o]} words would show no origin)`));
  console.error('Add a case for each in renderOrigin(), then re-run.');
  process.exit(1);
}

const out = path.join(ROOT, 'facts.json');
fs.writeFileSync(out, JSON.stringify(facts), 'utf8');
// Mirror into assets/, which main.py serves from and admin/lib/sync.js keeps in step.
const assetsFacts = path.join(ROOT, 'assets', 'facts.json');
if (fs.existsSync(path.dirname(assetsFacts))) fs.copyFileSync(out, assetsFacts);

const kb = (fs.statSync(out).size / 1024).toFixed(1);
console.log(`facts.json written: ${Object.keys(facts).length} entries from ${total} words, ${kb} KB`);
console.log('Origin breakdown:');
const curated = total - (stats.unknown || 0);
Object.entries(stats).sort((a, b) => b[1] - a[1])
  .forEach(([k, v]) => console.log(`  ${k.padEnd(13)} ${String(v).padStart(5)}`));
console.log(`\nCoverage: ${curated}/${total} curated (${(curated / total * 100).toFixed(1)}%), ` +
            `${Object.values(facts).filter(f => f.h).length} with hanja`);
console.log(`All ${Object.keys(stats).length} origin classes are renderable by game.js ✓`);
