/**
 * build_facts_json.js — generates facts.json (English) from levels.json
 *
 * Replaces the old scripts/build_vocab_facts.js, which inlined an 803 KB
 * `VOCAB_FACTS` literal into game.js. That data was 99.7% templated filler:
 * every entry shared the same closing sentence and the same mnemonic scaffold,
 * and the "example sentences" were generated by string concatenation and were
 * frequently ungrammatical (e.g. 먹다 -> "매일 한국어로 먹며 연습합니다").
 *
 * This script keeps only the signal that cannot be derived at runtime — the
 * curated word origin (hanja breakdown / loanword source / native) — and emits
 * it as structured data. Romanization, syllable count and batchim are computed
 * from the Hangul itself in getFunFact(), so they are deliberately NOT stored.
 *
 * Output schema, keyed by word.ko (all 1500 are unique):
 *   { o: 'native' }
 *   { o: 'sino',       h: '父母', p: [['父','부','father'], ['母','모','mother']] }
 *   { o: 'mixed',      h: '男',   p: [['男','남','male']], n: '동생' }
 *   { o: 'mixed-loan', h: '信用', p: [...], l: 'card' }
 *   { o: 'loan',       l: 'coffee' }
 *   { o: 'sino-verb' | 'sino-passive' | 'sino-adj' | 'sino-noun' }
 *
 * Run:  node scripts/build_facts_json.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const levelsData = JSON.parse(fs.readFileSync(path.join(ROOT, 'levels.json'), 'utf8'));

// ─────────────────────────────────────────────────────────────────────────────
// Hanja eumhun (音訓) glosses, translated to English.
// Keyed by the full "<hanja> <korean-meaning> <korean-reading>" token because
// the same character carries different glosses in different compounds
// (子 아들 "son" vs 子 첫째지 "first branch"; 行 다닐 "to go" vs 行 행할 "to carry out").
// ─────────────────────────────────────────────────────────────────────────────
const EUMHUN_EN = {
  '兄 형 형': 'elder brother',        '男 사내 남': 'male',
  '女 계집 녀': 'female',             '父 아비 부': 'father',
  '母 어미 모': 'mother',             '子 아들 자': 'son',
  '女 딸 녀': 'daughter',             '親 친할 친': 'close, intimate',
  '戚 겨레 척': 'kin',                '三 석 삼': 'three',
  '寸 마디 촌': 'degree of kinship',  '姨 이모 이': 'maternal aunt',
  '姑 시어미 고': 'paternal aunt',    '孫 손자 손': 'grandchild',
  '學 배울 학': 'to learn',           '校 학교 교': 'school',
  '生 날 생': 'to be born',           '先 먼저 선': 'first, before',
  '醫 의원 의': 'healing, medicine',  '院 집 원': 'institution',
  '師 스승 사': 'master, teacher',    '藥 약 약': 'medicine',
  '局 판 국': 'bureau, office',       '銀 은 은': 'silver',
  '行 다닐 행': 'to circulate',       '郵 우편 우': 'post, mail',
  '遞 갈아탈 체': 'to relay',         '警 경계할 경': 'to guard, to warn',
  '察 살필 찰': 'to inspect',         '署 관청 서': 'government office',
  '消 사라질 소': 'to extinguish',    '防 막을 방': 'to prevent',
  '百 일백 백': 'hundred',            '貨 재물 화': 'goods',
  '店 가게 점': 'shop',               '圖 그림 도': 'picture, diagram',
  '書 글 서': 'writing, book',        '館 집 관': 'hall, building',
  '博 넓을 박': 'broad, extensive',   '物 물건 물': 'thing, object',
  '美 아름다울 미': 'beautiful',      '術 재주 술': 'art, technique',
  '公 공평할 공': 'public',           '園 동산 원': 'garden',
  '映 비칠 영': 'to project',         '畫 그림 화': 'picture',
  '容 얼굴 용': 'face, appearance',   '室 집 실': 'room',
  '地 땅 지': 'earth, ground',        '下 아래 하': 'below',
  '鐵 쇠 철': 'iron',                 '驛 역 역': 'station',
  '空 하늘 공': 'sky, empty',         '港 항구 항': 'harbour',
  '口 입 구': 'mouth, opening',       '駐 살 주': 'to station, to park',
  '車 수레 차': 'vehicle',            '場 마당 장': 'place, grounds',
  '食 먹을 식': 'to eat, food',       '堂 집 당': 'hall',
  '飲 마실 음': 'to drink',           '料 헤아릴 료': 'material, fee',
  '水 물 수': 'water',                '茶 차 다': 'tea',
  '饅 만두 만': 'steamed bun',        '頭 머리 두': 'head',
  '果 열매 과': 'fruit',              '實 열매 실': 'fruit, substance',
  '時 때 시': 'time',                 '間 사이 간': 'interval',
  '日 날 일': 'day, sun',             '字 글자 자': 'character',
  '週 돌 주': 'week, cycle',          '末 끝 말': 'end',
  '平 평평할 평': 'level, ordinary',  '正 바를 정': 'upright, exact',
  '午 낮 오': 'noon',                 '子 첫째지 자': 'first zodiac branch (midnight)',
  '季 계절 계': 'season',             '節 마디 절': 'node, section',
  '氣 기운 기': 'air, energy',        '溫 따뜻할 온': 'warm',
  '濕 축축할 습': 'damp',             '度 법도 도': 'degree, measure',
  '運 옮길 운': 'to move, to carry',  '動 움직일 동': 'to move',
  '文 글 문': 'writing, text',        '化 될 화': 'to transform',
  '餘 남을 여': 'surplus, spare',     '暇 겨레 가': 'leisure',
  '健 건강할 건': 'healthy',          '康 편안할 강': 'at ease, well',
  '症 증세 증': 'symptom',            '狀 형상 상': 'condition, form',
  '科 과목 과': 'branch, subject',    '目 눈 목': 'eye, item',
  '試 시험할 시': 'to test',          '驗 시험 험': 'examination',
  '職 직분 직': 'post, duty',         '業 업 업': 'occupation',
  '務 힘쓸 무': 'to strive, duty',    '課 매길 과': 'to assign, lesson',
  '題 제목 제': 'topic, title',       '住 살 주': 'to reside',
  '居 살 거': 'to dwell',             '家 집 가': 'house, family',
  '具 갖출 구': 'implement',          '環 고리 환': 'ring, circle',
  '境 지경 경': 'boundary, region',   '情 뜻 정': 'feeling, circumstance',
  '報 알릴 보': 'to report',          '通 통할 통': 'to pass through',
  '信 믿을 신': 'to trust, message',  '放 놓을 방': 'to release, to air',
  '送 보낼 송': 'to send',            '新 새 신': 'new',
  '聞 들을 문': 'to hear',            '禮 예도 예': 'courtesy, rite',
  '社 모임 사': 'association',        '會 모일 회': 'to gather',
  '制 제도 제': 'system, to regulate','問 물을 문': 'to ask',
  '金 돈 금': 'gold, money',          '融 녹을 융': 'to melt, to circulate',
  '經 지날 경': 'to pass, to manage', '濟 건널 제': 'to cross, to relieve',
  '費 쓸 비': 'to spend, expense',    '市 저자 시': 'market, city',
  '貿 무역할 무': 'to trade',         '易 바꿀 역': 'to exchange',
  '產 낳을 산': 'to produce',         '研 갈 연': 'to grind, to research',
  '究 구할 구': 'to investigate',     '技 재주 기': 'skill',
  '遺 남길 유': 'to leave behind',    '產 재산 산': 'property',
  '演 펼칠 연': 'to perform',         '藝 재주 예': 'art, craft',
  '判 판단할 판': 'to judge',         '斷 끊을 단': 'to cut off, to decide',
  '價 값 가': 'price',                '値 값 치': 'value',
  '基 터 기': 'foundation',           '準 평평할 준': 'standard',
  '概 대개 개': 'outline, general',   '念 생각 념': 'thought',
  '原 근본 원': 'origin, root',       '理 이치 리': 'principle',
  '政 정사 정': 'governance',         '治 다스릴 치': 'to govern',
  '府 관청 부': 'government office',  '法 법 법': 'law',
  '秩 차례 질': 'order, sequence',    '序 차례 서': 'order, sequence',
  '行 행할 행': 'to carry out',       '民 백성 민': 'people, citizen',
  '豫 먼저 예': 'beforehand',         '約 약속 약': 'promise',
  '注 대댈 주': 'to pour, to note',   '文 글자 문': 'character, writing',
  '計 셈할 계': 'to count',           '算 셈할 산': 'to calculate',
  '領 거둘 영': 'to receive',         '收 거둘 수': 'to collect',
  '證 증거 증': 'proof, certificate', '從 따를 종': 'to follow',
  '業 업무 업': 'work, business',     '員 인원 원': 'member, staff',
  '格 격식 격': 'form, standard',     '割 쪼갤 할': 'to split',
  '引 끌 인': 'to pull',              '決 결단할 결': 'to decide',
  '済 건널 제': 'to settle',          '現 나타날 현': 'to appear, present',
  '座 자리 좌': 'seat, account',      '移 옮길 이': 'to transfer',
  '替 바꿀 체': 'to substitute',      '購 살 구': 'to purchase',
  '買 살 매': 'to buy',               '販 팔 판': 'to vend',
  '賣 팔 매': 'to sell',              '節 아낄 절': 'to economize',
  '浪 물결 랑': 'wave, wasteful',     '無 없을 무': 'without, none',
  '東 동녘 동': 'east',               '西 서녘 서': 'west',
  '南 남녘 남': 'south',              '北 북녘 북': 'north',
  '中 가운데 중': 'middle',           '央 가운데 앙': 'centre',
  '手 손 수': 'hand',                 '段 단계 단': 'step, stage',
  '路 길 로': 'road',                 '線 줄 선': 'line',
  '換 바꿀 환': 'to exchange',        '乘 탈 승': 'to ride, to board',
  '由 까닭 유': 'reason, by way of',  '出 날 출': 'to exit',
  // Used only by the corrected 환불 entry below.
  '還 돌아올 환': 'to return',        '拂 떨칠 불': 'to pay out',
  // Used only by 신용카드.
  '用 쓸 용': 'to use',

  // ── Added by the third curation pass ──────────────────────────────────────
  // Body, illness and symptoms.
  '內 안 내': 'inside',               '臟 오장 장': 'internal organ',
  '心 마음 심': 'heart, mind',        '肺 허파 폐': 'lung',
  '痛 아플 통': 'to ache',            '齒 이 치': 'tooth',
  '腹 배 복': 'belly',                '熱 더울 열': 'hot, fever',
  '泄 샐 설': 'to leak',              '瀉 쏟을 사': 'to pour out',
  '便 똥오줌 변': 'bodily waste',      '祕 숨길 비': 'to conceal, to block',
  '傷 다칠 상': 'to be hurt',         '處 곳 처': 'place',
  '骨 뼈 골': 'bone',                 '折 꺾을 절': 'to break, to snap',
  '炎 불꽃 염': 'flame, inflammation', '皮 가죽 피': 'skin, hide',
  '膚 살갗 부': 'skin surface',
  '不 아닐 불': 'not',                '良 좋을 량': 'good',
  // Weather.
  '颱 태풍 태': 'typhoon',            '風 바람 풍': 'wind',
  '暴 사나울 폭': 'violent, sudden',   '雪 눈 설': 'snow',
  '寒 찰 한': 'cold',                 '波 물결 파': 'wave',
  '較 견줄 교': 'to compare',         '差 다를 차': 'difference',
  '冷 찰 랭': 'cold',
  // Time.
  '來 올 래': 'to come',              '年 해 년': 'year',
  '昨 어제 작': 'yesterday',          '點 점 점': 'point, dot',
  // Food and objects.
  '飯 밥 반': 'cooked rice',          '饌 반찬 찬': 'side dish',
  '麵 국수 면': 'noodles',            '粥 죽 죽': 'porridge',
  '洋 큰바다 양': 'ocean, Western',    '襪 버선 말': 'sock',
  '帽 모자 모': 'hat',                '掌 손바닥 장': 'palm of the hand',
  '匣 갑 갑': 'case, box',            '紙 종이 지': 'paper',
  '眼 눈 안': 'eye',                  '鏡 거울 경': 'mirror, lens',
  '粧 단장할 장': 'to adorn',          '品 물건 품': 'article, goods',
  // Appearance and manner.
  '童 아이 동': 'child',              '顔 얼굴 안': 'face',
  '老 늙을 로': 'old',                '軀 몸 구': 'body, frame',
  '型 모형 형': 'form, type',         '耳 귀 이': 'ear',
  '鼻 코 비': 'nose',                 '印 도장 인': 'seal, imprint',
  '象 코끼리 상': 'elephant, image',
  '恒 항상 항': 'constant',           '常 떳떳할 상': 'ordinary, always',
  // Direction.
  '直 곧을 직': 'straight',           '進 나아갈 진': 'to advance',

  // Law and order.
  '憲 법 헌': 'constitution',         '裁 마를 재': 'to judge, to cut',
  '事 일 사': 'affair, matter',       '檢 검사할 검': 'to examine',
  '辯 말잘할 변': 'to argue, to plead', '士 선비 사': 'scholar, professional',
  '被 입을 피': 'to receive, passive',  '告 알릴 고': 'to tell, to accuse',
  '訴 호소할 소': 'to appeal',         '訟 송사할 송': 'to litigate',
  '合 합할 합': 'to join, lawful',     '刑 형벌 형': 'punishment',
  '嫌 싫어할 혐': 'to dislike, suspicion', '疑 의심할 의': 'to doubt',
  '據 근거 거': 'grounds, basis',      '懲 징계할 징': 'to discipline',
  '役 부릴 역': 'labour, service',     '罰 벌할 벌': 'to punish',
  '司 맡을 사': 'to take charge',      '安 편안 안': 'peace, safety',
  // Finance.
  '券 문서 권': 'certificate',         '株 그루 주': 'stock, share',
  '式 법 식': 'form, formula',         '投 던질 투': 'to throw, to invest',
  '資 재물 자': 'resources, capital',   '貯 쌓을 저': 'to store up',
  '蓄 모을 축': 'to accumulate',       '預 맡길 예': 'to entrust, to deposit',
  '積 쌓을 적': 'to pile up',          '貸 빌릴 대': 'to lend',
  '利 이로울 리': 'benefit, interest',  '率 비율 률': 'rate, ratio',
  '潤 불을 윤': 'to enrich, profit',    '損 덜 손': 'to lose, to damage',
  '赤 붉을 적': 'red',                 '黑 검을 흑': 'black',
  '本 근본 본': 'root, principal',
  // School.
  '敎 가르칠 교': 'to teach',          '講 익힐 강': 'to lecture',
  '義 옳을 의': 'righteous, meaning',   '育 기를 육': 'to raise, to educate',
  '寄 부칠 기': 'to lodge, to send',    '宿 잘 숙': 'to lodge overnight',
  '舍 집 사': 'quarters, building',     '國 나라 국': 'country',
  '英 꽃부리 영': 'flower, England',    '數 셈 수': 'number',
  '韓 한국 한': 'Korea',               '史 사기 사': 'history',
  '音 소리 음': 'sound',               '樂 노래 악': 'music',
  '助 도울 조': 'to assist',
  // Classes and exams.
  '席 자리 석': 'seat',                '缺 이지러질 결': 'to lack, to be absent',
  '遲 늦을 지': 'late',                '刻 새길 각': 'to carve, moment',
  '考 상고할 고': 'to examine, to test', '査 조사할 사': 'to investigate',
  '期 기약할 기': 'period, term',       '奬 장려할 장': 'to encourage, to award',
  '入 들 입': 'to enter',              '績 길쌈할 적': 'achievement, record',
  '表 겉 표': 'surface, table',         '位 자리 위': 'position, rank',
  // Jobs and departments.
  '長 긴 장': 'long, chief',           '部 떼 부': 'division, department',
  '次 버금 차': 'next, second',        '組 짤 조': 'to organize, group',
  '織 짤 직': 'to weave',              '劃 그을 획': 'to draw, to plan',
  '營 경영할 영': 'to manage',          '總 다 총': 'all, general',
  '財 재물 재': 'wealth',              '開 열 개': 'to open',
  '發 필 발': 'to issue, to develop',
  // ── Fourth curation pass: 사자성어 ───────────────────────────────────────
  // Four-character idioms are Sino-Korean by construction, and the literal reading is the
  // point of learning them — 청출어람 only makes sense once you can see 靑 出 於 藍.
  '一 한 일': 'one',                   '二 두 이': 'two',
  '三 석 삼': 'three',                 '七 일곱 칠': 'seven',
  '八 여덟 팔': 'eight',               '十 열 십': 'ten',
  '石 돌 석': 'stone',                 '鳥 새 조': 'bird',
  '兩 두 량': 'both, two',             '得 얻을 득': 'to gain',
  '答 대답할 답': 'to answer',          '深 깊을 심': 'deep',
  '思 생각 사': 'to think',            '熟 익을 숙': 'ripe, thorough',
  '作 지을 작': 'to make',             '苦 쓸 고': 'bitter, hardship',
  '盡 다할 진': 'to exhaust',          '甘 달 감': 'sweet',
  '有 있을 유': 'to have',             '言 말씀 언': 'word, speech',
  '匙 숟가락 시': 'spoon',             '同 한가지 동': 'same',
  '相 서로 상': 'each other',          '憐 불쌍히여길 련': 'to pity',
  '顚 엎드러질 전': 'to topple',        '起 일어날 기': 'to rise',
  '此 이 차': 'this',                  '彼 저 피': 'that',
  '過 지날 과': 'to exceed',           '猶 오히려 유': 'still, rather',
  '及 미칠 급': 'to reach',            '靑 푸를 청': 'blue, green',
  '於 어조사 어': 'from, at',           '藍 쪽 람': 'indigo plant',
  '必 반드시 필': 'necessarily',        '歸 돌아갈 귀': 'to return',
  '初 처음 초': 'beginning',           '志 뜻 지': 'will, intent',
  '貫 꿸 관': 'to pierce, to run through', '錦 비단 금': 'brocade',
  '上 윗 상': 'above, upon',           '添 더할 첨': 'to add',
  '花 꽃 화': 'flower',                '加 더할 가': 'to add',
  '霜 서리 상': 'frost',               '備 갖출 비': 'to prepare',
  '以 써 이': 'by means of',           '傳 전할 전': 'to transmit',
  '主 주인 주': 'host, master',        '客 손 객': 'guest',
  '倒 넘어질 도': 'to invert',          '床 평상 상': 'bed, couch',
  '異 다를 이': 'different',           '夢 꿈 몽': 'dream',
  '俗 풍속 속': 'custom, common',       '談 말씀 담': 'talk',

  // Politics and government.
  '大 큰 대': 'great, large',          '統 거느릴 통': 'to unify, to govern',
  '領 거느릴 령': 'to lead, collar',    '黨 무리 당': 'party, faction',
  '票 표 표': 'ticket, vote',          '與 더불 여': 'to give, to take part',
  '野 들 야': 'field, out of power',    '立 설 립': 'to stand, to establish',
  '權 권세 권': 'authority, right',      '共 한가지 공': 'together, shared',
  '監 볼 감': 'to oversee, to audit',
  // Science and research.
  '實 열매 실': 'fruit, actual',        '假 거짓 가': 'false, provisional',
  '說 말씀 설': 'to explain, theory',    '見 볼 견': 'to see',
  '明 밝을 명': 'bright, clear',        '特 특별할 특': 'special',
  '許 허락할 허': 'to permit',          '觀 볼 관': 'to observe',
  '測 헤아릴 측': 'to measure',         '工 장인 공': 'craft, engineering',
  // Academic terms.
  '反 돌이킬 반': 'to reverse, counter', '形 모양 형': 'shape',
  '類 무리 류': 'kind, category',       '多 많을 다': 'many',
  '源 근원 원': 'source',              '意 뜻 의': 'meaning, intention',
  '示 보일 시': 'to show',             '唆 부추길 사': 'to prompt, to hint',
  '誌 기록할 지': 'record, journal',
  // Social phenomena.
  '衆 무리 중': 'the masses',          '低 낮을 저': 'low',
  '高 높을 고': 'high',                '齡 나이 령': 'age',
  '都 도읍 도': 'capital, city',        '趨 달아날 추': 'to hasten, tendency',
  '勢 형세 세': 'force, situation',      '向 향할 향': 'to face, direction',
  '態 모습 태': 'state, condition',      '提 끌 제': 'to raise, to propose',
  '案 책상 안': 'proposal, plan',        '改 고칠 개': 'to reform',
  '革 가죽 혁': 'hide, to change',       '善 착할 선': 'good',
  '踐 밟을 천': 'to tread, to practise', '帶 띠 대': 'belt, band',
  '益 더할 익': 'benefit',

  // Conflict and reconciliation.
  '葛 칡 갈': 'arrowroot vine',         '藤 등나무 등': 'wisteria vine',
  '誤 그르칠 오': 'to err',            '解 풀 해': 'to loosen, to resolve',
  '摩 문지를 마': 'to rub',            '擦 문지를 찰': 'to scrape',
  '爭 다툴 쟁': 'to contend',          '謝 사례할 사': 'to thank, to apologise',
  '恕 용서할 서': 'to forgive',         '仲 버금 중': 'middle, intermediary',
  // Mental states.
  '精 정할 정': 'refined, spirit',       '神 귀신 신': 'spirit, god',
  '恐 두려울 공': 'to fear',           '怖 두려워할 포': 'dread',
  '憂 근심 우': 'worry',               '鬱 답답할 울': 'gloom, congestion',
  '附 붙을 부': 'to attach',           '緖 실마리 서': 'thread, beginning',
  '伏 엎드릴 복': 'to lie prostrate',    '羞 부끄러울 수': 'shame',
  '恥 부끄러울 치': 'disgrace',         '靜 고요할 정': 'calm',
  // Social problems.
  '極 극진할 극': 'extreme, pole',       '貧 가난할 빈': 'poor',
  '富 부자 부': 'rich',                '犯 범할 범': 'to violate',
  '罪 허물 죄': 'crime, guilt',         '孤 외로울 고': 'alone',
  '獨 홀로 독': 'solitary',            '死 죽을 사': 'to die',
  '別 다를 별': 'separate, different',   '偏 치우칠 편': 'biased',
  '階 섬돌 계': 'step, rank',           '層 층 층': 'layer, stratum',
  '策 꾀 책': 'plan, measure',          '全 온전 전': 'whole, complete',
  // Workplace relationships.
  '競 다툴 경': 'to compete',          '昇 오를 승': 'to rise',
  '退 물러날 퇴': 'to withdraw',        '僚 동료 료': 'colleague',
  '去 갈 거': 'to go, past',           '顧 돌아볼 고': 'to look back, to patronise',
  '轉 구를 전': 'to turn, to transfer',  '勤 부지런할 근': 'diligent, duty',

  // Adverbs that read as native and are not.
  '優 넉넉할 우': 'superior, ample',     '設 베풀 설': 'to set up, to suppose',
  '令 하여금 령': 'command, to cause',   '甚 심할 심': 'extreme',
  '至 이를 지': 'to arrive at',         '但 다만 단': 'only, however',
  '只 다만 지': 'merely',              '何 어찌 하': 'what, why',
  '面 낯 면': 'face, side',
  // Internet.
  '秘 숨길 비': 'secret',              '密 빽빽할 밀': 'dense, close',
  '番 차례 번': 'turn, number',         '號 이름 호': 'name, number',
  '讀 읽을 독': 'to read',             '像 모양 상': 'image',
  '索 찾을 색': 'to search',           '窓 창 창': 'window',
  '定 정할 정': 'to fix, to settle',
  // Technology.
  '能 능할 능': 'ability',             '知 알 지': 'to know',
  '商 장사 상': 'commerce',
  '律 법칙 률': 'law, rule',           '走 달릴 주': 'to run',
  '宇 집 우': 'space, universe',        '宙 집 주': 'cosmos',
  '航 배 항': 'to navigate',           '半 반 반': 'half',
  '導 인도할 도': 'to lead, to conduct', '命 목숨 명': 'life, command',
  '端 끝 단': 'end, tip',              '尖 뾰족할 첨': 'sharp, pointed',
  // Tradition and heritage.
  '寶 보배 보': 'treasure',            '歷 지날 력': 'to pass through, history',
  '王 임금 왕': 'king',                '朝 아침 조': 'morning, dynasty',
  '流 흐를 류': 'to flow',             '想 생각 상': 'thought',
  '儒 선비 유': 'Confucian scholar',     '佛 부처 불': 'Buddha',
  // Housing and furniture.
  '寢 잘 침': 'to sleep',              '臺 대 대': 'platform, stand',
  '冊 책 책': 'book',                  '卓 높을 탁': 'table, high',
  '貰 세낼 세': 'to rent',             '賣 팔 매': 'to sell',
  '買 살 매': 'to buy',                '保 지킬 보': 'to protect, to guarantee',
  '契 맺을 계': 'to contract',          '約 약속 약': 'promise, agreement',
  '藏 감출 장': 'to store',            '庫 곳집 고': 'storehouse',
  '洗 씻을 세': 'to wash',             '濯 씻을 탁': 'to rinse',
  '淸 맑을 청': 'clear, clean',         '掃 쓸 소': 'to sweep',
  '玄 검을 현': 'dark, profound',       '關 관계할 관': 'barrier, to connect',
  '新 새 신': 'new',                   '築 쌓을 축': 'to build',
  '單 홑 단': 'single',                '住 살 주': 'to reside',
  '宅 집 택': 'residence',             '月 달 월': 'moon, month',
  // People and contact.
  '輩 무리 배': 'cohort, generation',    '弟 아우 제': 'younger brother',
  '脈 줄기 맥': 'vein, network',        '因 인할 인': 'cause',
  '緣 인연 연': 'tie, affinity',        '伴 짝 반': 'companion',
  '後 뒤 후': 'behind, after',

  // ── Fifth curation pass ───────────────────────────────────────────────────
  // Culture, leisure and the arts.
  '劇 심할 극': 'drama, intense',        '展 펼 전': 'to unfold, to exhibit',
  '休 쉴 휴': 'to rest',               '息 쉴 식': 'to breathe, to rest',
  '好 좋을 호': 'to like, good',        '舞 춤출 무': 'to dance',
  '奏 아뢸 주': 'to play (music)',       '器 그릇 기': 'vessel, instrument',
  '寫 베낄 사': 'to copy, to photograph', '眞 참 진': 'true, real',
  '撮 모을 촬': 'to gather, to shoot',   '影 그림자 영': 'shadow, image',
  '趣 뜻 취': 'interest, taste',        '活 살 활': 'to live, active',
  // Sightseeing.
  '光 빛 광': 'light',                 '蹟 자취 적': 'trace, ruins',
  '名 이름 명': 'name, renowned',        '所 바 소': 'place',
  '望 바랄 망': 'to gaze, to hope',      '記 기록할 기': 'to record',
  '養 기를 양': 'to nurture',           '沒 빠질 몰': 'to sink',
  '致 이를 치': 'to reach, to cause',    '夜 밤 야': 'night',
  '追 쫓을 추': 'to pursue',            '憶 생각할 억': 'to recall',
  // Work and tasks.
  '件 물건 건': 'item, case',           '承 이을 승': 'to inherit, to accept',
  '認 알 인': 'to recognise',           '張 베풀 장': 'to stretch, to spread',
  '俸 녹 봉': 'salary',                '給 줄 급': 'to give, to supply',
  '怠 게으를 태': 'idle, negligent',
  // Customs and performance.
  '習 익힐 습': 'to practise, custom',   '秋 가을 추': 'autumn',
  '夕 저녁 석': 'evening',             '服 옷 복': 'clothing',
  '屋 집 옥': 'house',
  // Sports.
  '蹴 찰 축': 'to kick',               '球 공 구': 'ball',
  '籠 대바구니 롱': 'basket',           '排 밀칠 배': 'to push, to arrange',
  '泳 헤엄칠 영': 'to swim',           '登 오를 등': 'to climb',
  '山 메 산': 'mountain',              '跆 밟을 태': 'to trample',
  '拳 주먹 권': 'fist',                '道 길 도': 'way, path',
  // Travel.
  '背 등 배': 'back',                  '囊 주머니 낭': 'pouch, sack',
  '錢 돈 전': 'coin, money',           '程 한도 정': 'extent, schedule',
  '汽 물끓는김 기': 'steam',            '飛 날 비': 'to fly',
  '船 배 선': 'boat',                  '舶 큰배 박': 'large ship',

  // ── Fifth pass, second batch ──────────────────────────────────────────────
  '泊 머무를 박': 'to lodge',           '搭 탈 탑': 'to board',
  '荷 짐 하': 'load, baggage',         '稅 세금 세': 'tax',
  '整 가지런할 정': 'orderly',          '頓 조을 돈': 'to arrange',
  '離 떠날 리': 'to separate',          '管 대롱 관': 'pipe, to manage',
  '派 갈래 파': 'branch, to dispatch',   '散 흩을 산': 'to scatter',
  '施 베풀 시': 'to carry out',         '便 편할 편': 'convenient, side',
  '宜 마땅 의': 'suitable',            '騷 떠들 소': 'noisy',
  '栓 마개 전': 'plug, tap',           '雜 섞일 잡': 'mixed, miscellaneous',
  '速 빠를 속': 'fast',                '著 나타날 저': 'to author, to appear',
  '媒 중매 매': 'go-between, medium',    '敬 공경할 경': 'to respect',
  '握 쥘 악': 'to grasp',              '德 덕 덕': 'virtue',
  '慣 익숙할 관': 'accustomed',         '配 나눌 배': 'to distribute',
  '慮 생각할 려': 'to consider',         '福 복 복': 'blessing',
  '祉 복 지': 'welfare',               '兒 아이 아': 'child',
  '惠 은혜 혜': 'favour, grace',        '澤 못 택': 'marsh, bounty',
  '奉 받들 봉': 'to serve',            '仕 섬길 사': 'to serve',
  '需 쓰일 수': 'to need, demand',       '供 이바지할 공': 'to supply',
  '圈 우리 권': 'sphere, zone',         '輸 보낼 수': 'to transport',
  '效 본받을 효': 'effect',             '太 클 태': 'great',
  '陽 볕 양': 'sun, positive',          '燃 탈 연': 'to burn',
  '再 두 재': 'again',                 '植 심을 식': 'to plant',
  '棲 살 서': 'to dwell',              '森 수풀 삼': 'forest',
  '林 수풀 림': 'grove',               '海 바다 해': 'sea',
  '微 작을 미': 'minute, fine',         '細 가늘 세': 'thin, fine',
  '害 해할 해': 'harm',                '質 바탕 질': 'substance, quality',
  '炭 숯 탄': 'charcoal, carbon',        '素 본디 소': 'element, plain',
  '暖 따뜻할 난': 'warm',              '循 돌 순': 'to circulate',
  '回 돌아올 회': 'to return, a time',   '射 쏠 사': 'to shoot, to radiate',
  '酸 실 산': 'sour, acid',            '性 성품 성': 'nature, property',
  '紫 자줏빛 자': 'purple',            '沙 모래 사': 'sand',
  '漠 넓을 막': 'vast, desert',         '氷 얼음 빙': 'ice',
  '河 물 하': 'river',                 '洪 넓을 홍': 'vast, flood',
  '旱 마를 한': 'drought',             '震 우레 진': 'to quake',
  '持 가질 지': 'to hold',             '可 옳을 가': 'possible',
  '踊 뛸 용': 'to leap, to dance',      '詩 시 시': 'poem',
  '小 작을 소': 'small',               '隨 따를 수': 'to follow',
  '筆 붓 필': 'brush, to write',        '繪 그림 회': 'to draw',
  '彫 새길 조': 'to carve',            '板 널 판': 'board, plank',
  '陶 질그릇 도': 'pottery',            '瓷 사기그릇 자': 'porcelain',
  '咸 다 함': 'all',                   '使 부릴 사': 'to send, envoy',
  '則 법칙 칙': 'rule',                '構 얽을 구': 'to construct',
  '系 이을 계': 'lineage, system',       '元 으뜸 원': 'origin, prime',
  '規 법 규': 'rule, compass',          '範 법 범': 'model, norm',
  '倫 인륜 륜': 'human relations',       '等 무리 등': 'rank, equal',
  '世 인간 세': 'world, generation',     '界 지경 계': 'boundary, realm',
  '互 서로 호': 'mutual',              '矜 자랑할 긍': 'to be proud',
  '非 아닐 비': 'not, non-',            '確 굳을 확': 'certain',
  '模 본뜰 모': 'model, scale',         '賃 품삯 임': 'wages, rent',
  '緩 느릴 완': 'slow, to relax',        '請 청할 청': 'to request',
  '願 원할 원': 'to wish',             '聽 들을 청': 'to listen',
  '條 가지 조': 'article, clause',       '例 법식 례': 'example, precedent',
  '審 살필 심': 'to examine',          '卽 곧 즉': 'namely, at once',
  '萬 일만 만': 'ten thousand',         '若 같을 약': 'if, like',
  '劑 약제 제': 'preparation, dose',     '朱 붉을 주': 'vermilion',
  '黃 누를 황': 'yellow',              '色 빛 색': 'colour',
  '粉 가루 분': 'powder',              '紅 붉을 홍': 'red, pink',
  '最 가장 최': 'most',                '受 받을 수': 'to receive',
  '申 펼 신': 'to state, to apply',      '就 나아갈 취': 'to attain',
  '限 한할 한': 'limit',               '況 상황 황': 'circumstance',
  '負 짐질 부': 'to bear, negative',     '債 빚 채': 'debt',
  '揭 걸 게': 'to post, to hoist',      '四 넉 사': 'four',
  '焦 탈 초': 'scorched, anxious',       '燥 마를 조': 'dry',
  '欌 장롱 장': 'wardrobe, cabinet',
  '週 돌 주': 'week',                  '授 줄 수': 'to give, to teach',
  '經 지날 경': 'to pass, scripture',
  '診 진찰할 진': 'to examine (medically)', '療 병고칠 료': 'to treat, to cure',
  '固 굳을 고': 'firm',                '執 잡을 집': 'to grasp, to hold to',
  '疲 피곤할 피': 'weary',             '勞 일할 로': 'toil',
  '量 헤아릴 량': 'quantity',           '綜 모을 종': 'to gather, to synthesise',
  '食 먹을 식': 'to eat, food',         '家 집 가': 'house, expert',

  // Hospital and pharmacy.
  '看 볼 간': 'to watch over',         '患 근심 환': 'to suffer, illness',
  '者 놈 자': 'person',                '外 바깥 외': 'outside',
  '應 응할 응': 'to respond',          '急 급할 급': 'urgent',
  '方 모 방': 'direction, method',      '箋 기록할 전': 'slip of paper',
  '軟 연할 연': 'soft',                '膏 기름 고': 'ointment, fat',
  '咽 목구멍 인': 'throat',            '喉 목구멍 후': 'larynx',

  // ── Second curation pass ────────────────────────────────────────────────────
  // Roots chosen by cascade potential: each one below appears inside several compounds
  // in levels.json, so curating it lifts every compound containing it via sino-partial.
  '旅 나그네 려': 'traveller',        '自 스스로 자': 'self',
  '然 그럴 연': 'so, thus',           '由 말미암을 유': 'to arise from',
  '關 관계할 관': 'to connect',       '係 맬 계': 'to tie',
  '共 함께 공': 'together',           '鑑 거울 감': 'to examine',
  '賞 상줄 상': 'to appreciate',      '議 의논할 의': 'to deliberate',
  '儀 거동 의': 'rite, decorum',      '排 물리칠 배': 'to expel',
  '電 번개 전': 'electricity',        '話 말씀 화': 'speech',
  '失 잃을 실': 'to lose',            '策 꾀 책': 'scheme, policy',
  '景 볕 경': 'scene, prospect',      '態 모습 태': 'condition',
  '汚 더러울 오': 'to soil',          '染 물들일 염': 'to stain',
  '保 지킬 보': 'to preserve',        '護 도울 호': 'to guard',
  '候 기후 후': 'season, climate',
  '要 요긴할 요': 'essential',        '選 가릴 선': 'to select',
  '擧 들 거': 'to raise up',          '授 줄 수': 'to impart',
  '卒 마칠 졸': 'to finish',          '企 꾀할 기': 'to plan',
  '創 비롯할 창': 'to originate',     '成 이룰 성': 'to form',
  '語 말씀 어': 'word, speech',       '感 느낄 감': 'to feel',
  '滿 찰 만': 'full',                 '足 발 족': 'sufficient',
  '疏 소통할 소': 'distant, sparse',  '遠 멀 원': 'far',
  '興 일 흥': 'to arise, interest',   '味 맛 미': 'taste',
  '和 화할 화': 'harmony',            '製 지을 제': 'to manufacture',
  '造 지을 조': 'to build',           '析 쪼갤 석': 'to analyse',
  '變 변할 변': 'to change',          '危 위태할 위': 'danger',
  '機 틀 기': 'mechanism, juncture',  '代 대신할 대': 'generation, era',
  '結 맺을 결': 'to bind, conclude',  '論 논할 론': 'to argue',
  '體 몸 체': 'body, form',
  '連 이을 련': 'to link',            '續 이을 속': 'to continue',
  '對 대할 대': 'to face, oppose',    '照 비칠 조': 'to shine on, compare',
  '人 사람 인': 'person',             '分 나눌 분': 'to divide',
  // Used by the corrected 병원 entry.
  '病 병 병': 'illness',
  // 茶 carries two established Korean readings, 다 and 차. Both are listed so 차 is not
  // rendered as a 두음법칙 shift, which it is not.
  '茶 차 차': 'tea',
};

// ─────────────────────────────────────────────────────────────────────────────
// Curated word origins. Format: [hanja, [eumhun tokens...]] for pure Sino-Korean,
// or a descriptor object for native / mixed / loan words.
//
// Three entries are corrected relative to the old HANJA_MAP, which contained
// hanja that did not match its own breakdown:
//   무료   listed 免費 but decomposed 無 + 料   -> 無料 is correct
//   환불   listed the parts in reverse order    -> 還拂
//   계좌이체 listed 口座 (= 구좌, the obsolete term) -> 計座移替
// ─────────────────────────────────────────────────────────────────────────────
const SINO = {
  '형': ['兄', ['兄 형 형']],
  '부모': ['父母', ['父 아비 부', '母 어미 모']],
  '자녀': ['子女', ['子 아들 자', '女 딸 녀']],
  '친척': ['親戚', ['親 친할 친', '戚 겨레 척']],
  '삼촌': ['三寸', ['三 석 삼', '寸 마디 촌']],
  '이모': ['姨母', ['姨 이모 이', '母 어미 모']],
  '고모': ['姑母', ['姑 시어미 고', '母 어미 모']],
  '손자': ['孫子', ['孫 손자 손', '子 아들 자']],
  '손녀': ['孫女', ['孫 손자 손', '女 딸 녀']],
  '학교': ['學校', ['學 배울 학', '校 학교 교']],
  '학생': ['學生', ['學 배울 학', '生 날 생']],
  '선생님': ['先生', ['先 먼저 선', '生 날 생']],
  // Corrected: the original map had 醫院, which reads 의원 (a clinic, or an assembly member).
  // 병원 is 病院.
  '병원': ['病院', ['病 병 병', '院 집 원']],
  '의사': ['醫師', ['醫 의원 의', '師 스승 사']],
  '약국': ['藥局', ['藥 약 약', '局 판 국']],
  '은행': ['銀行', ['銀 은 은', '行 다닐 행']],
  '우체국': ['郵遞局', ['郵 우편 우', '遞 갈아탈 체', '局 판 국']],
  '경찰서': ['警察署', ['警 경계할 경', '察 살필 찰', '署 관청 서']],
  '소방서': ['消防署', ['消 사라질 소', '防 막을 방', '署 관청 서']],
  '백화점': ['百貨店', ['百 일백 백', '貨 재물 화', '店 가게 점']],
  '도서관': ['圖書館', ['圖 그림 도', '書 글 서', '館 집 관']],
  '박물관': ['博物館', ['博 넓을 박', '物 물건 물', '館 집 관']],
  '미술관': ['美術館', ['美 아름다울 미', '術 재주 술', '館 집 관']],
  '공원': ['公園', ['公 공평할 공', '園 동산 원']],
  '영화관': ['映畫館', ['映 비칠 영', '畫 그림 화', '館 집 관']],
  '미용실': ['美容室', ['美 아름다울 미', '容 얼굴 용', '室 집 실']],
  '지하철역': ['地下鐵驛', ['地 땅 지', '下 아래 하', '鐵 쇠 철', '驛 역 역']],
  '지하철': ['地下鐵', ['地 땅 지', '下 아래 하', '鐵 쇠 철']],
  '공항': ['空港', ['空 하늘 공', '港 항구 항']],
  '항구': ['港口', ['港 항구 항', '口 입 구']],
  '주차장': ['駐車場', ['駐 살 주', '車 수레 차', '場 마당 장']],
  '식당': ['食堂', ['食 먹을 식', '堂 집 당']],
  '음료수': ['飲料水', ['飲 마실 음', '料 헤아릴 료', '水 물 수']],
  '음식': ['飲食', ['飲 마실 음', '食 먹을 식']],
  '차': ['茶', ['茶 차 차']],   // dual reading 다/차; here it is 차
  '만두': ['饅頭', ['饅 만두 만', '頭 머리 두']],
  // 과일 is deliberately absent: the original map claimed 果實, which reads 과실, not 과일.
  // It is handled as a naturalised native form in NATIVE_NOTE instead.
  '시간': ['時間', ['時 때 시', '間 사이 간']],
  '일자': ['日字', ['日 날 일', '字 글자 자']],
  '주말': ['週末', ['週 돌 주', '末 끝 말']],
  '평일': ['平日', ['平 평평할 평', '日 날 일']],
  '정오': ['正午', ['正 바를 정', '午 낮 오']],
  '자정': ['子正', ['子 첫째지 자', '正 바를 정']],
  '계절': ['季節', ['季 계절 계', '節 마디 절']],
  '기온': ['氣溫', ['氣 기운 기', '溫 따뜻할 온']],
  '습도': ['濕度', ['濕 축축할 습', '度 법도 도']],
  '온도': ['溫度', ['溫 따뜻할 온', '度 법도 도']],
  '운동': ['運動', ['運 옮길 운', '動 움직일 동']],
  '문화': ['文化', ['文 글 문', '化 될 화']],
  '여가': ['餘暇', ['餘 남을 여', '暇 겨레 가']],
  '건강': ['健康', ['健 건강할 건', '康 편안할 강']],
  '증상': ['症狀', ['症 증세 증', '狀 형상 상']],
  '과목': ['科目', ['科 과목 과', '目 눈 목']],
  '시험': ['試驗', ['試 시험할 시', '驗 시험 험']],
  '직업': ['職業', ['職 직분 직', '業 업 업']],
  '업무': ['業務', ['業 업 업', '務 힘쓸 무']],
  '과제': ['課題', ['課 매길 과', '題 제목 제']],
  '주거': ['住居', ['住 살 주', '居 살 거']],
  '가구': ['家具', ['家 집 가', '具 갖출 구']],
  '환경': ['環境', ['環 고리 환', '境 지경 경']],
  '정보': ['情報', ['情 뜻 정', '報 알릴 보']],
  '통신': ['通信', ['通 통할 통', '信 믿을 신']],
  '방송': ['放送', ['放 놓을 방', '送 보낼 송']],
  '신문': ['新聞', ['新 새 신', '聞 들을 문']],
  '예절': ['禮節', ['禮 예도 예', '節 마디 절']],
  '사회': ['社會', ['社 모임 사', '會 모일 회']],
  '제도': ['制度', ['制 제도 제', '度 법도 도']],
  '문제': ['問題', ['問 물을 문', '題 제목 제']],
  '금융': ['金融', ['金 돈 금', '融 녹을 융']],
  '경제': ['經濟', ['經 지날 경', '濟 건널 제']],
  '소비': ['消費', ['消 사라질 소', '費 쓸 비']],
  '시장': ['市場', ['市 저자 시', '場 마당 장']],
  '무역': ['貿易', ['貿 무역할 무', '易 바꿀 역']],
  '산업': ['產業', ['產 낳을 산', '業 업 업']],
  '과학': ['科學', ['科 과목 과', '學 배울 학']],
  '연구': ['研究', ['研 갈 연', '究 구할 구']],
  '기술': ['技術', ['技 재주 기', '術 재주 술']],
  '유산': ['遺產', ['遺 남길 유', '產 재산 산']],
  '공연': ['公演', ['公 공평할 공', '演 펼칠 연']],
  '예술': ['藝術', ['藝 재주 예', '術 재주 술']],
  '문학': ['文學', ['文 글 문', '學 배울 학']],
  '판단': ['判斷', ['判 판단할 판', '斷 끊을 단']],
  '가치': ['價値', ['價 값 가', '値 값 치']],
  '기준': ['基準', ['基 터 기', '準 평평할 준']],
  '개념': ['概念', ['概 대개 개', '念 생각 념']],
  '원리': ['原理', ['原 근본 원', '理 이치 리']],
  '정치': ['政治', ['政 정사 정', '治 다스릴 치']],
  '정부': ['政府', ['政 정사 정', '府 관청 부']],
  '법': ['法', ['法 법 법']],
  '질서': ['秩序', ['秩 차례 질', '序 차례 서']],
  '행정': ['行政', ['行 행할 행', '政 정사 정']],
  '시민': ['市民', ['市 저자 시', '民 백성 민']],
  '예약': ['豫約', ['豫 먼저 예', '約 약속 약']],
  '주문': ['注文', ['注 대댈 주', '文 글자 문']],
  '계산': ['計算', ['計 셈할 계', '算 셈할 산']],
  '영수증': ['領收證', ['領 거둘 영', '收 거둘 수', '證 증거 증']],
  '종업원': ['從業員', ['從 따를 종', '業 업무 업', '員 인원 원']],
  '가격': ['價格', ['價 값 가', '格 격식 격']],
  '할인': ['割引', ['割 쪼갤 할', '引 끌 인']],
  '결제': ['決済', ['決 결단할 결', '済 건널 제']],
  '현금': ['現金', ['現 나타날 현', '金 돈 금']],
  '계좌이체': ['計座移替', ['計 셈할 계', '座 자리 좌', '移 옮길 이', '替 바꿀 체']],
  '환불': ['還拂', ['還 돌아올 환', '拂 떨칠 불']],
  '구매': ['購買', ['購 살 구', '買 살 매']],
  '판매': ['販賣', ['販 팔 판', '賣 팔 매']],
  '절약': ['節約', ['節 아낄 절', '約 약속 약']],
  '낭비': ['浪費', ['浪 물결 랑', '費 쓸 비']],
  '무료': ['無料', ['無 없을 무', '料 헤아릴 료']],
  '중앙': ['中央', ['中 가운데 중', '央 가운데 앙']],
  '수단': ['手段', ['手 손 수', '段 단계 단']],
  '요금': ['料金', ['料 헤아릴 료', '金 돈 금']],
  '노선': ['路線', ['路 길 로', '線 줄 선']],
  '환승': ['換乘', ['換 바꿀 환', '乘 탈 승']],
  '하차': ['下車', ['下 아래 하', '車 수레 차']],
  '승차': ['乘車', ['乘 탈 승', '車 수레 차']],
  '경유': ['經由', ['經 지날 경', '由 까닭 유']],
  '출구': ['出口', ['出 날 출', '口 입 구']],

  // ── Second curation pass ────────────────────────────────────────────────────
  // Selected by measuring which roots occur inside the most still-uncurated compounds
  // (see the cascade analysis in the commit message), not by working alphabetically.
  '여행': ['旅行', ['旅 나그네 려', '行 다닐 행']],
  '자연': ['自然', ['自 스스로 자', '然 그럴 연']],
  '자유': ['自由', ['自 스스로 자', '由 까닭 유']],
  '관계': ['關係', ['關 관계할 관', '係 맬 계']],
  '공공': ['公共', ['公 공평할 공', '共 함께 공']],
  '감상': ['鑑賞', ['鑑 거울 감', '賞 상줄 상']],
  '회의': ['會議', ['會 모일 회', '議 의논할 의']],
  '예의': ['禮儀', ['禮 예도 예', '儀 거동 의']],
  '배출': ['排出', ['排 물리칠 배', '出 날 출']],
  '전화': ['電話', ['電 번개 전', '話 말씀 화']],
  '실업': ['失業', ['失 잃을 실', '業 업 업']],
  '정책': ['政策', ['政 정사 정', '策 꾀 책']],
  '경기': ['景氣', ['景 볕 경', '氣 기운 기']],
  '생태': ['生態', ['生 날 생', '態 모습 태']],
  '오염': ['汚染', ['汚 더러울 오', '染 물들일 염']],
  '보호': ['保護', ['保 지킬 보', '護 도울 호']],
  '기후': ['氣候', ['氣 기운 기', '候 기후 후']],
  '현대': ['現代', ['現 나타날 현', '代 대신할 대']],
  '요약': ['要約', ['要 요긴할 요', '約 약속 약']],
  '선거': ['選擧', ['選 가릴 선', '擧 들 거']],
  '수업': ['授業', ['授 줄 수', '業 업 업']],
  '졸업': ['卒業', ['卒 마칠 졸', '業 업 업']],
  '기업': ['企業', ['企 꾀할 기', '業 업 업']],
  '창업': ['創業', ['創 비롯할 창', '業 업 업']],
  '성어': ['成語', ['成 이룰 성', '語 말씀 어']],
  '감동': ['感動', ['感 느낄 감', '動 움직일 동']],
  '만족': ['滿足', ['滿 찰 만', '足 발 족']],
  '인기': ['人氣', ['人 사람 인', '氣 기운 기']],
  '소원': ['疏遠', ['疏 소통할 소', '遠 멀 원']],
  '흥미': ['興味', ['興 일 흥', '味 맛 미']],
  '평화': ['平和', ['平 평평할 평', '和 화할 화']],
  '주민': ['住民', ['住 살 주', '民 백성 민']],
  '제조': ['製造', ['製 지을 제', '造 지을 조']],
  '분석': ['分析', ['分 나눌 분', '析 쪼갤 석']],
  '변화': ['變化', ['變 변할 변', '化 될 화']],
  '위기': ['危機', ['危 위태할 위', '機 틀 기']],
  '결론': ['結論', ['結 맺을 결', '論 논할 론']],
  '구체': ['具體', ['具 갖출 구', '體 몸 체']],
  '연속': ['連續', ['連 이을 련', '續 이을 속']],
  '대조': ['對照', ['對 대할 대', '照 비칠 조']],

  // ── Third curation pass ───────────────────────────────────────────────────
  // Chosen because they read as native to a learner and are not. Getting these wrong in the
  // other direction — filing them under 고유어 because they are everyday words — is exactly
  // the mistake the inherited data made.
  '내장': ['內臟', ['內 안 내', '臟 오장 장']],
  '심장': ['心臟', ['心 마음 심', '臟 오장 장']],
  '폐': ['肺', ['肺 허파 폐']],
  '감기': ['感氣', ['感 느낄 감', '氣 기운 기']],
  '두통': ['頭痛', ['頭 머리 두', '痛 아플 통']],
  '치통': ['齒痛', ['齒 이 치', '痛 아플 통']],
  '복통': ['腹痛', ['腹 배 복', '痛 아플 통']],
  '소화불량': ['消化不良', ['消 사라질 소', '化 될 화', '不 아닐 불', '良 좋을 량']],
  '열': ['熱', ['熱 더울 열']],
  '설사': ['泄瀉', ['泄 샐 설', '瀉 쏟을 사']],
  '변비': ['便祕', ['便 똥오줌 변', '祕 숨길 비']],
  '상처': ['傷處', ['傷 다칠 상', '處 곳 처']],
  '골절': ['骨折', ['骨 뼈 골', '折 꺾을 절']],
  '염증': ['炎症', ['炎 불꽃 염', '症 증세 증']],
  '피부': ['皮膚', ['皮 가죽 피', '膚 살갗 부']],
  // Weather.
  '태풍': ['颱風', ['颱 태풍 태', '風 바람 풍']],
  '폭설': ['暴雪', ['暴 사나울 폭', '雪 눈 설']],
  '폭염': ['暴炎', ['暴 사나울 폭', '炎 불꽃 염']],
  '한파': ['寒波', ['寒 찰 한', '波 물결 파']],
  '일교차': ['日較差', ['日 날 일', '較 견줄 교', '差 다를 차']],
  // Time. 내일 and 점심 are the two that most often get filed as native.
  '내일': ['來日', ['來 올 래', '日 날 일']],
  '점심': ['點心', ['點 점 점', '心 마음 심']],
  '작년': ['昨年', ['昨 어제 작', '年 해 년']],
  '내년': ['來年', ['來 올 래', '年 해 년']],
  // Food.
  '반찬': ['飯饌', ['飯 밥 반', '饌 반찬 찬']],
  '냉면': ['冷麵', ['冷 찰 랭', '麵 국수 면']],
  '죽': ['粥', ['粥 죽 죽']],
  // Clothing and objects.
  '양말': ['洋襪', ['洋 큰바다 양', '襪 버선 말']],
  '모자': ['帽子', ['帽 모자 모', '子 아들 자']],
  '장갑': ['掌匣', ['掌 손바닥 장', '匣 갑 갑']],
  '지갑': ['紙匣', ['紙 종이 지', '匣 갑 갑']],
  '시계': ['時計', ['時 때 시', '計 셈할 계']],
  '안경': ['眼鏡', ['眼 눈 안', '鏡 거울 경']],
  '화장품': ['化粧品', ['化 될 화', '粧 단장할 장', '品 물건 품']],
  '치약': ['齒藥', ['齒 이 치', '藥 약 약']],
  // Appearance.
  '체구': ['體軀', ['體 몸 체', '軀 몸 구']],
  '체형': ['體型', ['體 몸 체', '型 모형 형']],
  '이목구비': ['耳目口鼻', ['耳 귀 이', '目 눈 목', '口 입 구', '鼻 코 비']],
  '인상': ['印象', ['印 도장 인', '象 코끼리 상']],
  '미인': ['美人', ['美 아름다울 미', '人 사람 인']],
  '동안': ['童顔', ['童 아이 동', '顔 얼굴 안']],
  '노안': ['老顔', ['老 늙을 로', '顔 얼굴 안']],
  // Adverb and direction.
  '항상': ['恒常', ['恒 항상 항', '常 떳떳할 상']],
  '직진': ['直進', ['直 곧을 직', '進 나아갈 진']],

  // ── Law and order ─────────────────────────────────────────────────────────
  '헌법': ['憲法', ['憲 법 헌', '法 법 법']],
  '법원': ['法院', ['法 법 법', '院 집 원']],
  '재판': ['裁判', ['裁 마를 재', '判 판단할 판']],
  '판사': ['判事', ['判 판단할 판', '事 일 사']],
  '검사': ['檢事', ['檢 검사할 검', '事 일 사']],
  '변호사': ['辯護士', ['辯 말잘할 변', '護 도울 호', '士 선비 사']],
  '피고': ['被告', ['被 입을 피', '告 알릴 고']],
  '원고': ['原告', ['原 근본 원', '告 알릴 고']],
  '소송': ['訴訟', ['訴 호소할 소', '訟 송사할 송']],
  '판결': ['判決', ['判 판단할 판', '決 결단할 결']],
  '불법': ['不法', ['不 아닐 불', '法 법 법']],
  '합법': ['合法', ['合 합할 합', '法 법 법']],
  '형사': ['刑事', ['刑 형벌 형', '事 일 사']],
  '민사': ['民事', ['民 백성 민', '事 일 사']],
  '혐의': ['嫌疑', ['嫌 싫어할 혐', '疑 의심할 의']],
  '증거': ['證據', ['證 증거 증', '據 근거 거']],
  '징역': ['懲役', ['懲 징계할 징', '役 부릴 역']],
  '벌금': ['罰金', ['罰 벌할 벌', '金 돈 금']],
  '사법': ['司法', ['司 맡을 사', '法 법 법']],
  '치안': ['治安', ['治 다스릴 치', '安 편안 안']],
  // ── Finance and economy ───────────────────────────────────────────────────
  '증권': ['證券', ['證 증거 증', '券 문서 권']],
  '주식': ['株式', ['株 그루 주', '式 법 식']],
  '투자': ['投資', ['投 던질 투', '資 재물 자']],
  '저축': ['貯蓄', ['貯 쌓을 저', '蓄 모을 축']],
  '예금': ['預金', ['預 맡길 예', '金 돈 금']],
  '적금': ['積金', ['積 쌓을 적', '金 돈 금']],
  '대출': ['貸出', ['貸 빌릴 대', '出 날 출']],
  '금리': ['金利', ['金 돈 금', '利 이로울 리']],
  '이자': ['利子', ['利 이로울 리', '子 아들 자']],
  '물가': ['物價', ['物 물건 물', '價 값 가']],
  '환율': ['換率', ['換 바꿀 환', '率 비율 률']],
  '자산': ['資產', ['資 재물 자', '產 재산 산']],
  '원가': ['原價', ['原 근본 원', '價 값 가']],
  '이윤': ['利潤', ['利 이로울 리', '潤 불을 윤']],
  '손실': ['損失', ['損 덜 손', '失 잃을 실']],
  '적자': ['赤字', ['赤 붉을 적', '字 글자 자']],
  '흑자': ['黑字', ['黑 검을 흑', '字 글자 자']],
  '자본': ['資本', ['資 재물 자', '本 근본 본']],
  // ── School ────────────────────────────────────────────────────────────────
  '교실': ['敎室', ['敎 가르칠 교', '室 집 실']],
  '강의실': ['講義室', ['講 익힐 강', '義 옳을 의', '室 집 실']],
  '강당': ['講堂', ['講 익힐 강', '堂 집 당']],
  '체육관': ['體育館', ['體 몸 체', '育 기를 육', '館 집 관']],
  '기숙사': ['寄宿舍', ['寄 부칠 기', '宿 잘 숙', '舍 집 사']],
  '국어': ['國語', ['國 나라 국', '語 말씀 어']],
  '영어': ['英語', ['英 꽃부리 영', '語 말씀 어']],
  '수학': ['數學', ['數 셈 수', '學 배울 학']],
  '한국사': ['韓國史', ['韓 한국 한', '國 나라 국', '史 사기 사']],
  '지리': ['地理', ['地 땅 지', '理 이치 리']],
  '음악': ['音樂', ['音 소리 음', '樂 노래 악']],
  '체육': ['體育', ['體 몸 체', '育 기를 육']],
  '조교': ['助敎', ['助 도울 조', '敎 가르칠 교']],
  // ── Classes and exams ─────────────────────────────────────────────────────
  '강의': ['講義', ['講 익힐 강', '義 옳을 의']],
  '출석': ['出席', ['出 날 출', '席 자리 석']],
  '결석': ['缺席', ['缺 이지러질 결', '席 자리 석']],
  '지각': ['遲刻', ['遲 늦을 지', '刻 새길 각']],
  '학점': ['學點', ['學 배울 학', '點 점 점']],
  '중간고사': ['中間考査', ['中 가운데 중', '間 사이 간', '考 상고할 고', '査 조사할 사']],
  '기말고사': ['期末考査', ['期 기약할 기', '末 끝 말', '考 상고할 고', '査 조사할 사']],
  '보고서': ['報告書', ['報 알릴 보', '告 알릴 고', '書 글 서']],
  '논문': ['論文', ['論 논할 론', '文 글 문']],
  '장학금': ['奬學金', ['奬 장려할 장', '學 배울 학', '金 돈 금']],
  '입학': ['入學', ['入 들 입', '學 배울 학']],
  '학기': ['學期', ['學 배울 학', '期 기약할 기']],
  '방학': ['放學', ['放 놓을 방', '學 배울 학']],
  '성적표': ['成績表', ['成 이룰 성', '績 길쌈할 적', '表 겉 표']],
  '학위': ['學位', ['學 배울 학', '位 자리 위']],
  // ── Jobs and departments ──────────────────────────────────────────────────
  '사장': ['社長', ['社 모임 사', '長 긴 장']],
  '이사': ['理事', ['理 이치 리', '事 일 사']],
  '부장': ['部長', ['部 떼 부', '長 긴 장']],
  '차장': ['次長', ['次 버금 차', '長 긴 장']],
  '과장': ['課長', ['課 매길 과', '長 긴 장']],
  '대리': ['代理', ['代 대신할 대', '理 이치 리']],
  '사원': ['社員', ['社 모임 사', '員 인원 원']],
  '직원': ['職員', ['職 직분 직', '員 인원 원']],
  '직무': ['職務', ['職 직분 직', '務 힘쓸 무']],
  '조직': ['組織', ['組 짤 조', '織 짤 직']],
  '기획부': ['企劃部', ['企 꾀할 기', '劃 그을 획', '部 떼 부']],
  '영업부': ['營業部', ['營 경영할 영', '業 업 업', '部 떼 부']],
  '인사부': ['人事部', ['人 사람 인', '事 일 사', '部 떼 부']],
  '총무부': ['總務部', ['總 다 총', '務 힘쓸 무', '部 떼 부']],
  '재무부': ['財務部', ['財 재물 재', '務 힘쓸 무', '部 떼 부']],
  '개발부': ['開發部', ['開 열 개', '發 필 발', '部 떼 부']],
  // ── Hospital and pharmacy ─────────────────────────────────────────────────
  '간호사': ['看護士', ['看 볼 간', '護 도울 호', '士 선비 사']],
  '환자': ['患者', ['患 근심 환', '者 놈 자']],
  '내과': ['內科', ['內 안 내', '科 과목 과']],
  '외과': ['外科', ['外 바깥 외', '科 과목 과']],
  '안과': ['眼科', ['眼 눈 안', '科 과목 과']],
  '치과': ['齒科', ['齒 이 치', '科 과목 과']],
  '이비인후과': ['耳鼻咽喉科', ['耳 귀 이', '鼻 코 비', '咽 목구멍 인', '喉 목구멍 후', '科 과목 과']],
  '응급실': ['應急室', ['應 응할 응', '急 급할 급', '室 집 실']],
  '처방전': ['處方箋', ['處 곳 처', '方 모 방', '箋 기록할 전']],
  '연고': ['軟膏', ['軟 연할 연', '膏 기름 고']],

  // ── Fourth pass: 사자성어 (four-character idioms) ─────────────────────────
  '일석이조': ['一石二鳥', ['一 한 일', '石 돌 석', '二 두 이', '鳥 새 조']],
  '일거양득': ['一擧兩得', ['一 한 일', '擧 들 거', '兩 두 량', '得 얻을 득']],
  '동문서답': ['東問西答', ['東 동녘 동', '問 물을 문', '西 서녘 서', '答 대답할 답']],
  '심사숙고': ['深思熟考', ['深 깊을 심', '思 생각 사', '熟 익을 숙', '考 상고할 고']],
  '작심삼일': ['作心三日', ['作 지을 작', '心 마음 심', '三 석 삼', '日 날 일']],
  '고진감래': ['苦盡甘來', ['苦 쓸 고', '盡 다할 진', '甘 달 감', '來 올 래']],
  '유구무언': ['有口無言', ['有 있을 유', '口 입 구', '無 없을 무', '言 말씀 언']],
  '십시일반': ['十匙一飯', ['十 열 십', '匙 숟가락 시', '一 한 일', '飯 밥 반']],
  '동병상련': ['同病相憐', ['同 한가지 동', '病 병 병', '相 서로 상', '憐 불쌍히여길 련']],
  '칠전팔기': ['七顚八起', ['七 일곱 칠', '顚 엎드러질 전', '八 여덟 팔', '起 일어날 기']],
  '차일피일': ['此日彼日', ['此 이 차', '日 날 일', '彼 저 피', '日 날 일']],
  '과유불급': ['過猶不及', ['過 지날 과', '猶 오히려 유', '不 아닐 불', '及 미칠 급']],
  '청출어람': ['靑出於藍', ['靑 푸를 청', '出 날 출', '於 어조사 어', '藍 쪽 람']],
  '사필귀정': ['事必歸正', ['事 일 사', '必 반드시 필', '歸 돌아갈 귀', '正 바를 정']],
  '백발백중': ['百發百中', ['百 일백 백', '發 필 발', '百 일백 백', '中 가운데 중']],
  '자업자득': ['自業自得', ['自 스스로 자', '業 업 업', '自 스스로 자', '得 얻을 득']],
  '초지일관': ['初志一貫', ['初 처음 초', '志 뜻 지', '一 한 일', '貫 꿸 관']],
  '금상첨화': ['錦上添花', ['錦 비단 금', '上 윗 상', '添 더할 첨', '花 꽃 화']],
  '설상가상': ['雪上加霜', ['雪 눈 설', '上 윗 상', '加 더할 가', '霜 서리 상']],
  '유비무환': ['有備無患', ['有 있을 유', '備 갖출 비', '無 없을 무', '患 근심 환']],
  '이심전심': ['以心傳心', ['以 써 이', '心 마음 심', '傳 전할 전', '心 마음 심']],
  '주객전도': ['主客顚倒', ['主 주인 주', '客 손 객', '顚 엎드러질 전', '倒 넘어질 도']],
  '동상이몽': ['同床異夢', ['同 한가지 동', '床 평상 상', '異 다를 이', '夢 꿈 몽']],
  '속담': ['俗談', ['俗 풍속 속', '談 말씀 담']],

  // ── Politics and government ───────────────────────────────────────────────
  '국회': ['國會', ['國 나라 국', '會 모일 회']],
  '대통령': ['大統領', ['大 큰 대', '統 거느릴 통', '領 거느릴 령']],
  '정당': ['政黨', ['政 정사 정', '黨 무리 당']],
  '투표': ['投票', ['投 던질 투', '票 표 표']],
  '득표': ['得票', ['得 얻을 득', '票 표 표']],
  '여당': ['與黨', ['與 더불 여', '黨 무리 당']],
  '야당': ['野黨', ['野 들 야', '黨 무리 당']],
  '입법': ['立法', ['立 설 립', '法 법 법']],
  '삼권분립': ['三權分立', ['三 석 삼', '權 권세 권', '分 나눌 분', '立 설 립']],
  '민주주의': ['民主主義', ['民 백성 민', '主 주인 주', '主 주인 주', '義 옳을 의']],
  '공화국': ['共和國', ['共 한가지 공', '和 화할 화', '國 나라 국']],
  '국정감사': ['國政監査', ['國 나라 국', '政 정사 정', '監 볼 감', '査 조사할 사']],
  // ── Science and research ──────────────────────────────────────────────────
  '실험': ['實驗', ['實 열매 실', '驗 시험 험']],
  '이론': ['理論', ['理 이치 리', '論 논할 론']],
  '가설': ['假說', ['假 거짓 가', '說 말씀 설']],
  '검증': ['檢證', ['檢 검사할 검', '證 증거 증']],
  '발견': ['發見', ['發 필 발', '見 볼 견']],
  '발명': ['發明', ['發 필 발', '明 밝을 명']],
  '실험실': ['實驗室', ['實 열매 실', '驗 시험 험', '室 집 실']],
  '특허': ['特許', ['特 특별할 특', '許 허락할 허']],
  '물리': ['物理', ['物 물건 물', '理 이치 리']],
  '화학': ['化學', ['化 될 화', '學 배울 학']],
  '생물': ['生物', ['生 날 생', '物 물건 물']],
  '관측': ['觀測', ['觀 볼 관', '測 헤아릴 측']],
  '유전공학': ['遺傳工學', ['遺 남길 유', '傳 전할 전', '工 장인 공', '學 배울 학']],
  // ── Academic and technical terms ──────────────────────────────────────────
  '학술': ['學術', ['學 배울 학', '術 재주 술']],
  '반론': ['反論', ['反 돌이킬 반', '論 논할 론']],
  '논거': ['論據', ['論 논할 론', '據 근거 거']],
  '상형문자': ['象形文字', ['象 코끼리 상', '形 모양 형', '文 글 문', '字 글자 자']],
  '동음이의어': ['同音異義語', ['同 한가지 동', '音 소리 음', '異 다를 이', '義 옳을 의', '語 말씀 어']],
  '유의어': ['類義語', ['類 무리 류', '義 옳을 의', '語 말씀 어']],
  '반의어': ['反義語', ['反 돌이킬 반', '義 옳을 의', '語 말씀 어']],
  '다의어': ['多義語', ['多 많을 다', '義 옳을 의', '語 말씀 어']],
  '어원': ['語源', ['語 말씀 어', '源 근원 원']],
  '의미론': ['意味論', ['意 뜻 의', '味 맛 미', '論 논할 론']],
  '시사점': ['示唆點', ['示 보일 시', '唆 부추길 사', '點 점 점']],
  '방법론': ['方法論', ['方 모 방', '法 법 법', '論 논할 론']],
  '학술지': ['學術誌', ['學 배울 학', '術 재주 술', '誌 기록할 지']],
  // ── Social phenomena ──────────────────────────────────────────────────────
  '공동체': ['共同體', ['共 한가지 공', '同 한가지 동', '體 몸 체']],
  '대중': ['大衆', ['大 큰 대', '衆 무리 중']],
  '인구': ['人口', ['人 사람 인', '口 입 구']],
  '저출산': ['低出產', ['低 낮을 저', '出 날 출', '產 낳을 산']],
  '고령화': ['高齡化', ['高 높을 고', '齡 나이 령', '化 될 화']],
  '도시화': ['都市化', ['都 도읍 도', '市 저자 시', '化 될 화']],
  '현상': ['現象', ['現 나타날 현', '象 코끼리 상']],
  '추세': ['趨勢', ['趨 달아날 추', '勢 형세 세']],
  '동향': ['動向', ['動 움직일 동', '向 향할 향']],
  '실태': ['實態', ['實 열매 실', '態 모습 태']],
  '제안': ['提案', ['提 끌 제', '案 책상 안']],
  '개혁': ['改革', ['改 고칠 개', '革 가죽 혁']],
  '개선': ['改善', ['改 고칠 개', '善 착할 선']],
  '실천': ['實踐', ['實 열매 실', '踐 밟을 천']],
  '연대': ['連帶', ['連 이을 련', '帶 띠 대']],
  '통합': ['統合', ['統 거느릴 통', '合 합할 합']],
  '공익': ['公益', ['公 공평할 공', '益 더할 익']],

  // ── Conflict and reconciliation ───────────────────────────────────────────
  // 갈등 is two climbing plants that grow in opposite directions — the metaphor is the word.
  '갈등': ['葛藤', ['葛 칡 갈', '藤 등나무 등']],
  '대립': ['對立', ['對 대할 대', '立 설 립']],
  '오해': ['誤解', ['誤 그르칠 오', '解 풀 해']],
  '마찰': ['摩擦', ['摩 문지를 마', '擦 문지를 찰']],
  '불화': ['不和', ['不 아닐 불', '和 화할 화']],
  '언쟁': ['言爭', ['言 말씀 언', '爭 다툴 쟁']],
  '사과': ['謝過', ['謝 사례할 사', '過 지날 과']],
  '용서': ['容恕', ['容 얼굴 용', '恕 용서할 서']],
  '중재자': ['仲裁者', ['仲 버금 중', '裁 마를 재', '者 놈 자']],
  // ── Mental states ─────────────────────────────────────────────────────────
  '심리': ['心理', ['心 마음 심', '理 이치 리']],
  '정신': ['精神', ['精 정할 정', '神 귀신 신']],
  '공포': ['恐怖', ['恐 두려울 공', '怖 두려워할 포']],
  '우울증': ['憂鬱症', ['憂 근심 우', '鬱 답답할 울', '症 증세 증']],
  '동기부여': ['動機附與', ['動 움직일 동', '機 틀 기', '附 붙을 부', '與 더불 여']],
  '심리상태': ['心理狀態', ['心 마음 심', '理 이치 리', '狀 형상 상', '態 모습 태']],
  '정서': ['情緖', ['情 뜻 정', '緖 실마리 서']],
  '감정기복': ['感情起伏', ['感 느낄 감', '情 뜻 정', '起 일어날 기', '伏 엎드릴 복']],
  '수치심': ['羞恥心', ['羞 부끄러울 수', '恥 부끄러울 치', '心 마음 심']],
  '평정심': ['平靜心', ['平 평평할 평', '靜 고요할 정', '心 마음 심']],
  // ── Social problems ───────────────────────────────────────────────────────
  '양극화': ['兩極化', ['兩 두 량', '極 극진할 극', '化 될 화']],
  '빈부격차': ['貧富格差', ['貧 가난할 빈', '富 부자 부', '格 격식 격', '差 다를 차']],
  '범죄': ['犯罪', ['犯 범할 범', '罪 허물 죄']],
  '고독사': ['孤獨死', ['孤 외로울 고', '獨 홀로 독', '死 죽을 사']],
  '차별': ['差別', ['差 다를 차', '別 다를 별']],
  '편견': ['偏見', ['偏 치우칠 편', '見 볼 견']],
  '소외계층': ['疏外階層', ['疏 소통할 소', '外 바깥 외', '階 섬돌 계', '層 층 층']],
  '대책': ['對策', ['對 대할 대', '策 꾀 책']],
  '방안': ['方案', ['方 모 방', '案 책상 안']],
  '해결책': ['解決策', ['解 풀 해', '決 결단할 결', '策 꾀 책']],
  '갈등해소': ['葛藤解消', ['葛 칡 갈', '藤 등나무 등', '解 풀 해', '消 사라질 소']],
  '안전대책': ['安全對策', ['安 편안 안', '全 온전 전', '對 대할 대', '策 꾀 책']],
  // ── Workplace relationships ───────────────────────────────────────────────
  '경쟁': ['競爭', ['競 다툴 경', '爭 다툴 쟁']],
  '승진': ['昇進', ['昇 오를 승', '進 나아갈 진']],
  '퇴사': ['退社', ['退 물러날 퇴', '社 모임 사']],
  '이직': ['移職', ['移 옮길 이', '職 직분 직']],
  '상사': ['上司', ['上 윗 상', '司 맡을 사']],
  '부하': ['部下', ['部 떼 부', '下 아래 하']],
  '동료': ['同僚', ['同 한가지 동', '僚 동료 료']],
  '거래처': ['去來處', ['去 갈 거', '來 올 래', '處 곳 처']],
  '고객': ['顧客', ['顧 돌아볼 고', '客 손 객']],
  '전근': ['轉勤', ['轉 구를 전', '勤 부지런할 근']],
  '사기': ['士氣', ['士 선비 사', '氣 기운 기']],

  // ── Adverbs that read as native and are not ───────────────────────────────
  '우선': ['優先', ['優 넉넉할 우', '先 먼저 선']],
  '설령': ['設令', ['設 베풀 설', '令 하여금 령']],
  '심지어': ['甚至於', ['甚 심할 심', '至 이를 지', '於 어조사 어']],
  '단지': ['但只', ['但 다만 단', '只 다만 지']],
  '하필': ['何必', ['何 어찌 하', '必 반드시 필']],
  // ── Internet and social media ─────────────────────────────────────────────
  '계정': ['計定', ['計 셈할 계', '定 정할 정']],
  '비밀번호': ['祕密番號', ['祕 숨길 비', '密 빽빽할 밀', '番 차례 번', '號 이름 호']],
  '구독': ['購讀', ['購 살 구', '讀 읽을 독']],
  '영상': ['映像', ['映 비칠 영', '像 모양 상']],
  '검색창': ['檢索窓', ['檢 검사할 검', '索 찾을 색', '窓 창 창']],
  '검색엔진': ['檢索', ['檢 검사할 검', '索 찾을 색']],
  // ── Advanced technology ───────────────────────────────────────────────────
  '인공지능': ['人工知能', ['人 사람 인', '工 장인 공', '知 알 지', '能 능할 능']],
  '자율주행': ['自律走行', ['自 스스로 자', '律 법칙 률', '走 달릴 주', '行 다닐 행']],
  '우주항공': ['宇宙航空', ['宇 집 우', '宙 집 주', '航 배 항', '空 하늘 공']],
  '반도체': ['半導體', ['半 반 반', '導 인도할 도', '體 몸 체']],
  '생명공학': ['生命工學', ['生 날 생', '命 목숨 명', '工 장인 공', '學 배울 학']],
  '상용화': ['商用化', ['商 장사 상', '用 쓸 용', '化 될 화']],
  '융합': ['融合', ['融 녹을 융', '合 합할 합']],
  '자동화': ['自動化', ['自 스스로 자', '動 움직일 동', '化 될 화']],
  '첨단': ['尖端', ['尖 뾰족할 첨', '端 끝 단']],
  // ── Tradition and heritage ────────────────────────────────────────────────
  '국보': ['國寶', ['國 나라 국', '寶 보배 보']],
  '보물': ['寶物', ['寶 보배 보', '物 물건 물']],
  '역사': ['歷史', ['歷 지날 력', '史 사기 사']],
  '왕조': ['王朝', ['王 임금 왕', '朝 아침 조']],
  '신화': ['神話', ['神 귀신 신', '話 말씀 화']],
  '전설': ['傳說', ['傳 전할 전', '說 말씀 설']],
  '풍류': ['風流', ['風 바람 풍', '流 흐를 류']],
  '시대상': ['時代相', ['時 때 시', '代 대신할 대', '相 서로 상']],
  '사상': ['思想', ['思 생각 사', '想 생각 상']],
  '유교': ['儒敎', ['儒 선비 유', '敎 가르칠 교']],
  '불교': ['佛敎', ['佛 부처 불', '敎 가르칠 교']],

  // ── Housing and furniture ─────────────────────────────────────────────────
  '침대': ['寢臺', ['寢 잘 침', '臺 대 대']],
  '책상': ['冊床', ['冊 책 책', '床 평상 상']],
  '식탁': ['食卓', ['食 먹을 식', '卓 높을 탁']],
  '전세': ['傳貰', ['傳 전할 전', '貰 세낼 세']],
  '월세': ['月貰', ['月 달 월', '貰 세낼 세']],
  '매매': ['賣買', ['賣 팔 매', '買 살 매']],
  '보증금': ['保證金', ['保 지킬 보', '證 증거 증', '金 돈 금']],
  '계약서': ['契約書', ['契 맺을 계', '約 약속 약', '書 글 서']],
  '냉장고': ['冷藏庫', ['冷 찰 랭', '藏 감출 장', '庫 곳집 고']],
  '세탁기': ['洗濯機', ['洗 씻을 세', '濯 씻을 탁', '機 틀 기']],
  '청소기': ['淸掃機', ['淸 맑을 청', '掃 쓸 소', '機 틀 기']],
  '현관': ['玄關', ['玄 검을 현', '關 관계할 관']],
  '신축': ['新築', ['新 새 신', '築 쌓을 축']],
  '단독주택': ['單獨住宅', ['單 홑 단', '獨 홀로 독', '住 살 주', '宅 집 택']],
  // ── People and contact ────────────────────────────────────────────────────
  '지인': ['知人', ['知 알 지', '人 사람 인']],
  '선배': ['先輩', ['先 먼저 선', '輩 무리 배']],
  '후배': ['後輩', ['後 뒤 후', '輩 무리 배']],
  '제자': ['弟子', ['弟 아우 제', '子 아들 자']],
  '동창': ['同窓', ['同 한가지 동', '窓 창 창']],
  '인맥': ['人脈', ['人 사람 인', '脈 줄기 맥']],
  '인연': ['因緣', ['因 인할 인', '緣 인연 연']],
  '면담': ['面談', ['面 낯 면', '談 말씀 담']],
  '상담': ['相談', ['相 서로 상', '談 말씀 담']],
  '동반자': ['同伴者', ['同 한가지 동', '伴 짝 반', '者 놈 자']],

  // ── Fifth pass ────────────────────────────────────────────────────────────
  // Culture and leisure
  '독서': ['讀書', ['讀 읽을 독', '書 글 서']],
  '요리': ['料理', ['料 헤아릴 료', '理 이치 리']],
  '연극': ['演劇', ['演 펼칠 연', '劇 심할 극']],
  '전시회': ['展示會', ['展 펼 전', '示 보일 시', '會 모일 회']],
  '휴식': ['休息', ['休 쉴 휴', '息 쉴 식']],
  '동호회': ['同好會', ['同 한가지 동', '好 좋을 호', '會 모일 회']],
  '회원': ['會員', ['會 모일 회', '員 인원 원']],
  '관객': ['觀客', ['觀 볼 관', '客 손 객']],
  '무대': ['舞臺', ['舞 춤출 무', '臺 대 대']],
  '연주회': ['演奏會', ['演 펼칠 연', '奏 아뢸 주', '會 모일 회']],
  '악기연주': ['樂器演奏', ['樂 노래 악', '器 그릇 기', '演 펼칠 연', '奏 아뢸 주']],
  '사진촬영': ['寫眞撮影', ['寫 베낄 사', '眞 참 진', '撮 모을 촬', '影 그림자 영']],
  '취미생활': ['趣味生活', ['趣 뜻 취', '味 맛 미', '生 날 생', '活 살 활']],
  // Sightseeing
  '관광지': ['觀光地', ['觀 볼 관', '光 빛 광', '地 땅 지']],
  '유적지': ['遺蹟地', ['遺 남길 유', '蹟 자취 적', '地 땅 지']],
  '명소': ['名所', ['名 이름 명', '所 바 소']],
  '전망대': ['展望臺', ['展 펼 전', '望 바랄 망', '臺 대 대']],
  '기념품': ['記念品', ['記 기록할 기', '念 생각 념', '品 물건 품']],
  '특산물': ['特產物', ['特 특별할 특', '產 낳을 산', '物 물건 물']],
  '휴양지': ['休養地', ['休 쉴 휴', '養 기를 양', '地 땅 지']],
  '일출': ['日出', ['日 날 일', '出 날 출']],
  '일몰': ['日沒', ['日 날 일', '沒 빠질 몰']],
  '경치': ['景致', ['景 볕 경', '致 이를 치']],
  '풍경': ['風景', ['風 바람 풍', '景 볕 경']],
  '야경': ['夜景', ['夜 밤 야', '景 볕 경']],
  '추억': ['追憶', ['追 쫓을 추', '憶 생각할 억']],
  // Tasks and assignments
  '안건': ['案件', ['案 책상 안', '件 물건 건']],
  '기안서': ['起案書', ['起 일어날 기', '案 책상 안', '書 글 서']],
  '결재': ['決裁', ['決 결단할 결', '裁 마를 재']],
  '승인': ['承認', ['承 이을 승', '認 알 인']],
  '출장': ['出張', ['出 날 출', '張 베풀 장']],
  '야근': ['夜勤', ['夜 밤 야', '勤 부지런할 근']],
  '특근': ['特勤', ['特 특별할 특', '勤 부지런할 근']],
  '연차': ['年次', ['年 해 년', '次 버금 차']],
  '휴가': ['休暇', ['休 쉴 휴', '暇 겨레 가']],
  '성과': ['成果', ['成 이룰 성', '果 열매 과']],
  '연봉': ['年俸', ['年 해 년', '俸 녹 봉']],
  '월급': ['月給', ['月 달 월', '給 줄 급']],
  '근태': ['勤怠', ['勤 부지런할 근', '怠 게으를 태']],
  // Customs and performance
  '풍습': ['風習', ['風 바람 풍', '習 익힐 습']],
  '명절': ['名節', ['名 이름 명', '節 마디 절']],
  '추석': ['秋夕', ['秋 가을 추', '夕 저녁 석']],
  '한복': ['韓服', ['韓 한국 한', '服 옷 복']],
  '한옥': ['韓屋', ['韓 한국 한', '屋 집 옥']],
  '국악': ['國樂', ['國 나라 국', '樂 노래 악']],
  '국립극장': ['國立劇場', ['國 나라 국', '立 설 립', '劇 심할 극', '場 마당 장']],
  '민속': ['民俗', ['民 백성 민', '俗 풍속 속']],
  // Sports
  '축구': ['蹴球', ['蹴 찰 축', '球 공 구']],
  '농구': ['籠球', ['籠 대바구니 롱', '球 공 구']],
  '야구': ['野球', ['野 들 야', '球 공 구']],
  '배구': ['排球', ['排 밀칠 배', '球 공 구']],
  '수영': ['水泳', ['水 물 수', '泳 헤엄칠 영']],
  '등산': ['登山', ['登 오를 등', '山 메 산']],
  '태권도': ['跆拳道', ['跆 밟을 태', '拳 주먹 권', '道 길 도']],
  // Trip preparation
  '여권': ['旅券', ['旅 나그네 려', '券 문서 권']],
  '항공권': ['航空券', ['航 배 항', '空 하늘 공', '券 문서 권']],
  '배낭': ['背囊', ['背 등 배', '囊 주머니 낭']],
  '세면도구': ['洗面道具', ['洗 씻을 세', '面 낯 면', '道 길 도', '具 갖출 구']],
  '환전': ['換錢', ['換 바꿀 환', '錢 돈 전']],
  '일정표': ['日程表', ['日 날 일', '程 한도 정', '表 겉 표']],
  '지도': ['地圖', ['地 땅 지', '圖 그림 도']],
  '여비': ['旅費', ['旅 나그네 려', '費 쓸 비']],
  // Transport
  '기차': ['汽車', ['汽 물끓는김 기', '車 수레 차']],
  '비행기': ['飛行機', ['飛 날 비', '行 다닐 행', '機 틀 기']],
  '자전거': ['自轉車', ['自 스스로 자', '轉 구를 전', '車 수레 차']],
  '선박': ['船舶', ['船 배 선', '舶 큰배 박']],
  '승용차': ['乘用車', ['乘 탈 승', '用 쓸 용', '車 수레 차']],

  // Accommodation and border crossing
  '민박': ['民泊', ['民 백성 민', '泊 머무를 박']],
  '객실': ['客室', ['客 손 객', '室 집 실']],
  '탑승구': ['搭乘口', ['搭 탈 탑', '乘 탈 승', '口 입 구']],
  '기내': ['機內', ['機 틀 기', '內 안 내']],
  '수하물': ['手荷物', ['手 손 수', '荷 짐 하', '物 물건 물']],
  '출국': ['出國', ['出 날 출', '國 나라 국']],
  '입국': ['入國', ['入 들 입', '國 나라 국']],
  '세관': ['稅關', ['稅 세금 세', '關 관계할 관']],
  // Housework, bills and the neighbourhood
  '정리정돈': ['整理整頓', ['整 가지런할 정', '理 이치 리', '整 가지런할 정', '頓 조을 돈']],
  '분리수거': ['分離收去', ['分 나눌 분', '離 떠날 리', '收 거둘 수', '去 갈 거']],
  '관리비': ['管理費', ['管 대롱 관', '理 이치 리', '費 쓸 비']],
  '수도세': ['水道稅', ['水 물 수', '道 길 도', '稅 세금 세']],
  '전기세': ['電氣稅', ['電 번개 전', '氣 기운 기', '稅 세금 세']],
  '파출소': ['派出所', ['派 갈래 파', '出 날 출', '所 바 소']],
  '산책로': ['散策路', ['散 흩을 산', '策 꾀 책', '路 길 로']],
  '경비실': ['警備室', ['警 경계할 경', '備 갖출 비', '室 집 실']],
  '주차시설': ['駐車施設', ['駐 살 주', '車 수레 차', '施 베풀 시', '設 베풀 설']],
  '편의시설': ['便宜施設', ['便 편할 편', '宜 마땅 의', '施 베풀 시', '設 베풀 설']],
  '층간소음': ['層間騷音', ['層 층 층', '間 사이 간', '騷 떠들 소', '音 소리 음']],
  '통풍': ['通風', ['通 통할 통', '風 바람 풍']],
  '방음': ['防音', ['防 막을 방', '音 소리 음']],
  '수전': ['水栓', ['水 물 수', '栓 마개 전']],
  '통화': ['通話', ['通 통할 통', '話 말씀 화']],
  // Press and broadcasting
  '잡지': ['雜誌', ['雜 섞일 잡', '誌 기록할 지']],
  '언론': ['言論', ['言 말씀 언', '論 논할 론']],
  '기사': ['記事', ['記 기록할 기', '事 일 사']],
  '기자': ['記者', ['記 기록할 기', '者 놈 자']],
  '속보': ['速報', ['速 빠를 속', '報 알릴 보']],
  '저작권': ['著作權', ['著 나타날 저', '作 지을 작', '權 권세 권']],
  '매체': ['媒體', ['媒 중매 매', '體 몸 체']],
  // Manners and etiquette
  '경어': ['敬語', ['敬 공경할 경', '語 말씀 어']],
  '인사': ['人事', ['人 사람 인', '事 일 사']],
  '악수': ['握手', ['握 쥘 악', '手 손 수']],
  '덕망': ['德望', ['德 덕 덕', '望 바랄 망']],
  '태도': ['態度', ['態 모습 태', '度 법도 도']],
  '행동': ['行動', ['行 다닐 행', '動 움직일 동']],
  '습관': ['習慣', ['習 익힐 습', '慣 익숙할 관']],
  '배려심': ['配慮心', ['配 나눌 배', '慮 생각할 려', '心 마음 심']],
  // Welfare and institutions
  '복지': ['福祉', ['福 복 복', '祉 복 지']],
  '국민연금': ['國民年金', ['國 나라 국', '民 백성 민', '年 해 년', '金 돈 금']],
  '육아휴직': ['育兒休職', ['育 기를 육', '兒 아이 아', '休 쉴 휴', '職 직분 직']],
  '혜택': ['惠澤', ['惠 은혜 혜', '澤 못 택']],
  '봉사활동': ['奉仕活動', ['奉 받들 봉', '仕 섬길 사', '活 살 활', '動 움직일 동']],
  '기부': ['寄附', ['寄 부칠 기', '附 붙을 부']],
  '법률': ['法律', ['法 법 법', '律 법칙 률']],
  '시책': ['施策', ['施 베풀 시', '策 꾀 책']],
  '권리': ['權利', ['權 권세 권', '利 이로울 리']],
  '의무': ['義務', ['義 옳을 의', '務 힘쓸 무']],
  // Trade, industry and markets
  '유통': ['流通', ['流 흐를 류', '通 통할 통']],
  '수요': ['需要', ['需 쓰일 수', '要 요긴할 요']],
  '공급': ['供給', ['供 이바지할 공', '給 줄 급']],
  '상권': ['商圈', ['商 장사 상', '圈 우리 권']],
  '수출': ['輸出', ['輸 보낼 수', '出 날 출']],
  '수입': ['輸入', ['輸 보낼 수', '入 들 입']],
  '관세': ['關稅', ['關 관계할 관', '稅 세금 세']],
  '통상': ['通商', ['通 통할 통', '商 장사 상']],
  '물류': ['物流', ['物 물건 물', '流 흐를 류']],
  // Energy and environment
  '효율': ['效率', ['效 본받을 효', '率 비율 률']],
  '태양광': ['太陽光', ['太 클 태', '陽 볕 양', '光 빛 광']],
  '화석연료': ['化石燃料', ['化 될 화', '石 돌 석', '燃 탈 연', '料 헤아릴 료']],
  '신재생': ['新再生', ['新 새 신', '再 두 재', '生 날 생']],
  '동식물': ['動植物', ['動 움직일 동', '植 심을 식', '物 물건 물']],
  '야생동물': ['野生動物', ['野 들 야', '生 날 생', '動 움직일 동', '物 물건 물']],
  '서식지': ['棲息地', ['棲 살 서', '息 쉴 식', '地 땅 지']],
  '삼림': ['森林', ['森 수풀 삼', '林 수풀 림']],
  '해양': ['海洋', ['海 바다 해', '洋 큰바다 양']],
  '미세먼지': ['微細', ['微 작을 미', '細 가늘 세']],
  '유해물질': ['有害物質', ['有 있을 유', '害 해할 해', '物 물건 물', '質 바탕 질']],
  '보전': ['保全', ['保 지킬 보', '全 온전 전']],
  '탄소중립': ['炭素中立', ['炭 숯 탄', '素 본디 소', '中 가운데 중', '立 설 립']],
  '지구온난화': ['地球溫暖化', ['地 땅 지', '球 공 구', '溫 따뜻할 온', '暖 따뜻할 난', '化 될 화']],
  '자원순환': ['資源循環', ['資 재물 자', '源 근원 원', '循 돌 순', '環 고리 환']],
  '일회용품': ['一回用品', ['一 한 일', '回 돌아올 회', '用 쓸 용', '品 물건 품']],
  '방사능': ['放射能', ['放 놓을 방', '射 쏠 사', '能 능할 능']],
  '산성비': ['酸性', ['酸 실 산', '性 성품 성']],
  '자외선': ['紫外線', ['紫 자줏빛 자', '外 바깥 외', '線 줄 선']],
  '오존층': ['層', ['層 층 층']],
  '사막화': ['沙漠化', ['沙 모래 사', '漠 넓을 막', '化 될 화']],
  '빙하': ['氷河', ['氷 얼음 빙', '河 물 하']],
  '해수면': ['海水面', ['海 바다 해', '水 물 수', '面 낯 면']],
  '홍수': ['洪水', ['洪 넓을 홍', '水 물 수']],
  '가뭄': ['旱', ['旱 마를 한']],
  '지진': ['地震', ['地 땅 지', '震 우레 진']],
  '보전활동': ['保全活動', ['保 지킬 보', '全 온전 전', '活 살 활', '動 움직일 동']],
  '지속가능': ['持續可能', ['持 가질 지', '續 이을 속', '可 옳을 가', '能 능할 능']],
  // Art and literature
  '무용': ['舞踊', ['舞 춤출 무', '踊 뛸 용']],
  '시': ['詩', ['詩 시 시']],
  '소설': ['小說', ['小 작을 소', '說 말씀 설']],
  '수필': ['隨筆', ['隨 따를 수', '筆 붓 필']],
  '회화': ['繪畫', ['繪 그림 회', '畫 그림 화']],
  '조각': ['彫刻', ['彫 새길 조', '刻 새길 각']],
  '판소리': ['板', ['板 널 판']],
  '서예': ['書藝', ['書 글 서', '藝 재주 예']],
  '도자기': ['陶瓷器', ['陶 질그릇 도', '瓷 사기그릇 자', '器 그릇 기']],
  '공예': ['工藝', ['工 장인 공', '藝 재주 예']],
  '전시관': ['展示館', ['展 펼 전', '示 보일 시', '館 집 관']],
  '서양화': ['西洋畫', ['西 서녘 서', '洋 큰바다 양', '畫 그림 화']],
  '작품': ['作品', ['作 지을 작', '品 물건 품']],
  '미술': ['美術', ['美 아름다울 미', '術 재주 술']],
  '관용어': ['慣用語', ['慣 익숙할 관', '用 쓸 용', '語 말씀 어']],
  '함흥차사': ['咸興差使', ['咸 다 함', '興 일 흥', '差 다를 차', '使 부릴 사']],
  // Concepts, logic and values
  '사고': ['思考', ['思 생각 사', '考 상고할 고']],
  '논리': ['論理', ['論 논할 론', '理 이치 리']],
  '법칙': ['法則', ['法 법 법', '則 법칙 칙']],
  '구조': ['構造', ['構 얽을 구', '造 지을 조']],
  '체계': ['體系', ['體 몸 체', '系 이을 계']],
  '본질': ['本質', ['本 근본 본', '質 바탕 질']],
  '요소': ['要素', ['要 요긴할 요', '素 본디 소']],
  '차원': ['次元', ['次 버금 차', '元 으뜸 원']],
  '규범': ['規範', ['規 법 규', '範 법 범']],
  '윤리': ['倫理', ['倫 인륜 륜', '理 이치 리']],
  '도덕': ['道德', ['道 길 도', '德 덕 덕']],
  '정의': ['正義', ['正 바를 정', '義 옳을 의']],
  '평등': ['平等', ['平 평평할 평', '等 무리 등']],
  '세계관': ['世界觀', ['世 인간 세', '界 지경 계', '觀 볼 관']],
  '상호작용': ['相互作用', ['相 서로 상', '互 서로 호', '作 지을 작', '用 쓸 용']],
  '양심': ['良心', ['良 좋을 량', '心 마음 심']],
  '자긍심': ['自矜心', ['自 스스로 자', '矜 자랑할 긍', '心 마음 심']],
  '호남형': ['好男型', ['好 좋을 호', '男 사내 남', '型 모형 형']],
  // Prefixes and suffixes
  '재활용': ['再活用', ['再 두 재', '活 살 활', '用 쓸 용']],
  '비공식': ['非公式', ['非 아닐 비', '公 공평할 공', '式 법 식']],
  '불확실': ['不確實', ['不 아닐 불', '確 굳을 확', '實 열매 실']],
  '대규모': ['大規模', ['大 큰 대', '規 법 규', '模 본뜰 모']],
  '소규모': ['小規模', ['小 작을 소', '規 법 규', '模 본뜰 모']],
  '고성능': ['高性能', ['高 높을 고', '性 성품 성', '能 능할 능']],
  '저임금': ['低賃金', ['低 낮을 저', '賃 품삯 임', '金 돈 금']],
  '파생어': ['派生語', ['派 갈래 파', '生 날 생', '語 말씀 어']],
  // Administration and citizens
  '지자체': ['地自體', ['地 땅 지', '自 스스로 자', '體 몸 체']],
  '지방자치': ['地方自治', ['地 땅 지', '方 모 방', '自 스스로 자', '治 다스릴 치']],
  '공무원': ['公務員', ['公 공평할 공', '務 힘쓸 무', '員 인원 원']],
  '규제': ['規制', ['規 법 규', '制 제도 제']],
  '완화': ['緩和', ['緩 느릴 완', '和 화할 화']],
  '청원': ['請願', ['請 청할 청', '願 원할 원']],
  '공청회': ['公聽會', ['公 공평할 공', '聽 들을 청', '會 모일 회']],
  '인권': ['人權', ['人 사람 인', '權 권세 권']],
  '민원인': ['民願人', ['民 백성 민', '願 원할 원', '人 사람 인']],
  '법률안': ['法律案', ['法 법 법', '律 법칙 률', '案 책상 안']],
  '조례': ['條例', ['條 가지 조', '例 법식 례']],
  '의결': ['議決', ['議 의논할 의', '決 결단할 결']],
  '고시': ['告示', ['告 알릴 고', '示 보일 시']],
  '심의': ['審議', ['審 살필 심', '議 의논할 의']],
  // Logical connectives
  '즉': ['卽', ['卽 곧 즉']],
  '결국': ['結局', ['結 맺을 결', '局 판 국']],
  '만약': ['萬若', ['萬 일만 만', '若 같을 약']],
  // Remaining odds and ends
  '거스름돈': ['錢', ['錢 돈 전']],
  '영양제': ['營養劑', ['營 경영할 영', '養 기를 양', '劑 약제 제']],
  '주황색': ['朱黃色', ['朱 붉을 주', '黃 누를 황', '色 빛 색']],
  '분홍색': ['粉紅色', ['粉 가루 분', '紅 붉을 홍', '色 빛 색']],
  '최고': ['最高', ['最 가장 최', '高 높을 고']],
  '수강신청': ['受講申請', ['受 받을 수', '講 익힐 강', '申 펼 신', '請 청할 청']],
  '학업성취': ['學業成就', ['學 배울 학', '業 업 업', '成 이룰 성', '就 나아갈 취']],
  '제출기한': ['提出期限', ['提 끌 제', '出 날 출', '期 기약할 기', '限 한할 한']],
  '학과사무실': ['學科事務室', ['學 배울 학', '科 과목 과', '事 일 사', '務 힘쓸 무', '室 집 실']],
  '진행상황': ['進行狀況', ['進 나아갈 진', '行 다닐 행', '狀 형상 상', '況 상황 황']],
  '가계부채': ['家計負債', ['家 집 가', '計 셈할 계', '負 짐질 부', '債 빚 채']],
  '건너편': ['便', ['便 편할 편']],
  '맞은편': ['便', ['便 편할 편']],
  '미식가': ['美食家', ['美 아름다울 미', '食 먹을 식', '家 집 가']],
  // Enables the -하다 rule for 상하다 (傷하다). One-syllable entries never cascade into
  // compounds — SINO_ROOTS_BY_LEN filters to two syllables and up — so this cannot mislabel
  // anything else that happens to contain 상.
  '상': ['傷', ['傷 다칠 상']],
};

// Sino-Korean root + native Korean suffix.
const MIXED = {
  '남동생': ['男', ['男 사내 남'], '동생'],
  '여동생': ['女', ['女 계집 녀'], '동생'],
  '동쪽': ['東', ['東 동녘 동'], '쪽'],
  '서쪽': ['西', ['西 서녘 서'], '쪽'],
  '남쪽': ['南', ['南 남녘 남'], '쪽'],
  '북쪽': ['北', ['北 북녘 북'], '쪽'],
  // Fifth pass — Sino first, native second.
  '칫솔': ['齒', ['齒 이 치'], '솔'],
  '게시글': ['揭示', ['揭 걸 게', '示 보일 시'], '글'],
  '민속놀이': ['民俗', ['民 백성 민', '俗 풍속 속'], '놀이'],
  '사물놀이': ['四物', ['四 넉 사', '物 물건 물'], '놀이'],
  '교수님': ['敎授', ['敎 가르칠 교', '授 줄 수'], '님'],
  '신경쓰다': ['神經', ['神 귀신 신', '經 지날 경'], '쓰다'],
  '초조함': ['焦燥', ['焦 탈 초', '燥 마를 조'], '함'],
  '해양쓰레기': ['海洋', ['海 바다 해', '洋 큰바다 양'], '쓰레기'],
  '이웃사촌': ['四寸', ['四 넉 사', '寸 마디 촌'], '이웃'],
  '자전거 타기': ['自轉車', ['自 스스로 자', '轉 구를 전', '車 수레 차'], '타기'],
  // Sino noun + native predicate. These are collocations rather than idioms, so the halves are
  // worth showing plainly instead of a "literally …" gloss.
  '진료받다': ['診療', ['診 진찰할 진', '療 병고칠 료'], '받다'],
  '주사를 맞다': ['注射', ['注 대댈 주', '射 쏠 사'], '를 맞다'],
  '사진을 찍다': ['寫眞', ['寫 베낄 사', '眞 참 진'], '을 찍다'],
  '고집이 세다': ['固執', ['固 굳을 고', '執 잡을 집'], '이 세다'],
  '피로를 풀다': ['疲勞', ['疲 피곤할 피', '勞 일할 로'], '를 풀다'],
  '특히': ['特', ['特 특별할 특'], '히'],
  '종합해 보면': ['綜合', ['綜 모을 종', '合 합할 합'], '해 보면'],
  // 댓글's first element is usually traced to 對; the 글 is native either way.
  '댓글': ['對', ['對 대할 대'], '글'],
};

// Sino-Korean root + English loanword.
const MIXED_LOAN = {
  '신용카드': ['信用', ['信 믿을 신', '用 쓸 용'], 'card'],
  '방수팩': ['防水', ['防 막을 방', '水 물 수'], 'pack'],
  '온실가스': ['溫室', ['溫 따뜻할 온', '室 집 실'], 'gas'],
  '지도앱': ['地圖', ['地 땅 지', '圖 그림 도'], 'app'],
  '가스비': ['費', ['費 쓸 비'], 'gas'],
  '양자 컴퓨팅': ['量子', ['量 헤아릴 량', '子 아들 자'], 'computing'],
  '검색엔진': ['檢索', ['檢 검사할 검', '索 찾을 색'], 'engine'],
  '마케팅부': ['部', ['部 떼 부'], 'marketing'],
};

// Loanword first, Sino second — the mirror of MIXED_LOAN.
const LOAN_MIXED = {
  '가스비': ['費', ['費 쓸 비'], 'gas'],
  '마케팅부': ['部', ['部 떼 부'], 'marketing'],
};

// Native + Sino, in that order. Kept apart from MIXED because the panel prints the halves in
// the order the word actually has them, and 옷장 is 옷 first.
const MIXED_NATIVE = {
  '옷장': ['欌', ['欌 장롱 장'], '옷'],
  '알약': ['藥', ['藥 약 약'], '알'],
  '물약': ['藥', ['藥 약 약'], '물'],
  '보라색': ['色', ['色 빛 색'], '보라'],
  '지난주': ['週', ['週 돌 주'], '지난'],
  '이번주': ['週', ['週 돌 주'], '이번'],
  '알권리': ['權利', ['權 권세 권', '利 이로울 리'], '알'],
};

// Native Korean words with a note worth keeping (the rest just get o:'native').
const NATIVE_NOTE = {
  '과일': 'naturalised in Korean; related to the Sino-Korean 果實 (과실), but no longer read that way',
  '아버지': 'respectful term for one\'s father',
  '어머니': 'respectful term for one\'s mother',
  '할아버지': 'grandfather; also used for any elderly man',
  '할머니': 'grandmother; also used for any elderly woman',
};

// Native Korean words that need no further comment. "Native Korean (고유어)" on its own is
// the useful fact — it tells the learner there is no hanja to look for, which is most of what
// the origin panel is for.
//
// This is a checked list, not a default. The data this project inherited asserted 고유어 for
// ~1,090 words with no evidence and mislabelled a great deal of Sino-Korean along the way, so
// every entry here was read against its English gloss first. The words that trip people up are
// the ones that *look* native and are not — 내일 (來日), 점심 (點心), 양말 (洋襪), 지갑 (紙匣),
// 시계 (時計), 안경 (眼鏡), 감기 (感氣), 항상 (恒常), 냉면 (冷麵), 반찬 (飯饌) — and those are
// curated in SINO below rather than swept in here.
const NATIVE_SET = [
  // Body
  '머리', '눈', '코', '입', '귀', '얼굴', '목', '어깨', '팔', '손', '손가락', '가슴', '배',
  '허리', '다리', '발', '발가락', '콧물', '붓기', '기침', '흉터',
  // Position and direction
  '앞', '뒤', '위', '아래', '옆', '사이', '안', '밖', '오른쪽', '왼쪽', '구석', '모퉁이',
  // Weather and seasons
  '봄', '여름', '가을', '겨울', '날씨', '맑음', '흐림', '비', '함박눈', '바람', '장마',
  '맑다', '흐리다', '춥다', '덥다',
  // Time
  '오늘', '어제', '모레', '글피', '아침', '저녁', '밤', '새벽', '올해',
  // Food
  '밥', '국', '찌개', '김치', '불고기', '비빔밥', '떡볶이', '삼겹살', '갈비', '튀김',
  // Objects and clothing
  // 구두 is left out: it most likely reached Korean through Japanese くつ, and "probably a
  // loanword" is not something to assert on a flashcard.
  '옷', '바지', '치마', '신발', '목도리', '가방',
  // Colour and shape
  '빨간색', '파란색', '노란색', '초록색', '하얀색', '검은색', '동그랗다', '넓다', '좁다',
  '두껍다', '얇다', '가볍다',
  // Everyday actions
  '자다', '먹다', '마시다', '보다', '듣다', '읽다', '쓰다', '말하다', '걷다', '달리다',
  '쉬다', '씻다', '입다', '벗다', '웃다', '울다', '살다',
  // Appearance
  '키', '머릿결', '쌍꺼풀', '차림새', '겉모습', '옷차림',
  // Time adverbs
  '일찍', '늦게', '벌써', '아직', '자주', '가끔', '늘', '갑자기', '이미',
  // Misc native nouns confirmed against their glosses
  '동아리', '스승', '색깔',
  // Fourth pass. 침대 (寢臺), 책상 (冊床), 식탁 (食卓), 전세 (傳貰), 월세 (月貰) and 지인 (知人)
  // were drafted into this list and pulled back out — they are Sino-Korean and are curated as
  // such below. 옷장, 게시글, 민속놀이 and 댓글 are native+Sino compounds and stay `unknown`
  // rather than being forced into either bucket.
  '다툼', '싸움', '말다툼', '외로움', '낚시', '둘러보다', '집들이', '좋아요',
  '탈춤', '가락', '이웃', '누나', '오빠', '언니', '조카',
  // Fifth pass — basic native predicates and nouns
  '좋다', '크다', '작다', '많다', '적다', '길다', '짧다', '높다', '낮다', '귀엽다',
  '차갑다', '비싸다', '싸다', '아쉽다', '외롭다', '두렵다', '무섭다', '착하다',
  '덤벙대다', '까다롭다', '설레다', '벅차다', '보람차다', '갈아타다', '쓸다', '닦다',
  '손님', '젓가락', '숟가락', '접시', '쓴맛', '버릇', '집안일', '동네', '놀이터',
  '햇빛', '알림', '나눔', '존댓말', '반말', '절', '지난달', '이번달',
  '그림 그리기', '숲 가꾸기', '산불', '설날',
];
const NATIVE_LOOKUP = new Set(NATIVE_SET);

const LOANWORDS = {
  '컵': 'cup',
  // Third curation pass. 파스 arrived through Japanese パス rather than straight from English,
  // which is why its English gloss ("pain relief patch") looks nothing like the Korean.
  '인턴': 'intern',           '커리큘럼': 'curriculum',   '파스': 'pas (adhesive pain patch, via Japanese)',
  '헬스': 'health (gym)',      '스키': 'ski',             '캠핑': 'camping',
  '보너스': 'bonus',          '펜션': 'pension (holiday cottage)', '프론트': 'front (reception desk)',
  '렌터카': 'rent-a-car',      '빌라': 'villa',           '원룸': 'one-room (studio flat)',
  '에어컨': 'air conditioner', '이슈': 'issue',           '마케팅': 'marketing',
  // Fourth pass.
  '아파트': 'apart(ment)',     '오피스텔': 'office + hotel (Korean coinage)',
  '소파': 'sofa',             '보일러': 'boiler',        '베란다': 'veranda',
  '도어락': 'door lock',       '로봇': 'robot',           '드론': 'drone',
  '디지털': 'digital',         '센서': 'sensor',          '트라우마': 'trauma',
  '피드백': 'feedback',        '해킹': 'hacking',         '다운로드': 'download',
  '뮤지컬': 'musical',         '가이드': 'guide',         '유네스코': 'UNESCO',
  '알고리즘': 'algorithm',
  // Attribution stated with its uncertainty rather than left blank: 구두 is usually traced to
  // Japanese くつ, but it is not settled, and saying so is more use than saying nothing.
  '구두': 'kutsu (Japanese くつ) — the usual attribution, though not settled',
  // Fifth pass. 라면 came via Japanese ラーメン from Chinese 拉麵, not from English.
  '라면': 'ramen (Japanese ラーメン, from Chinese 拉麵)',
  '조깅': 'jogging',          '요가': 'yoga',            '마라톤': 'marathon',
  '비자': 'visa',             '체크인': 'check-in',       '체크아웃': 'check-out',
  '시티투어': 'city tour',     '매너': 'manners',         '와이파이': 'Wi-Fi',
  '아나운서': 'announcer',     '헤드라인': 'headline',     '에티켓': 'etiquette',
  '에너지': 'energy',         '배터리': 'battery',        '플라스틱': 'plastic',
  '메커니즘': 'mechanism',     '패러다임': 'paradigm',     '딜레마': 'dilemma',
  '커피': 'coffee', '빵': 'pão (Portuguese, via Japanese)', '마트': 'mart',
  '버스': 'bus', '택시': 'taxi', '셔츠': 'shirt', '코트': 'coat',
  '점퍼': 'jumper', '스마트폰': 'smartphone', '인터넷': 'internet',
  'SNS': 'SNS (social networking service)', 'PD': 'PD (producer/director)',
  '뉴스': 'news', '드라마': 'drama', '라디오': 'radio', '텔레비전': 'television',
  '컴퓨터': 'computer', '이메일': 'e-mail', '블로그': 'blog', '스포츠': 'sports',
  '테니스': 'tennis', '골프': 'golf', '피자': 'pizza', '햄버거': 'hamburger',
  '아이스크림': 'ice cream', '초콜릿': 'chocolate', '케이크': 'cake',
  '샌드위치': 'sandwich', '콜라': 'cola', '사이다': 'cider', '맥주': 'beer',
  '위스키': 'whisky', '뷔페': 'buffet', '메뉴': 'menu', '호텔': 'hotel',
  '리조트': 'resort', '모텔': 'motel', '패션': 'fashion', '스타일': 'style',
  '디자인': 'design', '팀': 'team', '게이머': 'gamer', '게임': 'game',
  '데이터': 'data', '시스템': 'system', '네트워크': 'network', '사이트': 'site',
  '메시지': 'message', '세일': 'sale', '메뉴판': 'menu (board)', '카메라': 'camera',
  '샤워': 'shower', '샴푸': 'shampoo', '비누': 'soap (Portuguese sabão)',
  '티셔츠': 'T-shirt', '청바지': 'jeans', '슬리퍼': 'slipper', '넥타이': 'necktie',
  '와이셔츠': 'white shirt', '원피스': 'one-piece dress', '스커트': 'skirt',
  '재킷': 'jacket', '패딩': 'padding (padded coat)', '핸드폰': 'hand phone',
  '노트북': 'notebook (laptop)', '모니터': 'monitor', '키보드': 'keyboard',
  '마우스': 'mouse', '마이크': 'mic', '헤드폰': 'headphone', '이어폰': 'earphone',
  '스피커': 'speaker', '택배': 'parcel delivery', '서비스': 'service',
  '이벤트': 'event', '캠페인': 'campaign', '아이디어': 'idea', '스트레스': 'stress',
  '다이어트': 'diet', '비키니': 'bikini', '선글라스': 'sunglasses',
  '립스틱': 'lipstick', '파운데이션': 'foundation', '마스크': 'mask',
  '시즌': 'season', '매치': 'match', '골': 'goal', '패스': 'pass', '슛': 'shoot',
  '코치': 'coach', '매니저': 'manager', '프로': 'pro', '팬': 'fan',
  '콘서트': 'concert', '밴드': 'band', '아티스트': 'artist',
};

// Second curation pass. Words verified against levels.json rather than recalled: an
// earlier heuristic sweep flagged 수업 / 졸업 / 기업 / 실업 / 제조업 as loanwords purely
// because they end in 업, when all of them are Sino-Korean (授業, 卒業, 企業, 失業, 製造業).
Object.assign(LOANWORDS, {
  '오토바이': 'auto-bicycle (motorcycle)', '힐링': 'healing',
  '캐리어': 'carrier (suitcase)',          '게스트하우스': 'guest house',
  '앱': 'app',                             '애플리케이션': 'application',
  '웹사이트': 'website',                    '업로드': 'upload',
  '스트리밍': 'streaming',                  '데이터베이스': 'database',
  '바이러스': 'virus',                      '콘텐츠': 'contents',
  '미디어': 'media',                        '팟캐스트': 'podcast',
  '인플레이션': 'inflation',                '빅데이터': 'big data',
  '시뮬레이션': 'simulation',               '리모델링': 'remodeling',
  '인테리어': 'interior',                   '데이터': 'data',
  '센터': 'center',                         '프로그램': 'program',
  '프린팅': 'printing',                     '업사이클링': 'upcycling',
  '소셜 미디어': 'social media',            '스마트 시티': 'smart city',
});

// 맥주 and 택배 are Sino-Korean, not loanwords — the old list mis-tagged them.
delete LOANWORDS['맥주'];
delete LOANWORDS['택배'];

// Native Korean predicates. Listed explicitly rather than inferred from the ending, because
// several endings attach happily to Sino roots — 만족스럽다 is 滿足 + 스럽다 and 예의 바르다
// is 禮儀 + 바르다, so a blanket "-스럽다 means native" rule would mislabel them. The `note`
// records which native ending is doing the work.
const NATIVE_PREDICATES = {
  '일어나다': 'native verb stem in -나다 (to arise)',
  '만나다': 'native verb stem in -나다',
  '신나다': 'native verb stem in -나다 (spirit rising)',
  '화나다': '화 (anger) + native -나다',
  '짜증나다': '짜증 (irritation) + native -나다',
  '네모나다': '네모 (four corners) + native -나다',
  '세모나다': '세모 (three corners) + native -나다',
  '헤어지다': 'native verb stem in -지다',
  '기름지다': '기름 (oil) + native -지다',
  '건방지다': 'native adjective in -지다',
  '바쁘다': 'native adjective stem in -쁘다',
  '기쁘다': 'native adjective stem in -쁘다',
  '나쁘다': 'native adjective stem in -쁘다',
  '예쁘다': 'native adjective stem in -쁘다',
  '슬프다': 'native adjective stem in -프다',
  '배고프다': '배 (belly) + native -고프다',
  '더럽다': 'native adjective stem in -럽다',
  '부끄럽다': 'native adjective stem in -럽다',
  '부럽다': 'native adjective stem in -럽다',
  '싱겁다': 'native adjective stem in -겁다',
  '뜨겁다': 'native adjective stem in -겁다',
  '무겁다': 'native adjective stem in -겁다',
  '즐겁다': 'native adjective stem in -겁다',
  '배부르다': '배 (belly) + native 부르다 (to be full)',
  '목마르다': '목 (throat) + native 마르다 (to dry)',
  '마르다': 'native verb 마르다 (to dry, to thin)',
  '머무르다': 'native verb stem in -르다',
  '맛있다': '맛 (taste) + 있다 (to exist)',
  '맛없다': '맛 (taste) + 없다 (to not exist)',
  '재미있다': '재미 (fun) + 있다 (to exist)',
  '뉘우치다': 'native verb 뉘우치다',
  '챙기다': 'native verb 챙기다',
};

// Idioms. Native by construction, and worth a gloss because the literal reading is the point.
const IDIOMS = {
  '배가 아프다': 'literally "the belly hurts" — to be envious of someone else\'s good fortune',
  '어깨가 무겁다': 'literally "the shoulders are heavy" — to carry a weighty responsibility',
  '눈코 뜰 새 없이 바쁘다': 'literally "no time to open eyes or nose" — frantically busy',
  '귀를 기울이다': 'literally "to tilt the ear" — to listen closely',
  '뼈가 있다': 'literally "there is a bone in it" — a remark with a hidden barb',
  '가슴을 치다': 'literally "to strike the chest" — to beat one\'s breast in grief',
  '눈이 높다': 'literally "the eyes are high" — to have exacting standards',
  '콧대가 높다': 'literally "the bridge of the nose is high" — haughty',
  '가슴이 치밀다': 'literally "the chest surges" — emotion welling up',
  '길을 찾다': 'literally "to look for the road" — to find one\'s way',
  '길을 잃다': 'literally "to lose the road" — to get lost',
  '눈길을 끌다': 'literally "to pull the gaze" — to catch the eye',
  // Fourth pass. Body-part idioms are worth the gloss for the same reason as the rest: the
  // literal reading is how the meaning is remembered.
  '발이 넓다': 'literally "the feet are wide" — to know a great many people',
  '귀가 얇다': 'literally "the ears are thin" — easily persuaded',
  '손이 크다': 'literally "the hand is big" — generous, cooks and gives in quantity',
  '입이 가볍다': 'literally "the mouth is light" — cannot keep a secret',
  '발 벗고 나서다': 'literally "to step out with bare feet" — to throw oneself into helping',
  '낯이 익다': 'literally "the face is ripe" — to look familiar',
  '낯이 설다': 'literally "the face is unripe" — to look unfamiliar',
  '입을 모으다': 'literally "to gather mouths" — to say the same thing in unison',
  '손을 씻다': 'literally "to wash one\'s hands" — to break with a bad business for good',
  '발을 끊다': 'literally "to cut one\'s feet" — to stop going somewhere entirely',
  '손을 잡다': 'literally "to take hands" — to join forces',
  '허리띠를 졸라매다': 'literally "to tighten the belt" — to cut back and endure',
  '티끌 모아 태산': 'literally "specks gathered make a great mountain" — many small amounts add up',
  '식은 죽 먹기': 'literally "eating cold porridge" — trivially easy',
  '누워서 떡 먹기': 'literally "eating rice cake lying down" — even easier than that',
  '우물 안 개구리': 'literally "a frog in a well" — someone who mistakes their corner for the world',
  '그림의 떡': 'literally "rice cake in a painting" — desirable and out of reach',
  '뜸을 들이다': 'literally "to let the rice steam" — to hold off and keep people waiting',
  '먼지를 털다': 'literally "to beat the dust out" — to dust something down',
};

// Discourse connectives, all native Korean constructions.
const DISCOURSE = {
  '그러므로': 'native connective — 그러하다 + -므로 (because it is so)',
  '따라서': 'native connective — 따르다 (to follow) + -아서',
  '이에따라': 'native connective — 이에 (to this) + 따라 (following)',
  '잇따라': 'native connective — 잇다 (to join) + 따라',
  '왜냐하면': 'native connective — 왜 (why) + -냐 하면 (if one asks)',
  '그럼에도 불구하고': 'native + Sino — 그럼에도 (even so) + 不拘하고 (without regard)',
  '한편': 'native/Sino — 한 (one) + 便 (side)',
  '한편으로는': '한편 (one side) + -으로는 (as for)',
  '다른 한편으로는': '다른 (other) + 한편 + -으로는',
  '바꾸어 말하면': 'native — 바꾸다 (to change) + 말하다 (to say) + -면',
  '말하자면': 'native — 말하다 + -자면 (if one is to say)',
  '들자면': 'native — 들다 (to raise, cite) + -자면',
  '비유하자면': '比喩 (analogy) + 하자면',
  '정리하자면': '整理 (to order) + 하자면',
  '요약하자면': '要約 (to summarise) + 하자면',
  '요약하건대': '要約 + -하건대 (in so summarising)',
  '다음으로': 'native — 다음 (next) + -으로',
  '끝으로': 'native — 끝 (end) + -으로',
  '다음주': 'native 다음 (next) + 週 (week)',
  '다음달': 'native 다음 (next) + 달 (month)',
  '드디어': 'native adverb 드디어 (at last)',
  '도리어': 'native adverb 도리어 (on the contrary)',
  // Fourth pass.
  '요컨대': '要 (essential) + -컨대 — "if one takes the essentials"',
  '예컨대': '例 (example) + -컨대 — "if one takes an example"',
  '한마디로': 'native — 한 (one) + 마디 (word, joint) + -로',
  '다시말해': 'native — 다시 (again) + 말하다 (to say)',
  '종래에는': '從來 (up to now) + 에는',
  '총괄하여': '總括 (to sum up) + 하여',
  '통틀어': 'native — 통 (whole) + 틀다 (to turn), taken all together',
  '첫째': 'native ordinal — 첫 (first) + -째',
  '둘째': 'native ordinal — 둘 (two) + -째',
  '셋째': 'native ordinal — 셋 (three) + -째',
  '비록': 'native concessive adverb',
  '나아가': 'native — 나아가다 (to go forward)',
  '오히려': 'native adverb',
  '게다가': 'native — 거기에다가 contracted',
  '더욱이': 'native — 더욱 (more) + -이',
  '아울러': 'native — 아우르다 (to encompass)',
  '마찬가지로': 'native — 마찬가지 (the same thing) + -로',
  '차라리': 'native adverb',
  '하물며': 'native adverb',
  '정작': 'native adverb',
  '연이어': 'native — 잇다 (to join) reduplicated',
  '덧붙여': 'native — 덧 (in addition) + 붙이다 (to attach)',
  '반면에': '反面 (the reverse side) + 에',
  '그리하여': 'native — 그리하다 (to do so) + -여',
  '그로인해': '그로 (by that) + 因 (cause) + 해',
  '그렇다면': 'native — 그렇다 (to be so) + -면',
  '그결과': '그 (that) + 結果 (result)',
  '설날': 'native — 설 (new year) + 날 (day)',
  '이번주': '이번 (this time) + 週 (week)',
};

// Multi-syllable loanwords that appear inside compounds, longest first, so a compound such
// as 데이터 센터 can be recognised from its parts the way sino-partial handles hanja roots.
const LOAN_ROOTS_BY_LEN = Object.keys(LOANWORDS)
  .filter(k => k.length >= 2)
  .sort((a, b) => b.length - a.length);

// ─────────────────────────────────────────────────────────────────────────────

function eumhun(tokens) {
  return tokens.map(t => {
    const en = EUMHUN_EN[t];
    if (!en) { throw new Error(`Missing English gloss for eumhun token: "${t}"`); }
    const [char, , reading] = t.split(' ');
    return [char, reading, en];
  });
}

// 두음법칙 — the initial-sound rule. Word-initial ㄹ and ㄴ shift in Sino-Korean, so 旅 (려)
// surfaces as 여 in 여행 and 路 (로) as 노 in 노선. Showing only the dictionary reading looks
// like a typo next to the word on screen; showing only the surface form hides the rule. So
// where they differ the reading becomes "려 → 여", which teaches it.
//
// Applied by position, and only for a word whose syllable count matches its hanja count —
// otherwise there is no reliable syllable-to-character alignment to compare against.
function markInitialSoundRule(ko, parts) {
  if (!parts || parts.length !== ko.length) return parts;
  return parts.map((p, i) => (p[1] === ko[i] ? p : [p[0], `${p[1]} → ${ko[i]}`, p[2]]));
}

// Derivational suffixes that attach to a Sino-Korean root without changing it.
// 건강하다 -> 건강 (健康) + 하다, so the curated hanja for the root still applies.
// Ordered longest-first so 시키다 wins over 다.
const DERIV_SUFFIXES = [
  ['시키다', 'sino-passive'], ['스럽다', 'sino-adj'], ['롭다', 'sino-adj'],
  ['하다', 'sino-verb'],      ['되다', 'sino-passive'],
  ['적이다', 'sino-adj'],     ['적', 'sino-adj'],
];

// Curated Sino roots of 2+ syllables, longest first, for compound matching.
const SINO_ROOTS_BY_LEN = Object.keys(SINO)
  .filter(k => k.length >= 2)
  .sort((a, b) => b.length - a.length);

function classify(ko) {
  if (SINO[ko])        { const [h, t] = SINO[ko];              return { o: 'sino', h, p: markInitialSoundRule(ko, eumhun(t)) }; }
  if (MIXED[ko])       { const [h, t, n] = MIXED[ko];          return { o: 'mixed', h, p: eumhun(t), n }; }
  if (LOAN_MIXED[ko])  { const [h, t, l] = LOAN_MIXED[ko];     return { o: 'loan-mixed', h, p: eumhun(t), l }; }
  if (MIXED_NATIVE[ko]) { const [h, t, n] = MIXED_NATIVE[ko];   return { o: 'mixed-native', h, p: eumhun(t), n }; }
  if (MIXED_LOAN[ko])  { const [h, t, l] = MIXED_LOAN[ko];     return { o: 'mixed-loan', h, p: eumhun(t), l }; }
  if (LOANWORDS[ko])   { return { o: 'loan', l: LOANWORDS[ko] }; }
  if (NATIVE_NOTE[ko]) { return { o: 'native', note: NATIVE_NOTE[ko] }; }
  if (NATIVE_LOOKUP.has(ko)) { return { o: 'native' }; }
  if (IDIOMS[ko])      { return { o: 'idiom', note: IDIOMS[ko] }; }
  if (DISCOURSE[ko])   { return { o: 'discourse', note: DISCOURSE[ko] }; }
  if (NATIVE_PREDICATES[ko]) { return { o: 'native', note: NATIVE_PREDICATES[ko] }; }

  // A curated Sino root carrying a derivational suffix keeps its hanja.
  for (const [suf, kind] of DERIV_SUFFIXES) {
    if (!ko.endsWith(suf)) continue;
    const root = ko.slice(0, -suf.length);
    if (SINO[root]) {
      const [h, t] = SINO[root];
      return { o: kind, h, p: eumhun(t), s: suf };
    }
    if (LOANWORDS[root]) return { o: 'loan', l: LOANWORDS[root], s: suf };
  }

  // Compounds built on curated Sino roots: 건강검진 contains 건강 (健康), so the word
  // is certainly Sino-Korean even though we only know part of the hanja. Scans
  // left to right taking the longest root at each position, so 중앙도서관 yields
  // both 中央 and 圖書館.
  //
  // Restricted to roots of 2+ syllables — a single Hangul syllable maps to many
  // characters (차 = 茶 / 車 / 差 / 次), so one-syllable matching would emit wrong
  // etymology. Emitted as `sino-partial`; `k` lists the parts we can vouch for.
  const found = [];
  for (let i = 0; i < ko.length; ) {
    const root = SINO_ROOTS_BY_LEN.find(r => ko.startsWith(r, i));
    if (root) { found.push(root); i += root.length; } else { i++; }
  }
  if (found.length) {
    return {
      o: 'sino-partial',
      h: found.map(r => SINO[r][0]).join(''),
      p: found.flatMap(r => eumhun(SINO[r][1])),
      k: found,
    };
  }

  // Same idea for loanwords: 데이터 센터 is 데이터 + 센터, 백신 프로그램 is a Sino root we do
  // not have plus 프로그램. Multi-syllable only, for the same ambiguity reason. The scan
  // skips any position that matches nothing, so a word-space between parts costs nothing.
  const loanParts = [];
  for (let i = 0; i < ko.length; ) {
    const r = LOAN_ROOTS_BY_LEN.find(x => ko.startsWith(x, i));
    if (r) { loanParts.push(r); i += r.length; } else { i++; }
  }
  if (loanParts.length) {
    return { o: 'loan-partial', l: loanParts.map(r => LOANWORDS[r]).join(' + '), k: loanParts };
  }

  // Suffix heuristics for Sino-Korean words we have no curated hanja for.
  if (ko.endsWith('하다') && ko.length >= 4)            return { o: 'sino-verb' };
  if (ko.endsWith('되다') || ko.endsWith('시키다'))      return { o: 'sino-passive' };
  if (ko.endsWith('적'))                                 return { o: 'sino-adj' };
  if (/[성력감]$/.test(ko))                              return { o: 'sino-noun' };

  // Honest default. The old VOCAB_FACTS claimed "고유어 (Native Korean word)" for
  // 1090 words with no evidence, which mislabels plenty of Sino-Korean vocabulary
  // (건강검진, 환경오염, 기술혁신 …). Unknown stays unknown; the UI shows
  // pronunciation and syllable structure instead of asserting an origin.
  return { o: 'unknown' };
}

// ── Build ────────────────────────────────────────────────────────────────────
const facts = {};
const stats = {};
let total = 0;

for (const level of levelsData) {
  for (const w of (level.words || [])) {
    const ko = (w.ko || '').normalize('NFC');
    if (!ko) continue;
    total++;
    if (facts[ko]) continue;           // levels.json has 1500 unique ko, but be safe
    const f = classify(ko);
    facts[ko] = f;
    stats[f.o] = (stats[f.o] || 0) + 1;
  }
}

// ── Guard: whole-word curation must still match a real headword ──────────────
//
// These six maps are keyed on complete words, unlike SINO and LOANWORDS which also hold
// bare roots for compound matching. So a key here that matches nothing in levels.json is
// dead curation — the usual cause is a headword being respelled (the 띄어쓰기 pass moved
// 어깨가무겁다 to 어깨가 무겁다) and the map not being updated with it. The word silently
// falls back to `unknown` and coverage drops with nothing to point at.
const WHOLE_WORD_MAPS = {
  MIXED, MIXED_LOAN, NATIVE_NOTE, IDIOMS, DISCOURSE, NATIVE_PREDICATES,
  // NATIVE_SET is a list, not a map, but the same rule applies: a headword that is not there
  // any more, or that an earlier branch of classify() now claims, is dead curation.
  NATIVE_SET: Object.fromEntries(NATIVE_SET.map(k => [k, true])),
};
const headwords = new Set(
  levelsData.flatMap(l => (l.words || []).map(w => (w.ko || '').normalize('NFC')))
);
const orphaned = Object.entries(WHOLE_WORD_MAPS).flatMap(([name, map]) =>
  Object.keys(map).filter(k => !headwords.has(k.normalize('NFC'))).map(k => `${name}['${k}']`)
);
if (orphaned.length) {
  console.error('\nERROR: curated entries that match no word in levels.json:');
  orphaned.forEach(o => console.error(`  ${o}`));
  console.error('Either the headword was respelled, or the entry is stale. Fix, then re-run.');
  process.exit(1);
}

// ── Guard: every emitted origin class must be renderable by the game ─────────
//
// renderOrigin() in game.js is a switch with a `default: return ''`, so introducing a new
// origin class here and forgetting to add a case there silently produces entries that are
// curated but display nothing. That happened once already with idiom / discourse /
// loan-partial, so the generator now refuses to emit a class game.js cannot render.
const gameJs = fs.readFileSync(path.join(ROOT, 'game.js'), 'utf8');
const renderOriginBody = gameJs.slice(
  gameJs.indexOf('function renderOrigin('),
  gameJs.indexOf('function renderStructure(')
);
const renderable = new Set(
  [...renderOriginBody.matchAll(/case '([a-z-]+)':/g)].map(m => m[1]).concat('unknown')
);
const unrenderable = Object.keys(stats).filter(o => !renderable.has(o));
if (unrenderable.length) {
  console.error('\nERROR: these origin classes have no case in game.js renderOrigin():');
  unrenderable.forEach(o => console.error(`  ${o} (${stats[o]} words would show no origin)`));
  console.error('Add a case for each in renderOrigin(), then re-run.');
  process.exit(1);
}

const out = path.join(ROOT, 'facts.json');
fs.writeFileSync(out, JSON.stringify(facts), 'utf8');
// Mirror into assets/, which main.py serves from and admin/lib/sync.js keeps in step.
const assetsFacts = path.join(ROOT, 'assets', 'facts.json');
if (fs.existsSync(path.dirname(assetsFacts))) fs.copyFileSync(out, assetsFacts);

const kb = (fs.statSync(out).size / 1024).toFixed(1);
console.log(`facts.json written: ${Object.keys(facts).length} entries from ${total} words, ${kb} KB`);
console.log('Origin breakdown:');
const curated = total - (stats.unknown || 0);
Object.entries(stats).sort((a, b) => b[1] - a[1])
  .forEach(([k, v]) => console.log(`  ${k.padEnd(13)} ${String(v).padStart(5)}`));
console.log(`\nCoverage: ${curated}/${total} curated (${(curated / total * 100).toFixed(1)}%), ` +
            `${Object.values(facts).filter(f => f.h).length} with hanja`);
console.log(`All ${Object.keys(stats).length} origin classes are renderable by game.js ✓`);
