const fs = require('fs');
const path = require('path');

const rootGamePath = path.join(__dirname, '../../game.js');
const gameContent = fs.readFileSync(rootGamePath, 'utf8');

// Extract PixelArtRenderer code and get generated keys
const pixelArtRendererCode = gameContent.substring(
  gameContent.indexOf('class PixelArtRenderer'),
  gameContent.indexOf('const K = {')
);

class RecordingScene {
  constructor() {
    this.createdKeys = new Set();
    this.textures = { exists: () => false, remove: () => {}, get: () => ({ setFilter: () => {} }) };
    this.anims = { exists: () => false, create: () => {} };
    this.make = {
      graphics: () => ({
        fillStyle: () => {},
        fillRect: () => {},
        generateTexture: (key) => this.createdKeys.add(key),
        destroy: () => {}
      })
    };
  }
}

const evalFn = new Function('Phaser', pixelArtRendererCode + '; return PixelArtRenderer;');
const PixelArtRenderer = evalFn({});
const scene = new RecordingScene();
PixelArtRenderer.generateAllTextures(scene);

// Search for all texture key strings used in Phaser constructors or methods:
// e.g., scene.add.image(x, y, 'KEY'), scene.add.sprite(x, y, 'KEY'), .setTexture('KEY'), frames: [{ key: 'KEY' }]
const keyUsagePatterns = [
  /add\.(image|sprite|tileSprite)\s*\(\s*[^,]+,\s*[^,]+,\s*['"]([^'"]+)['"]/g,
  /setTexture\s*\(\s*['"]([^'"]+)['"]/g,
  /key:\s*['"]([^'"]+)['"]/g,
  /play\s*\(\s*['"]([^'"]+)['"]/g
];

const foundUsedKeys = new Set();
keyUsagePatterns.forEach(pattern => {
  let match;
  while ((match = pattern.exec(gameContent)) !== null) {
    // Group index 2 for add.image, group index 1 for setTexture/key/play
    const key = match[2] || match[1];
    if (key && !key.includes('/') && !key.includes('.')) {
      foundUsedKeys.add(key);
    }
  }
});

console.log('=== TEXTURE KEY USAGE ANALYSIS IN GAME.JS ===\n');
console.log(`Total generated keys in PixelArtRenderer: ${scene.createdKeys.size}`);
console.log(`Total texture key references found in game.js: ${foundUsedKeys.size}`);

const matched = [];
const missingFromRenderer = [];

foundUsedKeys.forEach(key => {
  if (scene.createdKeys.has(key)) {
    matched.push(key);
  } else {
    // Exclude Phaser built-in or non-sprite keys if applicable
    missingFromRenderer.push(key);
  }
});

console.log(`\nKeys used in game.js that ARE generated by PixelArtRenderer (${matched.length}):`);
matched.forEach(k => console.log('  [VALID] ' + k));

console.log(`\nKeys used in game.js NOT generated by PixelArtRenderer (${missingFromRenderer.length}):`);
missingFromRenderer.forEach(k => console.log('  [OTHER/MISSING] ' + k));
