const fs = require('fs');
const path = require('path');

const rootGamePath = path.join(__dirname, '../../game.js');
const gameContent = fs.readFileSync(rootGamePath, 'utf8');

// Extract PixelArtRenderer code and run it with a recording MockScene
const pixelArtRendererCode = gameContent.substring(
  gameContent.indexOf('class PixelArtRenderer'),
  gameContent.indexOf('const K = {')
);

class RecordingScene {
  constructor() {
    this.createdKeys = [];
    this.keyDetails = [];
    this.textures = {
      exists: (key) => false,
      remove: (key) => {},
      get: (key) => ({ setFilter: () => {} })
    };
    this.anims = {
      exists: () => false,
      create: () => {}
    };
    this.make = {
      graphics: () => ({
        fillStyle: () => {},
        fillRect: () => {},
        generateTexture: (key, w, h) => {
          this.createdKeys.push(key);
          this.keyDetails.push({ key, width: w, height: h });
        },
        destroy: () => {}
      })
    };
  }
}

const evalFn = new Function('Phaser', pixelArtRendererCode + '; return PixelArtRenderer;');
const PixelArtRenderer = evalFn({});

const scene = new RecordingScene();
PixelArtRenderer.generateAllTextures(scene);

console.log('=== EXACT RUNTIME TEXTURE KEYS GENERATED BY PIXELARTRENDERER ===\n');
console.log(`Total texture generation calls: ${scene.createdKeys.length}`);

const counts = {};
scene.keyDetails.forEach(item => {
  counts[item.key] = (counts[item.key] || 0) + 1;
});

const duplicates = Object.entries(counts).filter(([k, c]) => c > 1);
console.log(`Unique texture keys: ${Object.keys(counts).length}`);

if (duplicates.length > 0) {
  console.log('\n[CRITICAL DETECTED] DUPLICATE TEXTURE KEYS AT RUNTIME:');
  duplicates.forEach(([k, c]) => {
    console.log(`  - Key "${k}" generated ${c} times!`);
  });
} else {
  console.log('\n[PASS] No duplicate keys detected at runtime.');
}

console.log('\nList of all generated keys and dimensions:');
scene.keyDetails.forEach((item, idx) => {
  console.log(`${(idx + 1).toString().padStart(2, ' ')}. ${item.key.padEnd(28, ' ')} (${item.width}x${item.height})`);
});
